### ISSUE TITLE
Incorrect formatting on paste

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#10]
When pasting into a quoted string, the pasted text is formatted as though it is an expression. For instance, pasting the regex pattern `(?i:if)` produces `( ? i : if )`, which will obviously not work. This does not occur when pasting similar expressions (even valid ones like `(a?b:c)`) into a JavaScript string.

I was very surprised to find that the extension overrides the "global" `editor.formatOnPaste` setting, after wasting hours chasing VS Code bug reports trying to figure out why VS Code was messing with my pasted code.  There seems to be no good reason for the extension to override `editor.formatOnPaste`, `editor.detectIndentation` or `editor.autoIndent`. It should respect the user's global preference.

**Comment by thqby** [comment]
the setting of language can overrides the global setting.
```
"[ahk2]": {
  "editor.detectIndentation": false,
  "editor.autoIndent": "full"
}
```

**Comment by thqby** [comment]
the setting of language can overrides the global setting.
```
"[ahk2]": {
  "editor.detectIndentation": false,
  "editor.autoIndent": "full"
}
```

**Comment by Lexikos** [comment]
> the setting of language can overrides the global setting.

I worked that out already, and am overriding all of the defaults you specified in the extension. I already have my solution, but I still think that your use of `"configurationDefaults"` for the three settings I mentioned provides a poor experience for new users.

If the user has set global `"editor.formatOnPaste": false`, for instance, I can't imagine any good reason that any language extension should override that. If the user wants formatOnPaste for specific languages, the user can override their own global setting.

Within the Settings UI, there is no indication that the "Editor: Format on Paste" setting is overridden by language-specific "defaults". I think this is a design issue within VSCode, but you can easily avoid it by removing unnecessary "defaults" from the extension. microsoft/vscode#58995 describes the main issue and has several links to other issues showing the confusion this causes.
