### ISSUE TITLE
Obscure highlighting error with method `x() =>`

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#101]
```AutoHotkey
class Z {
    MethodWithLongNameOrParameterList() =>
        MsgBox(('Message'), 'This string is highlighted white')
}
```
A part of the issue is that it seems `=>` isn't treated as line continuation, so the following line gets some kind of default treatment.

The other part is that some combination of parentheses causes the final string to be highlighted differently. I'm not sure whether this would be an issue if the continuation was handled correctly.

**Comment by RaptorX** [comment]
Yes it is a problem with the line continuation.

## In the correct highlight *[meta.block.method.body]* is selected by the lexer
![image](https://user-images.githubusercontent.com/328761/171693056-339288a8-1389-416a-91dd-1d0e1dd649c8.png)
![image](https://user-images.githubusercontent.com/328761/171693142-a097f870-d70e-4203-a9a2-fe8a16a4519f.png)

---
## while on the incorrect version it never picks the *[method.body]* scope
![image](https://user-images.githubusercontent.com/328761/171693644-9f4a297f-60d4-4f08-a770-244db44bf062.png)
![image](https://user-images.githubusercontent.com/328761/171693679-9ccb9831-0579-4bf9-84d0-a956195e200c.png)
