### ISSUE TITLE
Class folding breaks when immediately preceeded by comment

### ISSUE THREAD

**Issue by OpalMonkey** [thqby/vscode-autohotkey2-lsp#106]
When a block comment is placed immediately above a class definition, folding for the class breaks, the comment and everything inside the class still folds normally.
```
/*
Block
*/
class Test {
    __New() {

    }
}
```

I noticed this while trying out the JSDOC support, but it affects any block comment —even a single line block comment. In fact, with a single-line block comment or inline comment, the folding moves up to the comment and hides the class definition.
```
/* Block */
class Test2 {
    
}

; Inline
class Test3 {
    
}
```

Adding any line between the comment and class definition causes folding to function normally.

**Unfolded vs. Folded:**
![Unfolded vs Folded](https://user-images.githubusercontent.com/1016179/176126080-0f949b68-9bce-42e9-bfbc-de463a28ec1a.png)

Edit: I disabled the other extensions that I know are affect folding while testing this but didn't disable **all** extensions. So hopefully, this isn't due to some other extension or conflict.

**Comment by RaptorX** [comment]
Can confirm, if there's no space between the closing comment and the class, the classes folding breaks.

**Comment by thqby** [comment]
![image](https://user-images.githubusercontent.com/28240311/176438681-5906a4a5-9857-4c42-9761-3d6e41472b53.png)
![image](https://user-images.githubusercontent.com/28240311/176439377-0ddd5e34-95b7-4bfe-8408-49bcb1bce6cb.png)

However, I don't have this problem here.
