### ISSUE TITLE
No suggestion of built in variables without %% in include directive

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#108]
Issue Type: <b>Bug</b>

## Steps
* Use the #include directive
* Start typing a supported  built in A_Variable
### Suggestions should show up as percent signs are optional
![image](https://user-images.githubusercontent.com/328761/176330288-cd8cf5f4-03bb-49de-a87d-835a97a8448a.png)
### No suggestions are shown
![image](https://user-images.githubusercontent.com/328761/176330313-e11443fb-f7c9-47e6-93ee-fd4636e82159.png)
### After typing some variables errors are resolved (when the path exists)
![image](https://user-images.githubusercontent.com/328761/176330326-b613a443-00b4-44e2-8f46-1037f59b3e21.png)
## Suggestions
One of the issues is that the lexer tries to validates paths and while they are not valid the lexer enters in to an error state and nothing else seems to work.

Probably the lexer should validate the path after a new line when the path is completed.
In the meantime suggestions should work as expected because according to the documentation:

> Built-in variables may be used by enclosing them in percent signs (for example, [#Include](https://lexikos.github.io/v2/docs/commands/_Include.htm) "%[A_ScriptDir](https://lexikos.github.io/v2/docs/Variables.htm#ScriptDir)%"). Percent signs which are not part of a valid variable reference are interpreted literally. All built-in variables are valid, except for [A_Args](https://lexikos.github.io/v2/docs/Variables.htm#Args) and built-in classes.

**And as shown in the previous example the percent signs seem to be optional. I get no errors when not using the percent signs on variables while doing an include.**

Extension version: 1.3.6
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (21.36GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\OneDrive\\Documents\\AutoHotkey\\lib\\SQLite --crash-reporter-id 1eed22db-bc5c-446b-a877-f742be520d0c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by thqby** [comment]
> And as shown in the previous example the percent signs seem to be optional. I get no errors when not using the percent signs on variables while doing an include.

This is not optional, `.\XXXX\..\` is always equal to `.\`.

**Comment by RaptorX** [comment]
> > And as shown in the previous example the percent signs seem to be optional. I get no errors when not using the percent signs on variables while doing an include.

What I meant is that the autohotkey interpreter does not see `A_LineFile\..\` as an error. So it should be suggested

**Comment by thqby** [comment]
It's just that the wrong usage just doesn't cause an error in this case. Replacing `A_LineFile` with any `\w+` string is the same, and this line is redundant

**Comment by RaptorX** [comment]
> It's just that the wrong usage just doesn't cause an error in this case. Replacing `A_LineFile` with any `\w+` string is the same, and this line is redundant

Correct. I agree with that.

So in the meantime (until that changes) the lexer should be a bit laxed with that usage.
