### ISSUE TITLE
New syntax in v2.beta.6 

### ISSUE THREAD

**Issue by aseiot** [thqby/vscode-autohotkey2-lsp#109]
Following syntax has been supported in v2.beta.6.

```
x := {key:y?}
y:=[z?]

FuncA(x,y?){

}

FuncB(x,&y?){

}

; param with expression
FuncC(x,y:=x+10){

}
```

**Comment by Lexikos** [comment]
That's not all.

> Added `.Get(Index [, Default])` and `.Default` to Array.
Added `var?` and `unset` for use with optional parameters.
Added `var ?? value`, mostly equivalent to `IsSet(var) ? var : value`.
Added the ability to specify arbitrary expressions for parameter defaults (not yet documented).
Added `static fn()` for preventing capture of outer non-static vars.

But some of those are already handled correctly.

**Comment by thqby** [comment]
It has been released.
