### ISSUE TITLE
代码格式化 BUG

### ISSUE THREAD

**Issue by chaoxi24** [thqby/vscode-autohotkey2-lsp#11]
谢谢您提供的工具。

我发现了代码格式化的一个BUG，当else 后面是"()"时，它会把else当作函数。
比如
```
	if a=2
		b:=3
	else (b:=3,a:=2)
```
会处理为：
```
	if a = 2
		b := 3
	else(b := 3, a := 2)
```

顺便请问可以把ahk的格式化工具作为单独的命令行工具发布吗？
因为VSCODE不是我的主力编辑器，而我又十分依赖这个工具。谢谢。

**Comment by thqby** [comment]
下个版本修复，你的主力编辑器不支持lsp协议吗

**Comment by chaoxi24** [comment]
是的，EmEditor好像不支持LSP。而且如果有一个afml工具，我更想把它集成到全局快捷键上，能随时随地格式代码。

另外一个错误同样来自 else
```
	if p_w
		size:={x:p_x}
	else
		size:={x:z_x,y:z_y}
```

```
	if p_w
		size:={x:p_x} else
		size:={x:z_x,y:z_y}
```

**Comment by thqby** [comment]
写代码用vscode不好吗，还有调试等emeditor没有的功能😂

**Comment by chaoxi24** [comment]
它基于浏览器开发，我觉得过于臃肿笨重，无论是文件打开速度，操作灵敏度，都距理想状态差很远。

**Comment by thqby** [comment]
老机子启动有点慢，其他还好。neovim可以用vscode的插件。

https://github.com/neoclide/coc.nvim/issues/3023

**Comment by chaoxi24** [comment]
看到NVIM的介绍——GUI、IDE、Web 浏览器可以将 Neovim 嵌入 为编辑器或脚本宿主。
又一个scite？好像可以将其作为AHKGUI控件，可惜没搜索到ahk相关的资料。
