### ISSUE TITLE
Extension does not recognize arrow functions as valid default parameters

### ISSUE THREAD

**Issue by strawhat-dev** [thqby/vscode-autohotkey2-lsp#112]
Arrow/anonymous functions or callbacks or however you may call them, do not seem to be considered valid as default parameters as shown in the following:

![image](https://user-images.githubusercontent.com/63446377/177047725-c61ef92e-556d-44e6-a6de-333d5ec44dce.png)

However, this compiles and works fine as expected since arrow functions are recognized in [ahk 2](https://lexikos.github.io/v2/docs/Variables.htm#fat-arrow). This is useful for when you want to optionally define a callback for specific events. Here is a simpler example that you may try (which also gives "Invalid parameter definition"):

```ahk
example(doSomething := () => MsgBox('doThis')) {
  doSomething()
}

#`::example()
#+`::example(() => MsgBox('doThat'))
```

As a suggestion, maybe an option to disable specific rules, if possible, would be a good idea to help mitigate false positives like these. Thanks!!

**Comment by thqby** [comment]
This is the same issue as [#109].
