### ISSUE TITLE
No suggestions when next to character

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#120]
Issue Type: <b>Bug</b>

# Situation
Sometimes I typed a command and later I decide to wrap it with another command:

```
RegexReplace(var,"string") ; started with this and I decided to outputdebug it
Outputdebug RegexReplace(var,"string") ; like this

```
In other lexers I just simply press home, start typing and press Ctrl+Space to get suggestions. like this:

![image](https://user-images.githubusercontent.com/328761/179040603-77015eac-0144-4684-93a9-c7d4595dd1e0.png)

The above image is from the Autohotkey-Plus-Plus extension for v1

# Result
I get no suggestions

![image](https://user-images.githubusercontent.com/328761/179040732-a7ee9110-ebda-49e1-9ca3-38087fda8997.png)

I am forced to always type a space before getting suggestions.

# Notes
This doesnt happen if I do the same but with symbols instead of word characters as shown here:

![image](https://user-images.githubusercontent.com/328761/179040817-79b82d4c-076f-4fa5-a30b-219bda5883f6.png)

Extension version: 1.4.4
VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (21.55GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\OneDrive\\Desktop\\Word Obj.ahk --crash-reporter-id 1eed22db-bc5c-446b-a877-f742be520d0c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by thqby** [comment]
This is not a bug. The trigger mechanism of code snippets and completions is different.

**Comment by RaptorX** [comment]
> This is not a bug. The trigger mechanism of code snippets and completions is different. Code snippets can always trigger, but completion is not.
> 
> Currently, it can only be entered in . or # is forced to trigger completion, and it also is triggered when a word begins to be input. It is impossible to set every character as a trigger. After all, there are many characters that can be used as symbol names.

How can the other plugin do it then? is it using a different approach?

**Comment by thqby** [comment]
These plugins have code snippets for built-in functions, and you can try to reproduce using user-defined functions.

**Comment by RaptorX** [comment]
> These plugins have code snippets for built-in functions, and you can try to reproduce using user-defined functions.

![image](https://user-images.githubusercontent.com/328761/179336889-9d29de9f-5019-4bc9-8315-cb79211cdfb2.png)

I get suggestions with user-defined functions and typing right next to a text character.

**Comment by thqby** [comment]
https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/blob/main/src/extension.ts#L82
Enter a space or `.`  to force triggering. and typing in front of a word is not triggered.

**Comment by RaptorX** [comment]
> Sorry, I misunderstood, you meant `CTRL+space` to trigger

Yes, thats right. When typing right next to a word you can force suggestions by pressing CTRL + Space but your plugging returns nothing as shown in the OP.
