### ISSUE TITLE
Images won't load on VS Code Browser Marketplace

### ISSUE THREAD

**Issue by KingQuarter** [thqby/vscode-autohotkey2-lsp#131]
On https://marketplace.visualstudio.com/items?itemName=thqby.vscode-autohotkey2-lsp, the images won't load.
![image](https://user-images.githubusercontent.com/92368853/182011818-a6f57838-2acb-467c-baf8-ffe8bb67ff46.png)

I think it's a 403 error.
![image](https://user-images.githubusercontent.com/92368853/182012458-f291df0d-ca1f-4144-b8de-3c4d995be0b8.png)

Tested on Edge, Firefox, Chrome, and Safari.

**Comment by OpalMonkey** [comment]
I can confirm that the images are showing as broken for me too.

Not sure where the favicons that show a 403 error are supposed to show up, but I think the main images that show as broken on the page are returning a 302 status (found). Though I don't do much web-based stuff like this, so I could well be wrong.

![2022-07-31_00-28-28_497](https://user-images.githubusercontent.com/1016179/182013308-5e6590b5-1f91-4702-a760-af81093c9c9c.png)
 
Tested on Chrome v103.

**Comment by KingQuarter** [comment]
Fixed by d5b17d9378afd3334f3d6809c66ba0b316154016
