### ISSUE TITLE
False error for continuation section within object literal

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#136]
This is a valid expression, using a continuation section to avoid the need for a delimiting comma:
```AutoHotkey
view := {
(Join,
    65406: "Lines"
    65407: "Variables"
    65408: "Hotkeys"
    65409: "KeyHistory"
)}
```
The extension flags the entire continuation section as "Error in object literal".

This occurs even with a basic optionless continuation section (which would be entirely redundant in v2, but is still valid).

**Comment by lstrfwp** [comment]
There are errors when comment option is used:
```
obj := {
(Join, C
    ; comment
    prop: "A"
    ; comment
    1234: "B"
)}
```
