### ISSUE TITLE
False error in hotstring when using the ? option

### ISSUE THREAD

**Issue by KingQuarter** [thqby/vscode-autohotkey2-lsp#144]
![image](https://user-images.githubusercontent.com/92368853/184148734-ea72f87b-7bff-4ad5-a115-c340d1f7a4a1.png)

**Comment by RaptorX** [comment]
This issue was introduced by the latest update.

![image](https://user-images.githubusercontent.com/328761/184150051-7d40917f-868c-4293-9973-89323c63f924.png)

Version 1.5.1 doesnt have this problem.

**Comment by KingQuarter** [comment]
Although 1.5.1 doesn't have this issue, it still has a few other issues. I would just be replacing a problem with another problem.

**Comment by RaptorX** [comment]
I was not suggesting to go back to the previous version, but rather giving [thqby](https://github.com/thqby) a bit more context for clues as to where the problem lays.

After checking the code I noticed he replaced the whole regular expression for hotstring and hotkey matching.
