### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#150]
Type: <b>Bug</b>

I get the following error when trying to compile:

![image](https://user-images.githubusercontent.com/328761/184502711-dd2262c7-54aa-457b-a983-7417ed94a64e.png)

**_Seems like the extension is passing the path without quotes which will cause an issue with spaces in paths._**

# Expected
no errors

# Notes
AHK2Exe was updated to the latest version which seems to support Autohotkey.exe now according to [this post](https://www.autohotkey.com/boards/viewtopic.php?p=476468#p476468).

But it doesnt matter if I point to Autohotkey.exe or v2\Autohotkey64.exe I am getting the same error.

---

Extension version: 1.5.1
VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (21.52GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\Dropbox\\Guests\\the-Automator\\Client Work\\Lyra Networks\\zQuorum --crash-reporter-id bdc99747-9c48-41d5-87e2-d320011e638b|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252
azure-dev_surveyonecf:30545436

```

</details>

**Comment by thqby** [comment]
Command line arguments are missing `"`.
And you can now remove the '/base ${execPath}' part of the default, the script's directive `;@Ahk2Exe-Base xxx` will take effect.
