### ISSUE TITLE
"Invalid File Encoding" for files that aren't open

### ISSUE THREAD

**Issue by megamorphg** [thqby/vscode-autohotkey2-lsp#151]
On startup, extension seems to be checking files in the workspace's folder that aren't open (or even referenced in any open scripts).

![image](https://user-images.githubusercontent.com/1782353/184504401-700e05da-b618-4dd6-9f12-fb170050f6eb.png)

**Comment by thqby** [comment]
Valid ahk v2 file encodings are `UTF-8` and `UTF-16`.
In the next version,  files that are not opened and not included will not show errors.
