### ISSUE TITLE
Go to Definition (Ctrl + Click) on Library's Function Incorrect Library

### ISSUE THREAD

**Issue by megamorphg** [thqby/vscode-autohotkey2-lsp#153]
Steps to Reproduce:
1. Have a library (e.g. UIA_Interface) in two different folder locations and add the parent folders to workspace.
2. #Include the library in folder1 in AHK file 1
3. #Include the library in folder2 in AHK file 2
4. Go to definition of a function in folder 1 and folder 2 and observe it goes to the same definition instead of the definition of the correct #include

Example of [AHK file 1](https://github.com/Descolada/UIAutomation/blob/main/Examples/Example1_Notepad.ahk).

**Comment by thqby** [comment]
Please provide a detailed directory tree for easy reproduce this issuse.

**Comment by thqby** [comment]
![2](https://user-images.githubusercontent.com/28240311/184592445-a81d9841-b49c-4d32-8110-1c0577097cb5.gif)

I don't see any bugs in the 'Go to definition' feature

**Comment by thqby** [comment]
Are you sure you activated this extension?
![image](https://user-images.githubusercontent.com/28240311/184666114-ec0e5771-1f07-4871-92f9-24552b068031.png)
