### ISSUE TITLE
syntax highlighting issues

### ISSUE THREAD

**Issue by lstrfwp** [thqby/vscode-autohotkey2-lsp#159]
`1.5.1` Expected highlighting

![image](https://user-images.githubusercontent.com/110793221/184732600-ce71b55d-8c16-4dc1-8ddb-121dd8b118f5.png)

`1.5.5` Current highlighting

![image](https://user-images.githubusercontent.com/110793221/184732609-32bf4b2f-19df-49da-bba6-3b9f2005c58f.png)

**Comment by thqby** [comment]
This issuse is same as [#158].
