### ISSUE TITLE
Strange highlighting of hexadecimal prefixes, zero-padded integers and floats

### ISSUE THREAD

**Issue by lvalkov** [thqby/vscode-autohotkey2-lsp#16]
```ahk
        1111
   0.0001111

  0x00001111
   .00001111
   000001111
```
![image](https://user-images.githubusercontent.com/25468197/123356504-23456e80-d568-11eb-92a8-1cc098fde433.png)
Is there a particular reason why hexadecimal numbers, zero-left-padded integers and floating point numbers without leading zeroes are being highlighted this way?
I expected them to be highlighted identically to the non-zero-padded integer and regular float (see first two lines in the screenshot).

**Comment by thqby** [comment]
![Screenshot_20210625_101945_com microsoft rdc android](https://user-images.githubusercontent.com/28240311/123359005-1132f280-d59f-11eb-806b-a90e99951ead.png)
Except for '.000001111', there does not seem to be a problem.

**Comment by thqby** [comment]
![Screenshot_20210625_101945_com microsoft rdc android](https://user-images.githubusercontent.com/28240311/123359005-1132f280-d59f-11eb-806b-a90e99951ead.png)
Except for '.000001111', there does not seem to be a problem.

**Comment by lvalkov** [comment]
![HexadecimalScope](https://user-images.githubusercontent.com/25468197/123363449-d915ba80-d572-11eb-96ab-7dd38589c53e.gif)
If you deem `keyword.other.unit.(exponent | hexadecimal | octal)` to be correct scopes, being assigned correctly (this I do not contest), then I shall adjust my color scheme accordingly. From your screenshot, I can tell yours does not exhibit this issue. Thank you!

`keyword.operator.dot`, however, indeed does not seem to be the correct choice of scope in this particular case.

**Comment by thqby** [comment]
I will merge some textmate scopes.
