### ISSUE TITLE
Hotstring unexpected ':'

### ISSUE THREAD

**Issue by lstrfwp** [thqby/vscode-autohotkey2-lsp#160]
![Code_2022-08-15_17-16-33](https://user-images.githubusercontent.com/110793221/184757511-72ec7bc3-36bc-4e60-bb17-e8ac54a5b0cc.gif)

```
::DOUBLE_BUFFER::
(
    WS_EX_COMPOSITED    := 0x02000000
    WS_EX_LAYERED       := 0x00080000
    DOUBLE_BUFFER       := WS_EX_COMPOSITED | WS_EX_LAYERED
)

:*B0:WS_EX_CLICKTHROUGH:: := 0x0020
```

**Comment by thqby** [comment]
Are you sure it's the latest version?

**Comment by lstrfwp** [comment]
I'm using 1.5.5. The picture is a gif. It shows what happens when I tab to indent with the code above.

**Comment by thqby** [comment]
I did not reproduce the bug.

**Comment by lstrfwp** [comment]
I can reproduce with these steps:
- copy the code above
- paste it in VS Code
- highlight all
- press `tab`

It only appears when I indent the code, and if there is anything in the line after the continuation section (even a space), there's no error.

**Comment by thqby** [comment]
![2](https://user-images.githubusercontent.com/28240311/184802039-c27218e7-8ffd-4268-b114-10f8eb791796.gif)

**Comment by lstrfwp** [comment]
I'm using 4 spaces for tab. There was no problem when I converted space to tab.
