### ISSUE TITLE
[Feature Request] Help Doc CHM Definition Link?

### ISSUE THREAD

**Issue by megamorphg** [thqby/vscode-autohotkey2-lsp#163]
The tooltips are great but sometimes we need more info and rather than searching for this in the help doc, it would be great if we can either:

- click the tooltip link to go to the corresponding page in the CHM
- right click term and Go to Definition to go to page in CHM (F12)

**Comment by lstrfwp** [comment]
You can right click, and go to `Quick Help` or press `ctrl + F1` to go directly to the chm.

**Comment by lstrfwp** [comment]
If I click or highlight a term, and open Quick Help, it automatically opens the page for that term. Does it not work like that for you?

**Comment by thqby** [comment]
![2](https://user-images.githubusercontent.com/28240311/185411422-51f020e0-1e42-40e7-a780-06183521c0b0.gif)
This is a functional demo. The first time you open the CHM file with the quick help command, you may not jump to the search term. If the help window is not closed, subsequent jumps to search terms will be more stable.
