### ISSUE TITLE
incorrect hotstring syntax highlight when using brackets

### ISSUE THREAD

**Issue by lstrfwp** [thqby/vscode-autohotkey2-lsp#165]
![image](https://user-images.githubusercontent.com/110793221/185270840-fc45e56b-5190-4122-bf7f-d9d0eb253315.png)

expected syntax highlight:

![image](https://user-images.githubusercontent.com/110793221/185271954-0d22c856-c8a0-4946-8034-ac6d83f138da.png)

**Comment by thqby** [comment]
`::[test]::` and `::[[::`, etc. these can be solved by turning off the option `editor.bracketPairColorization.enabled`.
