### ISSUE TITLE
Include file can't be found due to apostrophe

### ISSUE THREAD

**Issue by lstrfwp** [thqby/vscode-autohotkey2-lsp#166]
The file exists, but the extension can't find the file if it has an apostrophe (`'`) in the name.

![image](https://user-images.githubusercontent.com/110793221/185726229-9c4db5c3-84b5-4b9c-b9f6-f8ac25bad779.png)

**Comment by krasnovpro** [comment]
Same with folders:
![image](https://user-images.githubusercontent.com/886676/185777610-7c339b75-593b-4d18-a864-cf5e6da2102b.png)

**Comment by thqby** [comment]
`%A_ScriptDir%` is not always correctly identified. In the current case, `A_ScriptDir` is assumed to be `c:\users\......\app\tapkey`.
It is better to use relative paths rather than absolute paths. such as `#include ..\lib`.
