### ISSUE TITLE
Custom Combinations hotkey syntax issue

### ISSUE THREAD

**Issue by Anutim** [thqby/vscode-autohotkey2-lsp#167]
Using Custom Combinations along with additional Modifiers throws an error:
https://streamable.com/u16hsf
(Also, haven't updated for a while until now, but this didn't throw an error before the update.)

**Comment by thqby** [comment]
I can't access this website.

**Comment by Anutim** [comment]
https://user-images.githubusercontent.com/18088499/185757125-0c1be87f-7bd5-4dc3-b210-9485f1b5db37.mp4
