### ISSUE TITLE
Issue with dynamic function calls that include keywords

### ISSUE THREAD

**Issue by OpalMonkey** [thqby/vscode-autohotkey2-lsp#168]
Okay, now this one feels like an obscure issue but figured I may as well report it.

```
v := 'Integer'
OutputDebug Is%v%(1)
OutputDebug !Is%v%(1)
OutputDebug !(Is%v%(1))
```
`Unknown operator use` is reported on line 3 for the `Is` portion. All three calls function properly.

![2022-08-20_18-04-48_062](https://user-images.githubusercontent.com/1016179/185769991-da529cbd-ff93-4227-833e-26db6488d65e.png)

Looks like it extends to dynamic calls using other keywords, too.
```
v := 'Integer'
v2 := 'Test'
OutputDebug If%v%()
OutputDebug %v2%If%v%()
OutputDebug !In%v%()
IfInteger() {
}
TestIfInteger() {
}
InInteger() {
}
```

**Comment by OpalMonkey** [comment]
You sure are quick on some of these fixes!

Just curious, when keywords, etc. are used as part of a dynamic function call, would it be possible for the syntax highlighting to style them as a normal function call? Not a big deal either way and imagine it might be more trouble than it's worth.

**Comment by thqby** [comment]
They are all regarded as part of the variable, so the coloring is better consistent with the variable?

**Comment by thqby** [comment]
They are all regarded as part of the variable, so the coloring is better consistent with the variable.
