### ISSUE TITLE
Parse the static member of a class in v1.5.7

### ISSUE THREAD

**Issue by aseiot** [thqby/vscode-autohotkey2-lsp#169]
![image](https://user-images.githubusercontent.com/600263/185784123-4d60fc95-96d7-4deb-8a9e-dd0ada0331bd.png)

**Comment by aseiot** [comment]
Besides this, I found it failed in some complicated situations. So it is possible to have a way to close this detection?

**Comment by thqby** [comment]
Now there is a Settings option to turn this off.

**Comment by Axlefublr** [comment]
> Now there is a Settings option to turn this off.

Where is it? I've never came across it through reading the package.json file or the vs code settings. 

Do you mean we can disable the error type overall (for all languages, potentially) or for *your* linter specifically? If so, how?

**Comment by thqby** [comment]
only this extension.
