### ISSUE TITLE
[Feature request] Configure custom module-symbols and disable some of the built-in

### ISSUE THREAD

**Issue by KingQuarter** [thqby/vscode-autohotkey2-lsp#173]
To my knowledge, `;;`, `; TODO`, and `;#` are the only ways of making `module`-symbols. See the outline on the left.

![image](https://user-images.githubusercontent.com/92368853/187081454-dbac3bb3-332b-453f-b1e7-846b747e9973.png)

But this conflicts with my use of the [Better Comments](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments) extension. I have configured the `;` tag to strikethrough the entire line, clearly showing I want it commented out. This probably means I don't want it in my outline.

![image](https://user-images.githubusercontent.com/92368853/187079973-3f7d2465-56df-46b8-a03c-9a9b34cc4abd.png)

I have also configured the `=`, `==`, and `===` tags to highlight headers. I want them to be in the outline, but they aren't.

![image](https://user-images.githubusercontent.com/92368853/187080226-5c80011a-e262-4f6e-ac1b-333bbf121646.png)

It would be cool if there was a setting in ahk2-lsp where I could configure a regex pattern to match custom `module`-symbols, such as `^;=+ [^=].+`, which would match my headers. It would also be nice to disable some of the built-in `module`-symbols.

**Comment by thqby** [comment]
set `commenttags` option

**Comment by KingQuarter** [comment]
Thanks for this!
