### ISSUE TITLE
[v1.5.9] ;#region doesn't fold

### ISSUE THREAD

**Issue by KingQuarter** [thqby/vscode-autohotkey2-lsp#177]
There's supposed to be option in the gutter to fold from `;#region` to `;#endregion`, but there's not.
```
;#region tag
code
;#endregion
```

**Comment by Axlefublr** [comment]
I second this. 

```
;{
;}
```

Work though

**Comment by RaptorX** [comment]
I have always used `;{` and `;}` for custom regions because 90% of the editors will use `{` and `}` correctly even if they are commented out.

As soon as you start using words and custom strings for that, you will have a lot of editors that dont support it ^^

**Comment by KingQuarter** [comment]
The nice thing about `;#region` was that not only did it create a folding region, but it also created a module symbol in the outline. Maybe `;{` could be labeled in the same way? e.g. `;{ tag`. This would make `;#region` redundant, and I'd totally support that; I didn't like how `;#region tag` and `;#endregion` made my code look because they're longer than they need to be, distracting me from the tag and the code.

**Comment by RaptorX** [comment]
Maybe I am misunderstanding something but the outline symbols are **not** created by the ;#region tags themselves... 

for example:

![image](https://user-images.githubusercontent.com/328761/188296154-e97ffc56-50cf-46b9-b7d0-6cc3f681e195.png)

The variables are being added to the outline because they are identified as symbols independent of whether they are in a region or not.

I think the language support server identifies things like variables, function definitions, classes and objects as symbols automatically.

**Comment by KingQuarter** [comment]
In v1.5.8 and prior, `;#region` does create `module`-symbols:
![image](https://user-images.githubusercontent.com/92368853/188297286-c72fd593-abd1-4fe4-a6c5-5aeafac393c7.png)

**Comment by RaptorX** [comment]
Oh, now I understand what you mean. I have never used that functionality.

**Comment by Axlefublr** [comment]
> Oh, now I understand what you mean. I have never used that functionality.
> 
> Seems like the other ways of creating tags is working:
> 
> ![image](https://user-images.githubusercontent.com/328761/188298395-4591e6f2-0829-4f04-bbf2-5dd18d896de0.png)
> 
> You can use `;;TagName` or `; TODO something` to create regions in the outline still.

Oh wow! I didn't know about ;; so this is really useful to know, thank you!

**Comment by xmaxrayx** [comment]
Hi many thanks for plug-in, I found it doesn't work with `mini-map` and buggy once you _nested_ them thet other languages have bigger fonts in mini-map

# ahk
- good 🌸 
  - region in "outline"

- Bug 🌸 
  -  not render in mini-map
  -   if you nested "region" it will duplicate in `outline` (see typescript it shows in fold)
![image](https://github.com/user-attachments/assets/b9b14520-a5e3-4888-8446-3309dc6f80e2)


# C
- rendor in mini map still have the outline seems unsupported maybe I need install better/another plugin
![image](https://github.com/user-attachments/assets/098535a5-a25e-4188-be1b-e5cf645f5358)

# typescript 🌟 
- folded outline
- minimap is big font
![image](https://github.com/user-attachments/assets/3f381366-ebf4-4390-9806-13231d52ceb6)

**Comment by thqby** [comment]
use `;@region`

**Comment by xmaxrayx** [comment]
> use `;@region`

oh this works 

many thx <3
