### ISSUE TITLE
Formatter "indents" comments with tabs

### ISSUE THREAD

**Issue by Axlefublr** [thqby/vscode-autohotkey2-lsp#179]
![image](https://user-images.githubusercontent.com/101342105/188280559-0c139110-f98a-4334-9b29-bbc27f5a4ee0.png)

But I'd much rather them be spaces instead. Please add a setting for the formatting to choose this. 

Otherwise, it could be decided by the `"indent_string"` option

**Comment by G33kDude** [comment]
Can this setting be configured? I kind of liked the tabs, as they worked uniquely well with [Elastic Tabstops](https://marketplace.visualstudio.com/items?itemName=isral.elastic-tabstops-mono).

**Comment by thqby** [comment]
set `AutoHotkey2.FormatOptions.white_space_before_inline_comment`

**Comment by Axlefublr** [comment]
Thanks for implementing this thqby!
