### ISSUE TITLE
Incorrect folding points with if statements

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#187]
Type: <b>Bug</b>

while trying to fix the folding points from the previous bug report
many folding points are now broken:

![image](https://user-images.githubusercontent.com/328761/190281481-322f4cf2-8418-4bf2-aaa6-aa21af289292.png)

Here is some testing code:

```
F1::
{
	Log.Clear()
	try
	{
		info := Genie.ProcessEmail()
		if !IsObject(info)
		{
			Log.Add(unset, STATUS_FAIL, "The info returned by the email is invalid")

			return MsgBox("The email was imported but the information found is invalid"
				, "Error"
				, "Iconx")
		}
		Genie.ImportPatient(info.fName)
		Genie.FindPatient(info.id)
		Genie.CreateConsult(info.id, info.data)
		Genie.FillDemographics(info.id)
	}
	catch Error as e
	{
		Log.Add(unset, STATUS_FAIL, e.Message)
		return MsgBox(e.Message, "Error", "Iconx")
	}
}

f2::
{
	outlook := ComObject("Outlook.Application")

	; convert html to genie import file
	; import the file
	Log.Add(unset, STATUS_INFO, "Getting the selected email")
	if !oInspector := outlook.ActiveInspector
		oExplorer := outlook.ActiveExplorer

	if !item := oInspector ? oInspector.currentItem : oExplorer.Selection.Item(1)
		throw Error("Couldnt get the current email", A_ThisFunc)
	Log.Add(unset, STATUS_PASS, "Email loaded correctly")

	Log.Add(unset, STATUS_INFO, "Getting the correct inbox")
	main := oInspector ? oInspector : oExplorer

	for store in outlook.session.stores
	{
		inbox := store.GetDefaultFolder(6)
		for folder in inbox.folders
		{
			OutputDebug folder.name
			if folder.name != "AHK Imported Patient Registration Forms"
				continue

			importFolder := folder
			break 2
		}
	}

	if !IsSet(importFolder)
		throw Error("Could not retrieve the import folder")

	MsgBox importFolder.name " is in " inbox.name
}
```
That code breaks on a new file

---

Extension version: 1.6.2
VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (15.36GB free)|
|Process Argv|--crash-reporter-id bdc99747-9c48-41d5-87e2-d320011e638b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
fc301958:30567733

```

</details>

**Comment by thqby** [comment]
it's same as [#186].

**Comment by RaptorX** [comment]
Is that already pushed? Or is the update coming soon? Because the screenshot I sent is from the latest version (updated 1 day ago)
