### ISSUE TITLE
格式化-花括号换行

### ISSUE THREAD

**Issue by Frozen1084** [thqby/vscode-autohotkey2-lsp#188]
不知道从哪个版本开始的，最近才发现格式化时花括号被强制不换行了。
以前是这样的
```
test(a){
	if a
	{
		MsgBox 1
	} else
	{
		MsgBox 2
	}
}
```

现在是这样
```
test(a) {
	if a {
		MsgBox 1
	} else
	{
		MsgBox 2
	}
}
```

请问怎样设置才能只让函数名后的花括号不换行，其他位置的强制换行呢？就像示例1。

**Comment by thqby** [comment]
one_true_brace选项，换行，不换行，保留原样

**Comment by Frozen1084** [comment]
谢谢。请问"保留原样"，应该怎样设置？

测试下来，true是不换行，false是换行(所有位置的花括号都被换行了)

请问怎样设置才能实现"函数名后的花括号不换行，其他位置的强制换行"？

**Comment by thqby** [comment]
已修复'保留原样'部分地方未生效
