### ISSUE TITLE
Possible issue with JSDoc @example syntax highlighting in v1.6.3

### ISSUE THREAD

**Issue by OpalMonkey** [thqby/vscode-autohotkey2-lsp#190]
I'm guessing this isn't how the `@example` tag should be coloured. All the other tags I have tried are okay, and it seems fine when I revert to v1.6.2.

v1.6.3: 
![2022-09-18_19-33-51](https://user-images.githubusercontent.com/1016179/190937597-ccda7956-204e-46f6-9e01-b1ed1ba4c6ef.png)
v1.6.2:
![2022-09-18_19-41-16](https://user-images.githubusercontent.com/1016179/190937941-8599142d-3df8-49c9-aedb-528c0f495c4a.png)

```
/**
 * Test function.
 * @example <caption>Test example:</caption> Test('something')
 * @param {any} p1 - Test param.
**/
Test(p1) {
    
}
```

**Comment by thqby** [comment]
The current version, after `@overload` and `@example`, is marked as ahk code

**Comment by OpalMonkey** [comment]
Ah, okay. That's so that it shows normal highlighting and Intellisense?

Not a big deal either way, but would it be possible to have the contents of `<caption>` be highlighted as a comment?

**Comment by thqby** [comment]
```
/**
 * Test function.
 * @param p1 Test param.
 * @example
 * ;Test example:
 *  Test('something')
 **/
Test(p1) {
    
}
```
Can we do that?

**Comment by OpalMonkey** [comment]
Yes, that'll be fine as a workaround. I was testing it out a few minutes ago, and this works as well, so I'm alright with that:
```
/**
 * Test function.
 * @param {any} p1 - Test param.
 * @example ;<caption>Test example:</caption>
 *          Test('something')
**/
Test(p1) {
    
}
```
Thanks for clarifying.
