### ISSUE TITLE
Option to change brace/indenting style

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#194]
Type: <b>Feature Request</b>

When autocompleting with Tab the lexer chooses a format for the brace styles.
![image](https://user-images.githubusercontent.com/328761/191128116-c9d326f0-6e65-46fa-b84b-7aab3cecc9e9.png)

It would be a nice feature to have a check box/list box that allows you to choose from at least the other well known style, [https://www.wikiwand.com/en/Indentation_style#Allman_style](the Allman Style), so that the autocomplete set the braces like this:
![image](https://user-images.githubusercontent.com/328761/191128179-afc03eb3-5a35-480c-b1dd-632d3f2f6947.png)

--- 
Extension version: 1.6.3
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by RaptorX** [comment]
Im dumb, I just noticed the formatting options in the settings

**Comment by RaptorX** [comment]
I checked the formatting options in settings but I dont think they are affecting the auto-complete functionality with the chosen formatting.

![image](https://user-images.githubusercontent.com/328761/191129988-dcee5cbe-00d3-4910-8d78-895281c25b6d.png)

I still get one true brace when hitting tab to autocomplete things like `__new` or `class`

**Comment by thqby** [comment]
Automatic completion will not trigger formatting, and typeFormat will be triggered by line feed after formatOnType is enabled. (Enter between brace)

**Comment by RaptorX** [comment]
so, when you type `clas{tab}`  who is creating the auto-complete? is that a snippet?

**Comment by thqby** [comment]
no, generated by reading snippet files at extension startup.
