### ISSUE TITLE
IntelliSense for classes with overwritten base

### ISSUE THREAD

**Issue by Descolada** [thqby/vscode-autohotkey2-lsp#197]
Hello,
First of all, thank you so much for the awesome extension! It has made AHK so much easier and fun to use.

I do have a question for you: is there any way of making IntelliSense work with classes where the base has been overwritten with another class? Eg:
```
Test.MyMethod()

class Test {
    static __New() {
        this.base := Test.SubTest
    }
    class SubTest {
        static MyMethod() => MsgBox("Test!")
    }
}
```
Here `MyMethod()` will have a warning `Class 'Test' maybe have not member 'MyMethod'` and I haven't found a way to tell VSCode/IntelliSense to also look in SubTest for methods. I tried @extends and @implements which don't seem to work. Any ideas?

**Comment by thqby** [comment]
Some complications don't apply.

```
class Test extends Test.SubTest {
    class SubTest {
        static MyMethod() => MsgBox("Test!")
    }
}
```

**Comment by Descolada** [comment]
@thqby, I tried the following:
```
Test.MyMethod2()

class Test extends Test.SubTest2 {
    class SubTest1 {
        static MyMethod1() => MsgBox("Test 1!")
    }
    class SubTest2 extends Test.SubTest1 {
        static MyMethod2() => MsgBox("Test 2!")
    }
}
```
but it starts giving a lot of errors:
```Request textDocument/semanticTokens/full/delta failed.
  Message: Request textDocument/semanticTokens/full/delta failed with message: Maximum call stack size exceeded
  Code: -32603```

Any way to fix this?
