### ISSUE TITLE
[Help] Generating the 'server.js' script contained in the VSIX VS Code Extension

### ISSUE THREAD

**Issue by pidgeon777** [thqby/vscode-autohotkey2-lsp#2]
Hello, I cloned your repository locally.

However, I noticed that the `server.js` file implementing the LSP is available only into your VS Code extension file (thqby.vscode-autohotkey2-lsp-0.6.8.vsix).

How could I generate the `server.js` file starting from this repository? Or does another way exist?

Thank you

**Comment by thqby** [comment]
1. install nodejs
2. cd vscode-autohotkey2-lsp
3. npm install
4. npm run vscode:prepublish
