### ISSUE TITLE
Wrong syntax highlighting within strings

### ISSUE THREAD

**Issue by hajljnopera** [thqby/vscode-autohotkey2-lsp#201]
![image](https://user-images.githubusercontent.com/39905585/194467021-1b7b9dd7-0d88-4dbd-b826-eb9793940eb9.png)

```ahk
uri_url_encode(url) {
    return uri_encode(url, "[0-9a-zA-Z:/;?@,&=+$#.-]")
}
```

**Comment by thqby** [comment]
![image](https://user-images.githubusercontent.com/28240311/194478271-7e4669c4-b60f-4a8e-99f4-c3fc05359252.png)
No error found.

**Comment by hajljnopera** [comment]
Seems like this extension caused the error

https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments
