### ISSUE TITLE
Detect misplaced or dangling control flow clauses

### ISSUE THREAD

**Issue by lvalkov** [thqby/vscode-autohotkey2-lsp#21]
The following piece of code produces a compile time error, however, no diagnostic is provided.
```ahk
if (true)
	foo := ''
	foo := '' ; An unintentional refactoring mistake.
else
	bar := ''
```
The emitted error is:
```
Error:  Unexpected "Else"

	Line#
	001: If (true)
	002: foo := ''
	003: foo := ''
--->	004: Else

The program will exit.
```
This is an easy error to commit by beginner and experienced (for instance, during refactoring) programmers alike or by those accustomed to indentation scope based languages such as Python. Therefore, I am of the opinion that it is worth having a diagnostic for. 

`else`
----
Associates with the [**nearest applicable unclaimed** single-line statement or block above it](https://lexikos.github.io/v2/docs/commands/Else.htm#Remarks), belonging to an `if`, `catch`, `for`, any kind of `loop` or `while`.

`until`
---
After any kind of `loop` or `for`.

`catch`
---
After `try` or `catch` (provided it is associated with a `try` preceding it).

`finally`
---
After `try`, `catch` or `else` (provided it is associated with a `try` preceding it).

Tested with [`AutoHotkey_L v2.0-a137-f6f65742`](https://github.com/Lexikos/AutoHotkey_L/releases/tag/v2.0-a137).

**Comment by thqby** [comment]
This requires a more detailed grammatical analysis.

**Comment by thqby** [comment]
The version that Detect dangling control flow clauses has been resleased.
