### ISSUE TITLE
To many spaces with comments and braces

### ISSUE THREAD

**Issue by adkurz** [thqby/vscode-autohotkey2-lsp#211]
Hello,

If i write something like:
} ; My comment
the formatters output is like:
}  ; My comment
Is there a possibility to fix this? Also that the number of spaces isn't affected?
Greetings
Adrian Kurz

**Comment by thqby** [comment]
Line comments are prefixed with white space and indented with the same white space, set by the `indent_string` option.

**Comment by thqby** [comment]
set option `white_space_before_inline_comment`
