### ISSUE TITLE
Diagnostics keep showing after switching lexer to v1

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#216]
Type: <b>Bug</b>

* Set v2 as default for .ahk files
* Open a v1 project
* Switch to v1 lexer

### Result

v2 engine continues to parse all other files in the workspace and continues showing diagnostics/linting errors.

![image](https://user-images.githubusercontent.com/328761/201526455-88d3669a-48da-4403-b541-b47864dde295.png)

### Expected
After switching to a v1 lexer the diagnostics/linting engine should be reset immediately and clean all coloring for all files in the workspace.

### Notes:

While writing this bug i noticed that after a minute or so the engine cleaned the diagnostics data. I think this should be done as soon as the language is changed. Not sure how viable that is though.

---

Extension version: 1.7.3
VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (18.47GB free)|
|Process Argv|--crash-reporter-id bdc99747-9c48-41d5-87e2-d320011e638b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce2:30605431
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by Lexikos** [comment]
I don't get any Problems from *this extension* for files that aren't open. I only get warnings if the file is open and AutoHotkey2 is selected as the language, and that's how I like it. I don't recall seeing or changing any setting relating to this, but I can see your setup doesn't behave the same as mine.

The v1 NekoHelp extension unfortunately does scan all files in the workspace, including files that are open with AutoHotkey2 selected.

**Comment by Lexikos** [comment]
> I don't get any Problems from *this extension* for files that aren't open.

I am seeing this unwanted behaviour in newly opened VS Code windows. I guess it's due to a recent update?

**Comment by thqby** [comment]
Maybe file reference calculation error, or the unclosed script that is regarded as v2 references the v1 script.

**Comment by RaptorX** [comment]
Is there a hook when switching extensions to know when your extension had been switched to another?

because if that is the case, you can use that event to just clear the diagnostics.

**Comment by thqby** [comment]
Switching to another language will trigger onDidClose, and closing the editor tab will also trigger this. There is no information to distinguish between the two cases. In most cases, you need to cache closed documents in the background to provide features such as completion.

**Comment by thqby** [comment]
Switching to another language will trigger onDidClose, and closing the editor tab will also trigger this. There is no information to distinguish between the two cases. In most cases, you need to cache closed documents in the background to provide features such as completion.

**Comment by thqby** [comment]
In addition, most v1 scripts can now be recognized, which can reduce such false positives.

**Comment by RaptorX** [comment]
> In addition, most v1 scripts can be recognized now. If you set it to automatic switching, you can reduce such false positives.

I will give it a try now lets see what we get.
