### ISSUE TITLE
issue when parsing a_linefile\..\ paths

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#217]
Type: <b>Bug</b>

* add #include with `%a_linefile%\..\path`

### Result
`The Autohotkey2 Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`

```
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOTDIR: not a directory, scandir 'D:\Cloud\RaptorX\OneDrive\Documents\AutoHotkey\lib\cppJSON\cppJSON.ahk\'
    at readdirSync (node:fs:1392:3)
    at e.readdirSync (node:electron/js2c/asar_bundle:5:10830)
    at h (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.3\server\dist\server.js:1:149316)
    at p (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.3\server\dist\server.js:1:149107)
    at e (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.3\server\dist\server.js:1:131592)
    at e (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.3\server\dist\server.js:1:131658)
    at c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.3\server\dist\server.js:1:368351
    at o.invoke (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.3\server\dist\server.js:1:236662)
    at r.fire (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.3\server\dist\server.js:1:237423)
    at c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.3\server\dist\server.js:1:322332 {
  errno: -4052,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: 'D:\\Cloud\\RaptorX\\OneDrive\\Documents\\AutoHotkey\\lib\\cppJSON\\cppJSON.ahk\\'
```

### Expected 
language server should recognize the type of path and read the file system accordingly

### Sample Code
```
#Include %A_LineFile%\..\lib\Native.ahk

class JSON {
    static __New() {
        Native.LoadModule(A_LineFile '\..\lib\ahk-json\' (A_PtrSize * 8) 'bit\ahk-json.dll', ['JSON'])
        this.DefineProp('true', {value: 1})
        this.DefineProp('false', {value: 0})
        this.DefineProp('null', {value: ''})
    }
    static parse(str) => 1
    static stringify(obj, space := 0) => 1
}
```

### Notes
When creating libraries that depend on other libraries one MUST use `%A_LineFile%\..\` paths to allow for correct includes in target apps because `.\lib` style of includes refer to the launching scripts and not the library folder paths and then includes fail.

### Known workaround

using this instead seem to work correctly:
```
#Include %A_LineFile%\..\lib\
#Include Native.ahk
```

The problem is that it now switches the default `#include` folder which might not be desired by the target app.

--- 

Extension version: 1.7.3
VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (18.10GB free)|
|Process Argv|--crash-reporter-id bdc99747-9c48-41d5-87e2-d320011e638b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce2:30605431
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by thqby** [comment]
`%A_LineFile%\..\` is the same as `.\` by default

**Comment by RaptorX** [comment]
It is not.

Ill provide an example of where it breaks.

**Comment by RaptorX** [comment]
btw, on a semi-related note, I encountered this issue while playing with another library of yours for JSON and got some errors there, I posted about it [here](https://www.autohotkey.com/boards/viewtopic.php?p=490995#p490995). Can you please take a quick look when you can? There is no github repository for it.

**Comment by RaptorX** [comment]
Actually I was able to reproduce what I meant.

I have a library for Sqlite3 that I have been developing.

The `unit.tests.ahk`  file includes the library with `#Include ..\SQLite3.ahk`

But the library loads a file using `dllBin := ".\bin\" SQLite3.bin` notation on line 22.

In this situation `.\` is NOT the same as `A_LineFile`.
Seems like they are synonyms only when using the `#include` directive.

Maybe @Lexikos might be able to clarify that.

[SQLite.zip](https://github.com/thqby/vscode-autohotkey2-lsp/files/9998098/SQLite.zip)

**Comment by thqby** [comment]
In `#include`, it is relative to the current file, If `#include folder` is not used. fileopen is relative to the working folder by default

**Comment by thqby** [comment]
This change in v2 makes it easy to find reference relationships from arbitrary ahk files.

**Comment by RaptorX** [comment]
Yes. Your later statement is correct. They are only synonyms in an `#include` directive.
Outside of that context they are not.

My mistake was thinking that you meant that they were always synonyms which is not the case.

**Comment by thqby** [comment]
> btw, on a semi-related note, I encountered this issue while playing with another library of yours for JSON and got some errors there, I posted about it [here](https://www.autohotkey.com/boards/viewtopic.php?p=490995#p490995). Can you please take a quick look when you can? There is no github repository for it.

I have tested it and found no errors.
