### ISSUE TITLE
Unwanted linebreak in if else statements

### ISSUE THREAD

**Issue by adkurz** [thqby/vscode-autohotkey2-lsp#219]
Hello,
Sorry for the disruption again.
If i write something like:
if (a = b) {
  do something
} else if (b = c) {
  Do other
}
The formatters output is:
if (a = b) {
  do something
}
else if (b = c) {
  Do other
}
Is there a possibility to avoid this linebreak after the first closing curly brace? So in this example, the formatter shouldn't do anything.
Thank you for the great work so far.
Greetings Adrian Kurz

**Comment by thqby** [comment]
set `one_true_brace` to 1
