### ISSUE TITLE
warnings when defining properties for built-in classes

### ISSUE THREAD

**Issue by lstrfwp** [thqby/vscode-autohotkey2-lsp#220]
I can define custom properties for the built-in classes, but the code below gives me warnings that `Class 'x' maybe have not member 'y'`.

```
Menu.MyProp := 50
MsgBox Menu.MyProp

Gui.MyProp := 34
Msgbox Gui.MyProp

Array.DefineProp("Test", {Value:"Hello"})
MsgBox Array.Test
```

**Comment by thqby** [comment]
Not just built-in classes, but custom classes as well.

This is a simple check and does not involve dynamic analysis. Unless you run each line of code, it's hard to tell if the current statement will throw an error. This is beyond my current ability.

**Comment by Lexikos** [comment]
I think that for this sort of case and others, you should add comment-based directives that give hints for the diagnostics, such as to add a property to a given class, or to suppress a specific diagnostic (or all diagnostics) for a specific thing.

**Comment by thqby** [comment]
In the same file, similar code will not be warned.
