### ISSUE TITLE
Diagnostic for missing `return` (feature request)

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#221]
For detecting problems like the one in [this topic](https://www.autohotkey.com/boards/viewtopic.php?f=82&t=110469), it would be helpful if conditions like this could be reported by the extension:
  - More strict: Function uses `return` but has some code paths where there is no `return`. (I intentionally do this knowing it is the same as `return ""`, but I know I shouldn't; and maybe it won't in a future version.)
  - Less strict: An expression is calling a function which might implicitly return "". In other words, don't treat it as a problem until we know that someone is trying to use the return value (and there might not be one).

A future version of the language might `return unset` by default, and consider it an error to attempt to use the unset return value:
```
f_has_no_return() {
}
x := f_has_no_return()  ; runtime error, just like x := v_has_no_value
y := f_has_no_return() ?? 1  ; y := 1
```
In the meantime, detecting these problems through static analysis could be very helpful.

**Comment by thqby** [comment]
Complex expressions are a little tricky to check.

**Comment by RaptorX** [comment]
> Complex expressions are a little tricky to check. And I don't have a good idea how to check all the return paths of a function.

I thought it was a matter of if you are in a function scope/context check if there is a return statement or not.
if not, then mark it as "returnless" and if there is an expression of `var := function()` somewhere just mark it as a warning.
