### ISSUE TITLE
Server Crash on new version

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#222]
Type: <b>Bug</b>

### Steps to Reproduce
Open a v1 project which had ahk v1 lexer selected

### Result

I am not sure why the crash happens but I get this error log:

![image](https://user-images.githubusercontent.com/328761/204295236-5c1da4a6-49ca-46b7-a452-a400fd64509a.png)

```
Error: EACCES: permission denied, open 'd:\cloud\raptorx\dropbox\guests\the-automator\scripts to work on\newsletter\newsletter manager\src\creative\html\html table generator_1.ahk'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at readFileSync (node:fs:453:35)
    at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at p (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.6\server\dist\server.js:1:153731)
    at t.parseWorkspaceFolders (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.6\server\dist\server.js:1:161312)
    at Timeout._onTimeout (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.7.6\server\dist\server.js:1:372472)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7) {
  errno: -4092,
  syscall: 'open',
  code: 'EACCES',
  path: 'd:\\cloud\\raptorx\\dropbox\\guests\\the-automator\\scripts to work on\\newsletter\\newsletter manager\\src\\creative\\html\\html table generator_1.ahk'
}
```

---

Extension version: 1.7.6
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (20.47GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\Dropbox\\Guests\\the-Automator\\Scripts to Work on\\The Automator Database Scripts\\CustomerList --crash-reporter-id bdc99747-9c48-41d5-87e2-d320011e638b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
pyind779cf:30617257
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by thqby** [comment]
> permission denied, open 'd:\cloud\raptorx\dropbox\guests\the-automator\scripts to work on\newsletter\newsletter manager\src\creative\html\html table generator_1.ahk'

Doesn't this indicate the cause of the error?

**Comment by RaptorX** [comment]
> > permission denied, open 'd:\cloud\raptorx\dropbox\guests\the-automator\scripts to work on\newsletter\newsletter manager\src\creative\html\html table generator_1.ahk'
> 
> Doesn't this indicate the cause of the error?

Not exactly because I do not have the **v2** extension enabled and that file has no file permission issues. When I run the code with the **v1** extension it works just fine.

File Permissions are set correctly:
![image](https://user-images.githubusercontent.com/328761/204311042-b0fcc686-903c-4878-af75-56dd722f0d89.png)

**Comment by thqby** [comment]
I don't know the exact reason. Does the problem still exist after I restart the computer?
Sometimes files are inaccessible because other programs are occupying them.

**Comment by thqby** [comment]
Has this problem been solved?

**Comment by RaptorX** [comment]
Yes This problem is no longer happening in the newest version.
