### ISSUE TITLE
Emacs support?

### ISSUE THREAD

**Issue by gtusr** [thqby/vscode-autohotkey2-lsp#223]
It would be helpful to provide instructions on how to configure this to work with emacs as well.

**Comment by thqby** [comment]
I haven't used emacs, [lsp-mode](https://github.com/emacs-lsp/lsp-mode) is the lsp client of emacs. You can refer to the configuration in other languages.

**Comment by thqby** [comment]
Have you found a way to configure it?

**Comment by gtusr** [comment]
Have not found a way to configure it.  Maybe leave this open in case someone who is more familiar with emacs lsp-mode could provide instructions.

**Comment by thqby** [comment]
The above link provides the configuration method. If it is still not configured, I think it is more effective to seek help in [lsp-mode](https://github.com/emacs-lsp/lsp-mode).
