### ISSUE TITLE
希望插件设置可以支持VSCode自带的${}变量

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#230]
目前在工作区中设置launch文件或ZeroPlusPlus，可以使用${}变量，如${file}、${workspacefolder}。但目前在本插件中尚不支持，如下图：
![image](https://user-images.githubusercontent.com/47076058/206887428-d791af64-e6dc-4b0f-bebf-40952c7c5b7e.png)
请问在工作区中设置你的插件，能否也给你的插件配置添加${}变量的使用支持。这样的话将会给使用工作区写v2代码的人带来便利、尤其是不想在C盘Progarm files/AutoHotkey中添加v2文件夹并把解释器安排到v2工作区的人。至少这样包含工作区文件的文件夹就可以随意移动位置了。

**Comment by PythonYunfei** [comment]
看起来只有luanch中才能用${}变量，那就用着绝对路径也行

**Comment by thqby** [comment]
工作区可以设置相对路径 `.\ahk.exe`

**Comment by PythonYunfei** [comment]
![image](https://user-images.githubusercontent.com/47076058/208242703-0ecf9ff5-931b-4550-8a7b-95c95e842acb.png)

这个好像只能相对当前工作区的文件夹，不能相对工作区。换到该工作区的另一个文件夹中运行脚本，可能就不行了
![image](https://user-images.githubusercontent.com/47076058/208242686-28a5abdc-0343-4ac8-82f6-47c930c56941.png)

**Comment by thqby** [comment]
仅支持第一个文件，多文件夹不同解释器需要管理多个本地库文件夹，比较麻烦，还不如多开几个vscode
