### ISSUE TITLE
Mark a full working directory for AHKv1 instead of file by file

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#232]
Type: <b>Feature Request</b>

* Set v2 extension as default .ahk handler
* Open a project that has many AHK v1 files in it
* Open one of the files (lexer changes to v1)
* Other files are not marked, and then they must be set one by one

![image](https://user-images.githubusercontent.com/328761/208204493-d3a9b5eb-2662-4c92-96e4-5834810304de.png)

### Expected

It would be nice if once a file has been marked for AHK v1, the whole working directory is considered by the extension as not an AHK v2 project, so the extension doesnt mark each file as having issues when marking them on the tree view.

---

Extension version: 1.8.0
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by thqby** [comment]
Since the whole folder is v1, you can set the folder to disable v2 plug-ins. It is also possible to mix two versions of the same folder.

**Comment by RaptorX** [comment]
> Since the whole folder is v1, you can set the folder to disable v2 plug-ins.
I am not aware of how to do this. Can you explain? 

> There may also be two versions of scripts in the same folder.
Like a v1 and v2 script? Huh... Never thought of that.
I usually use git and have a separate branch for a different version, but you are right some people might do that.

**Comment by RaptorX** [comment]
okay perfect, i will try with that for now then, thanks!
