### ISSUE TITLE
希望在try中消除属于“可被catch的"这类错误的警告

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#237]
在`try{}`语句块中进行警告，希望加个判断：如果编辑诊断出的错误的类型正好也是`Catch`后面的类型(或其子类)，则不予以警告；否则编辑器对该错误予以警告。既然某类错误被有意地安排了进行处理，自然不用警告。
  如下图，图中箭头处的错误是`PropertyError`，而`PropertyError`正好是`MemberError`的子类；那么可判定该类错误“可被catch”，是人为有意为之的，编辑器不予警告
![image](https://user-images.githubusercontent.com/47076058/208400929-be5a8af2-4c74-429b-a4a3-4e931aab865e.png)
  如果只有`Try XXX`但后面没有写明catch后的类型，可考虑正常警告。

**Comment by thqby** [comment]
不大改实现不了这个，暂不考虑。

会加入注释开关，关闭这个警告。

**Comment by PythonYunfei** [comment]
那先不去弄注释开关了，毕竟try的使用频率没有原函数__get多
