### ISSUE TITLE
Highlighting of `this` and `super` inside class body

### ISSUE THREAD

**Issue by lvalkov** [thqby/vscode-autohotkey2-lsp#24]
<details>
<summary>Code</summary>

```ahk
class Foo extends Bar
{
	__New()
	{
		if (this.Method())
			this.Method()

		if (super.Method())
			super.Method()

		BooleanArray := [ this.Method(), super.Method() ]
		BooleanMap := Map( 'this', this.Method(), 'super', super.Method() )
		BooleanObject := { this: this.Method(), super: super.Method() }

		NestedFunction()
		{
			if (this.Method())
				this.Method()

			if (super.Method())
				super.Method()

			BooleanArray := [ this.Method(), super.Method() ]
			BooleanMap := Map( 'this', this.Method(), 'super', super.Method() )
			BooleanObject := { this: this.Method(), super: super.Method() }
		}

		NestedFunctionWithShadowedParameters(this, super)
		{
			if (this.Method())
				this.Method()

			if (super.Method())
				super.Method()

			BooleanArray := [ this.Method(), super.Method() ]
			BooleanMap := Map( 'this', this.Method(), 'super', super.Method() )
			BooleanObject := { this: this.Method(), super: super.Method() }
		}
	}

	Method() => true
}

class Bar
{
	Method() => true
}
```

</details>

Within class bodies, incorrect scopes (`variable.other.*`) are being applied to the hidden parameter `this` and the pseudo-keyword `super` whenever they are **parenthesized** and in a few other instances.

![ThisSuper](https://user-images.githubusercontent.com/25468197/124370131-27fad880-dc74-11eb-9037-b628155c5c0c.gif)

The same issue can be observed in `Array` declarations. `Map` construction is also affected by virtue of being nothing more than a *parenthesized* function call. Suffice to say, *any* function calls, for that matter, suffer the same fate. `Object` declarations exhibit a different kind of issue. While the correct scopes are being applied to the object's property *values*, the **same scopes** are also **incorrectly** being applied to the object's property **names**.

Another issue I've come across concerns parametrized functions, which shadow `this` and `super`. Take the following nested function as an example:

![image](https://user-images.githubusercontent.com/25468197/124370339-ce47dd80-dc76-11eb-8254-a8d1b2bc0dcb.png)

In this case neither `this` nor `super` should be highlighted as referring to the deriving class itself or the base class (unless those exact references were passed in a call to the function, however, deducing that accurately might prove to be too challenging a task for static analysis), and yet they are.

Tested with [`AutoHotkey_L v2.0-a138-7538f26`](https://github.com/Lexikos/AutoHotkey_L/releases/tag/v2.0-a138).

**Comment by thqby** [comment]
Syntax Highlight is powered by TextMate grammars, it is not possible to highlight all words accurately.

**Comment by lvalkov** [comment]
As far as the nested function example is concerned, I understand it might not be feasible implement a very sophisticated detection mechanism but wouldn't it be possible at least for the other cases? Since the meta-scope `meta.block.class.body` has already been applied, can the TM grammar not be edited such that a `this`/`super` context is expected?

Unfortunately, I'm not intimately familiar with VS Code's highlighting engine. I'm basing my proposal on the assumption that it is stack-based. 

I reckon simply treating *any* `this`/`super` identifiers as `this`/`super` would provide superior highlighting in the majority of the cases (even one *couldn't* restrict to just class bodies). If that were so, only object property names and parametrized shadowing functions would be highlighted erroneously (i.e. when they shouldn't be), which shouldn't pose that big of a problem due to how unlikely it is to have to write such code.

**Comment by thqby** [comment]
Adding a few more similar code blocks should solve this problem.
