### ISSUE TITLE
Display intellisense when completing command without parenthesis

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#244]
Type: <b>Feature Request</b>

### Steps to reproduce

* Type a command
* You will get an autocomplete suggestion
![image](https://user-images.githubusercontent.com/328761/209742092-bd225c84-c8cb-4eb1-888a-cdb686fd4c0c.png)

* After hitting tab to select the suggestion intellisense is not displayed
![image](https://user-images.githubusercontent.com/328761/209742115-4d77e5bb-6caa-464c-8f05-41616fc7d51f.png)

* When adding the parenthesis the infotip is shown with intellisense
![image](https://user-images.githubusercontent.com/328761/209742126-2fd4b868-a157-4522-b86c-3348a9c3f9fa.png)

### Feature request
If possible, it would be good to have intellisense fire up as soon as the command is typed/selected because sometimes one might not remember exactly what the first parameter is and then we are forced to open the parenthesis even if I will have to deleted them later (I only use parenthesis when the command will be used as a function, that returns a value for example)

---
Extension version: 1.8.2
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by thqby** [comment]
ctrl+shift+space can trigger this

**Comment by RaptorX** [comment]
> ctrl+shift+space can trigger this

That is not working for me.

Ctrl + Space brings the autocomplete window for me, but not the intellisense tip.

This other hotkey though does what I'm looking for but I would have to change the **when expression:**

![image](https://user-images.githubusercontent.com/328761/210384325-d02d1e60-3687-400d-9ba0-cdb2785309d5.png)

My request would be for the hover window to show as soon as the command is selected from autocomplete (via tab or click) or when pressing space so that it behaves similar to when you use the parenthesis i.e. the tip is auto displayed when opening parenthesis.

**Comment by thqby** [comment]
Pressing the trigger key under any condition will trigger this, so I don't want to use the `space` as the trigger key to reduce invalid triggers.

Type `hotkey<space>`, and then press this hotkey `ctrl+shift+space`.

**Comment by RaptorX** [comment]
> Type `hotkey<space>`, and then press this hotkey `ctrl+shift+space`.

This actually works.

`hotkey<ctrl+shift+space>` doesn't.
That might do it for now. Thanks!

**Comment by lstrfwp** [comment]
> Type `hotkey<space>`, and then press this hotkey `ctrl+shift+space`.

In v`2.0.0`, parameter hints don't show when you press this hotkey in a function call without parentheses. Selecting "Trigger Parameter Hints" from command palette also doesn't work.
