### ISSUE TITLE
Incorrect parameter suggestions for classes

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#245]
In the new version we are getting the `this` keyword presented as a parameter in classes which is incorrect in the sense that the first parameter you can change is not the THIS itself but the defined parameters.

![image](https://user-images.githubusercontent.com/328761/209743027-95a042be-3b05-48d5-9b7a-1011bdd3632c.png)

This class only accepts 2 parameters `dbFile` and `overwrite`. While is true that the `@this` parameter exists, it shouldn't be suggested as the first parameter to fill out because you get this:

![image](https://user-images.githubusercontent.com/328761/209743150-916fe3a4-bffc-4fc0-9116-4fa72f9e65b6.png)

I already set the `dbFile` parameter but intellisense is telling me that i set the `this` parameter instead which is incorrect.

### Possible solution
I like that the `this` parameter is shown, but it shouldnt be preselected as the first parameter. Is there a way to set the "second" parameter as highlighted when the intellisense tip is shown?

If that's possible then I would rather have that. If not, maybe having the `this` keyword as the last parameter or in the worse case, completely removed again :(

**Comment by thqby** [comment]
This bug has been fixed, but I seem to forget to release it.

**Comment by RaptorX** [comment]
awesome!
Thanks!
