### ISSUE TITLE
Switch language fail on certain files

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#246]
Type: <b>Bug</b>

I have a file named `SQLSift.ahk` with the following contents:
<details>
<summary>AHK File</summary>

```
/** v0.1.0 | By RaptorX | [AHK Forum Post]()
 * Returns a SQLQuery expression to use with the LIKE statement
 * ---
 *
 * ### Params:
 * - `needle` - text to search for
 * - `SearchType` - how to search for needle in the database
 *     - `in` - find anywhere inside the haystack
 *     - `lt` - find only at the beginning of the haystack (left)
 *     - `rt` - find only at the end of the haystack (right)
 *     - `oc` - find ordered characters in the haystack even if not consecutive
 *     - `ow` - find ordered words in the haystack even if not consecutive
 *
 * ### Returns:
 * - `sql` - String to use with the LIKE statement
 *
 * ### Examples:

 msgbox % SQLSift("hello world", "in") ; %hello world%
 msgbox % SQLSift("hello world", "lt") ; hello world%
 msgbox % SQLSift("hello world", "rt") ; %hello world
 msgbox % SQLSift("hello world", "oc") ; %h%e%l%l%o%w%o%r%l%d%
 msgbox % SQLSift("hello world", "ow") ; %hello%world%

 */
SQLSift(needle, SearchType := "in")
{
	switch SearchType {
		case "in":
			sql .= "%" needle "%"
		case "lt":
			sql .= needle "%"
		case "rt":
			sql .= "%" needle
		case "oc":
			for each,char in StrSplit(needle)
			{
				if char && !(char ~= "\s|\t|\n")
					sql .= "%" char
			}
			sql .= "%"
		case "ow":
			for each,word in StrSplit(needle, A_Space)
				sql .= "%" word 
			sql .= "%"
	}

	return  """" sql """"
}
```

</details>

The extension correctly notes that this might be a V1 Script but when selecting to switch to v1 it stays as a v2 script.

Automatically switching also fails.

---

Extension version: 1.8.2
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.94GB free)|
|Process Argv|--crash-reporter-id bdc99747-9c48-41d5-87e2-d320011e638b|
|Screen Reader|no|
|VM|0%|
</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by RaptorX** [comment]
Actually Im having issues with the whole switching functionality:

![image](https://user-images.githubusercontent.com/328761/209983096-b77be333-07d3-474d-8a97-1d77891c6eee.png)


with these errors:

```
[Info  - 8:56:35 pm] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/autocompleter.ahk This script requires AutoHotkey v1, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Info  - 8:56:35 pm] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/lib/loaddata.ahk This might be a v1 script, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Info  - 8:56:35 pm] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/lib/sift.ahk This script requires AutoHotkey v1, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Info  - 9:00:04 pm] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/lib/sift.ahk This script requires AutoHotkey v1, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Info  - 9:05:56 pm] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/lib/sift.ahk This script requires AutoHotkey v1, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Info  - 9:16:05 pm] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/lib/sift.ahk This script requires AutoHotkey v1, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Info  - 9:19:13 pm] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/lib/sift.ahk This script requires AutoHotkey v1, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Info  - 9:22:50 pm] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/lib/sift.ahk This script requires AutoHotkey v1, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Info  - 9:26:27 pm] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/lib/sift.ahk This script requires AutoHotkey v1, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Info  - 9:30:26 pm] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/lib/sift.ahk This script requires AutoHotkey v1, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Info  - 9:28:42 am] file:///d%3a/cloud/raptorx/dropbox/sergeetienne/autocomplete%20filter/lib/sift.ahk This script requires AutoHotkey v1, and the lexer stops parsing. Try switching to AutoHotkey v1.
```
It is happening with many v1 scripts

**Comment by RaptorX** [comment]
I am noticing that when I open a v1 script and select the v1 lexer and close it, later on when I open the file again, I get the above errors.

So probably the extension is trying to switch to the v1 lexer but it is already selected and the action fails.

**Comment by thqby** [comment]
This issue has not been reproduced.

**Comment by RaptorX** [comment]
> This issue has not been reproduced.

I re installed windows and with that i has to reinstall vscode. I'm still getting that error. I'll try to record it and show the logs.

**Comment by RaptorX** [comment]
Im still getting the erros:

log:
<details>

```
[Info  - 1:11:45 PM] file:///d%3A/Cloud/RaptorX/Dropbox/Guests/the-Automator/Client%20Work/Panagiotis-GreekDogs/test/Paypal%20Scrape%20test.ahk This might be a v1 script, and the lexer stops parsing. Try switching to AutoHotkey v1.
[Error - 1:11:46 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read properties of undefined (reading 'diagnostics')
  Code: -32603 
```

<details>

The script is a v1 file. I had already selected the v1 extension. Closed the file and later on opened it again.

**Comment by thqby** [comment]
At present, `sift.ahk` is not recognized as v1.
`Request textDocument/codeAction failed`, this will be fixed in the next release.

**Comment by RaptorX** [comment]
Im still having the same issue.
When the file has been previously opened with the v1 extension it saves that.

When I close VSCode and reopen it, your extension tries to parse it and throws errors even though your extension is not selected.

Is there a way to tell if I have manually selected an extension for a given file? because if so, your extension should not try to parse files that I have manually said are v1 scripts or have the requires directive. At least it shouldnt try over and over again :P

**Comment by thqby** [comment]
What error is thrown?

**Comment by RaptorX** [comment]
here you can watch a quick video on it... https://www.youtube.com/watch?v=TdlEHKfXnu0
i just realized it is when opening a working directory some files cant be detected as v1 correctly by the 'switch to v1' function of your extension, so some files are correctly switched but others arent.

**Comment by thqby** [comment]
The language mode is specified by vscode every time a file is opened, the extension switches to v1 based on the recognition result, and does not cache those files that need to be switched.

**Comment by RaptorX** [comment]
> The language mode is specified by vscode every time a file is opened, the extension switches to v1 based on the recognition result, and does not cache those files that need to be switched.

yes, that seems to be the case, but the switching to v1 is failing on some files, ill test if having the file on its own working directory has the same issue.

**Comment by thqby** [comment]
The recognition switch is for a single file and is not considered a project. When no feature is found, it will not be switched.

**Comment by RaptorX** [comment]
> The recognition switch is for a single file and is not considered a project. When no feature is found, it will not be switched.
> 
> No v1 feature found in the above code.

Line 3 is `MsgBox %list%`
That's a pure v1 feature.

Also the linter does point to a few problems with the file, but it seems they are not enough to trigger the v1 switch.

**Comment by thqby** [comment]
This is also valid in v2.
