### ISSUE TITLE
函数括号补全的一点进一步增强建议

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#248]
在Vscode中有一点非常方便，选中文本输入引号：会自动生成引号对，并会自动在引号对之间自动出现选中的文本，而不是将选中文本直接删掉。括号也是如此。希望函数的括号补全也能同理（只不过 仅当选中文本的行数为1时才生效）：选中<=1行的文本，如果此时不按backspace/delete键删除 而是直接输入英文；那么选中文本会被删除，但是一旦通过“此次”的插件智能提示补全了括号，则会自动在括号中出现之前选中的文本且保持选中状态(完全无参的函数除外)。如此副作用很低但能方便很多。函数括号补全勾选后起作用。

**Comment by thqby** [comment]
输入时不会记录替换的原始文本，无法通过简单高效的方法实现这个
