### ISSUE TITLE
A_ScriptDir should be where current script locates, not VSCode's working directory

### ISSUE THREAD

**Issue by TetraTheta** [thqby/vscode-autohotkey2-lsp#249]
I constructed my project like this:
```plaintext
repositories.
│           
├─AutoHotKeyProject
│  │     
│  ├─Lib
│  │      ini.ahk
│  │      
│  └─temp
│          test.ahk
│          
└─<Other projects>

```
And in `test.ahk`, I tried to use `#include` like this:
```autohotkey
#requires AutoHotkey v2.0
#include "%A_ScriptDir%\..\Lib\ini.ahk"
```
Since this is referring `ini.ahk` file inside of `Lib` directory, it should not be underlined with red line. But this VSCode Extension underlines this line saying `'repositories\lib\ini.ahk' not exist`.  
It seems this extension is thinking `A_ScriptDir` is VSCode's opened directory, not where script file's location. This is definitely wrong.  

Yes, AHK v2 can load `ini.ahk` without error. It is this extension that thinks that line is wrong.

---

Current workaround is not using `A_ScriptDir` and include like this:
```autohotkey
#include "..\Lib\ini.ahk"
```

**Comment by thqby** [comment]
For non-specific folder structure, scriptdir cannot be inferred.

In the above cases, it is better to use relative paths, or set workingdirs to specify scriptdir.
