### ISSUE TITLE
Images won't load on the Mandarin version of the Overview page on VS Code Browser Marketplace

### ISSUE THREAD

**Issue by zachpoblete** [thqby/vscode-autohotkey2-lsp#250]
### https://marketplace.visualstudio.com/items?itemName=thqby.vscode-autohotkey2-lsp
![image](https://user-images.githubusercontent.com/92368853/212296562-5bd946b1-6eab-4998-9be9-8a58e401c669.png)

**Comment by thqby** [comment]
Maybe gitee has anti-reptile measures.
In addition, pictures from github can't be displayed here sometimes.
I don't know which drawing bed is easier to use.

**Comment by zachpoblete** [comment]
Excuse me, I'm not sure I understand the relation between Gitee and anti-crawler measures in regard to this issue as it is happening on the Visual Studio Marketplace and not Gitee. To me, this issue seems related to #131.

**Comment by thqby** [comment]
I used web images from github and gitee to avoid temporarily losing access to a repository. In the Visual Studio Marketplace, images from gitee can't be displayed, but they can be displayed locally or on github.
