### ISSUE TITLE
[Suggestion] Extra spacing option for hotkeys with OTB

### ISSUE THREAD

**Issue by ChristianLW** [thqby/vscode-autohotkey2-lsp#252]
If I write a hotkey like below
```ahk
Esc::{
    ExitApp()
}
```
Then the extension will format it to
```ahk
Esc:: {
    ExitApp()
}
```
And I personally hate the uneven spacing, so an option to disable the extra space before `{` would be very nice to have.

I'm not sure how difficult it is to implement, as I gave up quite soon after looking into the code to see if I could quickly make a PR instead. If anyone is up for doing this, I would be much delighted.

**Comment by thqby** [comment]
set formatoption.space_in_other = false

Other spaces will also be removed.

**Comment by ChristianLW** [comment]
I know about `formatoption.space_in_other`, but I'm specifically referring to this space, and not spaces around operators etc.

**Comment by ChristianLW** [comment]
Thanks a lot!
