### ISSUE TITLE
[1.8.4] Conditional IntelliSense failure with #Include

### ISSUE THREAD

**Issue by OpalMonkey** [thqby/vscode-autohotkey2-lsp#254]
IncludeTest.ahk
```
#Requires AutoHotkey v2.0
/**
 * This is a test function.
 * @param {any} p1 - A test parameter.
 * @return {string} Returns a blank string.
**/
TestFunc(p1) {
  
}
```
Main file:
```
#Requires AutoHotkey v2.0
#Include IncludeTest.ahk
class TestClass {
  __New(p1) {
    TestFunc()
  }
}
; TestFunc()
```

If the only calls to `TestFunc` are within a method or function, the IntelliSense doesn't show up. If the call to `TestFunc` at the bottom —outside of a block— is uncommented, both locations work correctly. If the definition for `TestFunc` is in the same file everything works fine.

When I roll back to v1.8.3, this bug doesn't seem to be present.

**Comment by thqby** [comment]
The issue did not reproduce.

**Comment by OpalMonkey** [comment]
Hmm, interesting. When I have a chance, I'll test it more carefully to see if it is a conflict with another extension. So far I was able to reproduce it reliably in my setup with the given code while swapping between 1.8.3 and 1.8.4 multiple times.

**Comment by OpalMonkey** [comment]
This was bugging me, so I decided to test it now. All other extensions are disabled, using a default theme, and running 1.8.4.

Bug is presenting:
![2023-01-16 1-01](https://user-images.githubusercontent.com/1016179/212719296-8cb62ae0-aaac-4168-9ee9-af715e7ffb1d.jpg)
With a call to `TestFunc` not nested in another block, it no longer presents:
![2023-01-16 1-02](https://user-images.githubusercontent.com/1016179/212719301-78c0a49e-ca19-48e9-9a77-b0862736d0c8.jpg)
Include file where `TestFunc` is defined.
![2023-01-16 1-03](https://user-images.githubusercontent.com/1016179/212719303-eef5eef7-7496-4e6d-98f2-90c90f723837.jpg)

I don't know if there is an easy way to temporarily reset all VS Code settings to default or run a clean instance to test if it's a setting, but short of that, I'm not sure how else it could be specific to my setup.

If anyone has any suggestions on how to test it more effectively, I'd be interested to try and find the cause.

**Comment by thqby** [comment]
you mean hover? This requires moving the mouse over the function name.
![image](https://user-images.githubusercontent.com/28240311/212726772-ccd16a91-98f4-4dfc-aa82-0dd71b3de5dc.png)

**Comment by thqby** [comment]
I see what you mean.
