### ISSUE TITLE
[1.8.4] Misdiagnose when returning a reference

### ISSUE THREAD

**Issue by Tebayaki** [thqby/vscode-autohotkey2-lsp#256]
```AutoHotkey
fn() {
    static var := 0
    return &var    ; Error Message: The following reserved word 'return' must not be used as a variable name
}
```
But it's not wrong behavior.

**Comment by Tomshiii** [comment]
you should have just `return var`
if you want to fill a varref it needs to be something closer to this; (as an example as shown [here](https://www.autohotkey.com/docs/v2/Functions.htm#return)
```ahk
fn(&var) {
    static variable := 0
    var := variable
}
```
