### ISSUE TITLE
[1.8.4]无法跳转到通过#Include包含的脚本内的定义

### ISSUE THREAD

**Issue by rebornsick** [thqby/vscode-autohotkey2-lsp#257]
1.8.3

![Snipaste_2023-01-19_01-36-44](https://user-images.githubusercontent.com/28842872/213255454-0565810d-0c80-4a6a-8592-7e6d6a6cc747.png)

1.8.4

![Snipaste_2023-01-19_01-37-32](https://user-images.githubusercontent.com/28842872/213255482-ce348792-93d2-4930-b67c-e36c5c2edb7c.png)

无法跳转到通过#Include包含的函数，按住ctrl表现得像是未定义函数，但是语法高亮都是正常的。

**Comment by thqby** [comment]
信息不足，没复现出这个问题

**Comment by thqby** [comment]
同 #254
