### ISSUE TITLE
Invalid file encoding

### ISSUE THREAD

**Issue by One1Tick** [thqby/vscode-autohotkey2-lsp#259]
Hi and thanks a lot for this very usefull extansion. I have a small issue that I am not able to solve... It should be a config issue but I don't no where it is coming from. I got a lot of the following message (these scripts are v1 script maybe it is part of the problem).
Thanks for your help.

![2023_01_21@5-36PM](https://user-images.githubusercontent.com/35428340/213877040-9c883054-889d-401c-a7c7-ff063ab93cac.PNG)

**Comment by RaptorX** [comment]
What file encoding do you use?

Open one of the files and On the statusbar in vscode (bottom right) you can check what the current encoding is.

**Comment by One1Tick** [comment]
Thanlks for your quick feedback, UTF-8... as for files not producing the error message

**Comment by RaptorX** [comment]
Are they UTF-8-BOM or UTF-8-RAW
because I had very rarely found that issue, and it was with ahk v1 files that the extension cannot read for some reason.

**Comment by One1Tick** [comment]
What is UTF-8-RAW, I don't have like this... All the script I have problem with seem to be UTF-8 and working one are UTF-8 and UTF-8-BOM...

**Comment by thqby** [comment]
For unknown file encodings, v2 is assumed to be utf-8 and v1 is assumed to be ansi. When a decoding error occurs using utf-8, the error is prompted.

**Comment by One1Tick** [comment]
Thanks @thqby for your huge work on the extension and for the clarification. All my old v1 files seem to be utf-8 which should produce the error but some does not... What is the best approach ? convert all v1 files to ansi ? Is there a script to do it automaticcaly ?

**Comment by thqby** [comment]
Without specifying the code page using the command line parameter, both v1 and v2 can run when utf8-bom is used; v1 does not run as expected when utf8 is used and contains non-ASCII characters.

If you know what code page your file is using, this can be done using a script.
The conversion is done by `FileRead` and `FileOpen().Write()` and specifying the appropriate code page.

**Comment by One1Tick** [comment]
Thanks for your help
