### ISSUE TITLE
Inconsistent recognition in an object's property

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#263]
Inconsistent recognition in different parts of an object's property. See these below:
```ahk
a:={ddccc:789}
d:=a.dd%'c'%cc
```
![image](https://user-images.githubusercontent.com/47076058/215310371-5cb993ae-7e0b-41c9-b233-f659b137619b.png)
![image](https://user-images.githubusercontent.com/47076058/215310373-b6c47ba8-76e4-498b-b9ae-762cde98a5b8.png)

`ddccc` is a whole property of `a`.  However, `dd` is recognized as `"Other.Property"` while the back part `cc `is recognized as `"Other" `which is nothing. Both of them are incorrect white rather than orange which is set as the property's color.
![image](https://user-images.githubusercontent.com/47076058/215311033-b5914896-181e-4d42-95f9-a767056a3e75.png)
Could you improve your plugin to recognize both of them successfully as the property of `a`?  Or it would be better if both of them could be recognized through the `semantic` instead of through `textmate scopes`.

**Comment by thqby** [comment]
Semantic tokens in complex expressions are not considered. 
In addition, they are all part of the property name and should not be `property`.

**Comment by PythonYunfei** [comment]
> Semantic tokens in complex expressions are not considered.

There's no problem. It is all up to your convenience. `Semantic tokens` is not a must.
However, as above fist two pictures show, could you please let `cc` to be recognized as the same with 'dd'?  Sure, they are all part of the property name. But they should not be two different parts.
