### ISSUE TITLE
FR: 增强if后对代码块的添加

### ISSUE THREAD

**Issue by XMB-7** [thqby/vscode-autohotkey2-lsp#264]
![image](https://user-images.githubusercontent.com/65625632/215837893-d8694777-245c-4265-b4c0-b3b62870feb3.png)
当前键入if行末回车, 直接缩进, 但此时对键入花括号并不友好, 需要多按一下shift+tab再回车往下写代码, 否则就会变成下图这种两重缩进的情况.
![image](https://user-images.githubusercontent.com/65625632/215838509-978050d6-0d29-4197-a9be-974d4522dc99.png)

而预期则是这样的, 故而希望能针对这种代码风格进一步优化, 非常感谢.
![image](https://user-images.githubusercontent.com/65625632/215839367-284839be-21f8-4e26-936b-eecacac7d1fb.png)

**Comment by thqby** [comment]
需要开启`editor.formatOnType`
