### ISSUE TITLE
"%Expr%" Problem with Extension v1.8.6

### ISSUE THREAD

**Issue by Stretch655** [thqby/vscode-autohotkey2-lsp#265]
Hi,

I'm currently using Autohotkey v2.0.2, and your extension is thinking my script must be AHK v1 because it came across the following line:

`item := { cls:"MyClass", method:"doStuff" }`
`%item.cls%.%item.method%(key)`

Can you fix this please.

**Comment by thqby** [comment]
Temporary solution: `%(item.cls)%.%(item.method)%(key)`
