### ISSUE TITLE
[BUG:]错误的自动补全

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#267]
![image](https://user-images.githubusercontent.com/47076058/215998294-1ac0796d-9b9c-431d-846a-9034db12cc53.png)
输入`m`再输入`.`，本来应该是正常键入`m.` 并显示m的属性建议，但是它现在自动补全为Map了：
![image](https://user-images.githubusercontent.com/47076058/215999077-b35f3bdb-9af4-4f04-a288-c97751c7b7a3.png)
之前不是这样。现在的这个"特性"跟习惯相悖。任何时候 想要使用某个弹出的智能建议并补全，只需`按回车`；且应该只允许通过`按回车`来补全。

**Comment by thqby** [comment]
这些特性在其他语言中也存在，现在增加了修改提交键的选项

**Comment by PythonYunfei** [comment]
对于函数来说，回车是最好的提交键，也能自动补全括号。
在面向对象中 静态方法极少在类外部使用；而类内部的静态方法的主体基本都会被`this.`或`super.`代替代了，但`this/super`目前反而不能自动补全、没有提交键的效果(`super`作为关键字甚至都不显示补全建议)。因此点语法`.`也极少在类中出现；点语法`.`大量出现的地方是实例中。而实例是动态的，不支持补全。
值得说的是，对于类来说，引入括号作为提交键非常赞👍  如此既能很方便地初始化对象，又给不补全括号提供了选择..
