### ISSUE TITLE
Help file hotkey works only on second try

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#273]
Type: <b>Bug</b>

* Start VSCode
* Select a command and press Ctrl+F1

### Expected

The help for the selected command should open

### Result

The help file is opened on the general page

### Notes

After you do this the second/third time the hotkey works as intended it only fails the first time

---

Extension version: 1.8.7
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (22.01GB free)|
|Process Argv|--crash-reporter-id bdc99747-9c48-41d5-87e2-d320011e638b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30657576
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by thqby** [comment]
Since most of the time this problem does not occur in my case, it is difficult to test what improvements would optimize this.

**Comment by RaptorX** [comment]
It has been very consistent in my case since i installed the extension.

It only happens when vscode is opened for the first time.

close all instances, open a folder with an ahk script, select a command and hit Ctrl+F1, it shows the help file but on the main page.

it cant be reproduced like that?

**Comment by thqby** [comment]
I have had this problem, but the probability of occurrence is quite small. I have tried to increase the delay, but it still happens on computers with poor performance. 
This is achieved through ahk code, you can test it directly.
