### ISSUE TITLE
自动补全增强建议：希望引入`候选键`

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#275]
希望显示输入建议时能够同时也显示每条建议对应的数字序号。就像输入法的候选框一样；此时每个数字都是一个提交键。这样，看到想选的建议，输入数字便可立刻选择该建议对应的数字 并补全。如此往往能节省不少键击。

**Comment by thqby** [comment]
符号名也可以有数字

**Comment by PythonYunfei** [comment]
下一字符为数字X的建议，(1)其序号也为X、(2)或者不给它显示序号；其他不含数字的建议，使用剩余的序号。
如果使用方案(1)，显示序号X。可先对非数字的建议排序(序号中已剔除X)，再把含X的建议插入到排好序的建议列表中。
更推荐使用方案(2)，下一字符为数字X的建议不显示序号X，且没有序号提交键的功能，因为直接键入X就能筛选。这样不必改变建议列表的原始排序。
方案(1)似乎麻烦且不太好，建议不用考虑；但方案(2)应该可行。

**Comment by thqby** [comment]
提交字符后追加到补全项中
不连续输入也能更快的筛选

**Comment by PythonYunfei** [comment]
😢不知咱们是不是互相 对彼此表达的意思有所误会..
您说的提交字符是指提交键吗？目前提交键只能选择并补全第一条建议吧？第二第三条建议目前还得先下移选框，再按提交键。
如果插件能够支持数字候选的话，那么此时你只需按下数字键`3`，就可以自动选择所显示的第三条输入建议并补全，而不用按两下`{Down}` 再按回车或提交键。

> 下一字符为数字X的建议

我此处所说的`数字X`，是指变量名包含数字的这种特殊情况的处理。比如，当变量名为`xyz7abc`时，输入‘xyz7’会跟`候选键7`冲突。此时推荐能采纳 上述增强改进中的方案(2)。

**Comment by thqby** [comment]
输入xyz7会变xyz7abc7
直接输xzc{tab}之类也能更快筛选
