### ISSUE TITLE
`{Alt Down}` snippet produces `{{Alt Down}` when invoking it with `{`

### ISSUE THREAD

**Issue by zachpoblete** [thqby/vscode-autohotkey2-lsp#286]
![brace-snippet_5s](https://user-images.githubusercontent.com/92368853/218312538-89a00c95-4d22-4b63-832c-16ee63a8d960.gif)

In this case, you need to invoke it with `{` because of the `b` at the start.

This goes for any of the other brace snippets like `{Shift Up}`, `{Click}`, etc.

**Comment by RaptorX** [comment]
Why would you want the snippet trigger to contain {}??

I bet you wouldn't have that issue if your trigger was `.alt` for example.

**Comment by RaptorX** [comment]
I thought you created it yourself.

well, you dont have to type the `{}` toget those suggestions.
I just typed `alt` and selected it from the list and got it to show up correctly.

**Comment by zachpoblete** [comment]
Yup, that works in most cases, except in the specific case I opened the issue about.

```ahk
Send('b')
```

If I want to insert `{Alt Down}` after `b` by just typing the letters, the suggestion would never pop up.

```ahk
Send('balt')
```

because `balt` isn't a trigger.

Also, in your gif, `{Alt Down}` isn't the 1st suggestion but the 3rd, so typing just the letters takes more time.

**Comment by RaptorX** [comment]
that is correct, in the first case you'd have to add a space and later remove it.
probably the way to go is that the `{` shouldnt be auto closed if we are inside of a string.

not sure if that is possible though, @thqby would confirm how that works.

**Comment by thqby** [comment]
Remove the `{` in the completion to adapt to all situations

**Comment by PythonYunfei** [comment]
> Remove the `{` in the completion to adapt to all situations.

I think the issue can be considered. As inputting `"se"` will automatically complete `"Send"`, rather than `"sSend"`.  The same should be applied to `"{A"` too, just like what `"se"` does.
