### ISSUE TITLE
Opening a new window displays interpreter info erroneously

### ISSUE THREAD

**Issue by Repiteo** [thqby/vscode-autohotkey2-lsp#287]
Whenever a new VSCode window is opened, information regarding the AHK interpreter is displayed at the bottom left. This is regardless of whether opening a completely fresh instance, or if it's opening a cached window. If the current window is changed in any way (opening a new file, closing your current file, changing tabs, etc), the extension returns to normal behaviour

- Fresh instance
![](https://i.imgur.com/Tn4Z5ro.png)
- Cached instance
![](https://i.imgur.com/wjMQoNm.png)

**Comment by thqby** [comment]
The activation mechanism of the vscode plug-in has changed, and the plug-in has been started in advance.
