### ISSUE TITLE
TreeView/ListView Methods are derived incorrectly

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#289]
Type: <b>Bug</b>

When hovering over listview/treeview methods nothing is displayed and using commas in the parameters, the parameter suggestions are incorrect.

They are being derived from the GUI object instead of the correct control object.

Sample code:
<details>

```
main := Gui()
lvCtrl := main.addListView('w600 r10', ['test'])
tvCtrl := main.addTreeView('w600 r10')

lv.Add('', 'test')
tv.Add('test', 0)
```

</details>

![GIF 2-16-2023 13-45-19](https://user-images.githubusercontent.com/328761/219447527-5ad47b38-3527-4a73-87c6-602e0c0b03de.gif)

---

Extension version: 1.9.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (19.32GB free)|
|Process Argv|--crash-reporter-id 5662df70-51fa-468c-b034-629cf5419c2f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30662992
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by thqby** [comment]
The sample code is irrelevant to the issue.

Type derivation of such expressions `obj.prop[params]` is not currently supported.

**Comment by RaptorX** [comment]
> The sample code is irrelevant to the issue.
> 
> Type derivation of such expressions `obj.prop[params]` is not currently supported.

beside the GIF i provided sample code that is not `obj.prop[params]` syntax, Ill provide it again:

```
main := Gui()
lvCtrl := main.addListView('w600 r10', ['test'])
tvCtrl := main.addTreeView('w600 r10')

lv.Add('', 'test')
tv.Add('test', 0)
```

I guess this is supported because other derivations work fine.

**Comment by RaptorX** [comment]
> main := Gui()
> lvCtrl := main.addListView('w600 r10', ['test'])
> tvCtrl := main.addTreeView('w600 r10')
> 
> lv.Add('', 'test')
> tv.Add('test', 0)

ooops you are right, that example works fine.

okay then, it is that the other way is not supported then.

**Comment by RaptorX** [comment]
> I think it would be very complicated and a lot of work to support the case in the OP. What about JSDoc style type hints? Those might be simpler to implement.

Yeah, at least having those might be a good idea.
