### ISSUE TITLE
[FR] 对多行注释符的成对匹配

### ISSUE THREAD

**Issue by XMB-7** [thqby/vscode-autohotkey2-lsp#291]
目前应该是非贪婪匹配, 但这无法支持多行注释内含多行注释. 若能优化为成对匹配, 那真是再好不过了.
<img src="https://user-images.githubusercontent.com/65625632/219697108-98dad124-54c7-4c6d-a078-82a8415f8b2f.png" alt="image" width="300" height="450"> <img src="https://user-images.githubusercontent.com/65625632/219697233-8313849f-e97b-4e71-a72e-2c2430aa8e7b.png" alt="image" width="300" height="450">

**Comment by XMB-7** [comment]
我的意思是, alt&1前的/*最好能和alt&2后的*/成对匹配, 而不是现在这样与divider后的*/成对匹配, 致使alt&2这段代码如今并没有被注释掉.

**Comment by thqby** [comment]
不存在多行注释内含多行注释，你确定上面的能运行？

**Comment by XMB-7** [comment]
现在运行不了啊, 因为非贪婪匹配而是成对匹配, 导致最后多出来一个`*/`不被识别, 我的意思是它本该被识别的.
目前类似regex的非贪婪匹配, `/*`向后匹配到第一个`*/`即止, 所以导致出现这一问题.

**Comment by thqby** [comment]
ahk的注释就这样，另外我没发现css是这样的
![image](https://user-images.githubusercontent.com/28240311/219709612-9a5553dc-e880-4001-81f3-eb9d61457e07.png)

**Comment by XMB-7** [comment]
我对编程不是很熟悉, 我是在使用obsidian笔记软件的过程中在记事本里这么简单写过css, 彼处是完全可运行的, 我不清楚这是不是前端的代码规范, 但如果用记事本这么写能运行无误, 我想这应该就是合法的写法.
然后我刚刚也用记事本试了试ahk, 惊讶地发现ahk确实不支持这么写注释. 所以像我说得这么改确实与官方规范不同, 虽然我感觉这么改只有好处没有坏处, 但我也完全理解如果不做改动, 或许我得考虑更换一种写多行注释的习惯.
还是很感谢开发这款插件, 作为ahk初学者, 感觉真的很好用.

**Comment by PythonYunfei** [comment]
> 我对编程不是很熟悉, 我是在使用obsidian笔记软件的过程中在记事本里这么简单写过css, 彼处是完全可运行的, 我不清楚这是不是前端的代码规范, 但如果用记事本这么写能运行无误, 我想这应该就是合法的写法. 然后我刚刚也用记事本试了试ahk, 惊讶地发现ahk确实不支持这么写注释. 所以增加像我说的这种功能确实与官方规范相违背, 虽然个人感觉这么改应该是没有坏处的, 但我也完全理解如果不做改动的话, 所以或许我得考虑更换一种写多行注释的习惯. 还是很感谢开发这款插件, 作为ahk初学者, 感觉真的很好用.

只有AHK语法和解释器先 支持了成对匹配。插件才有可能支持。插件只是为了跟AHK的语法保持一致的。
