### ISSUE TITLE
Server retrying until failing in Neovim when using newer versions.

### ISSUE THREAD

**Issue by gwenreynolds94** [thqby/vscode-autohotkey2-lsp#292]
I've been using the `1.7.0` version, from back when I set up the server for Sublime Text 4 and it's been working great. Specificaly [here is a link](https://github.com/gwenreynolds94/thqby-ahk-lsp-1_7_0/tree/main) to a repository where I just uploaded the specific instance of the lsp I've been using -- the one that does work.

Whenever I use the method of downloading and installing the lsp mentioned in the README, or even just use the installed extension from VSCode, the server starts and stops repeatedly until coc gives up.

I can share whatever other information is needed to diagnose.

`EDIT:` I just upgraded my Sublime Text 4 ahk lsp using the one I installed that doesn't work with Neovim ( version `1.9.0` ). It works fine in Sublime Text.

### Here is my coc setup:
```
"languageserver": {
    "lsp-ahk2": {
        //┌──────────────────────────┐
        //│ BROKEN [Version 1.9.0] ▼ │
        //├──────────────────────────┴──────────────────────────────────────────────┐
        //│ "module": "C:/Users/<User>/.config/ahk2-lsp-new/server/dist/server.js", │
        //└─────────────────────────────────────────────────────────────────────────┘
        // [Version 1.7.0] ▼
        "module": "C:/Users/<User>/.config/ahk2-lsp/server/dist/server.js",
        "args": ["--node-ipc"],
        "filetypes": ["autohotkey"],
        "initializationOptions": {
            "locale": "en-us",
            "AutoLibInclude": "All",
            "CommentTags": "^;;\\s*(?<tag>.+)",
            "CompleteFunctionParens": false,
            "Diagnostics": {
                "ClassStaticMemberCheck": true,
                "ParamsCheck": true
            },
            "ActionWhenV1IsDetected": "Continue",
            "FormatOptions": {
                "indent_string": "    ",
                "keep_array_indentation": true,
                "max_preserve_newlines": 2
            },
            "InterpreterPath": "C:/Program Files/AutoHotkey/v2/AutoHotkey.exe",
            "WorkingDirs": [],
            "SymbolFoldingFromOpenBrace": false
        }
    }
}
```

**Comment by thqby** [comment]
Errors caused by different configuration synchronization mechanisms.

**Comment by gwenreynolds94** [comment]
Works great! Thank you!
