### ISSUE TITLE
Format options documentation

### ISSUE THREAD

**Issue by kczx3** [thqby/vscode-autohotkey2-lsp#294]
Is there any documentation on the various formatter options and the corresponding values for each option?  I see that at some point one_true_brace must have changed from true/false to now be -1/0/1 but I don't understand which one to pick based on my preference.

**Comment by RaptorX** [comment]
I dont think there is any at the moment, I faced the same issue before, some options have several choices but it is not clear what they mean.

**Comment by thqby** [comment]
What are these styles called?
```
if 1 {
} else {
}

if 1 {
}
else {
}

if 1
{
}
else
{
}
```

**Comment by RaptorX** [comment]
• One True Brace (1TBS)
• One True Brace (1TBS) Variant: Stroustrup
• Allman

you can find more info here: https://www.wikiwand.com/en/Indent_style
