### ISSUE TITLE
[1.9.2] IsSet color

### ISSUE THREAD

**Issue by lstrfwp** [thqby/vscode-autohotkey2-lsp#298]
IsSet syntax color is same as keyword.
![image](https://user-images.githubusercontent.com/110793221/222046217-12234b9e-bdaf-4765-a6b4-df1137786b07.png)

**Comment by thqby** [comment]
see https://www.autohotkey.com/docs/v2/v2-changes.htm#names

Reserved words includes `IsSet`.

**Comment by lstrfwp** [comment]
Oh I see now. https://www.autohotkey.com/docs/v2/lib/IsSet.htm
`Although IsSet uses the same syntax as a function call, it may be considered more of an operator than a function. The keyword IsSet is reserved for the use shown here and cannot be redefined as a variable or function. IsSet cannot be called indirectly because any attempt to pass an uninitialized variable would cause an error to be thrown.`
