### ISSUE TITLE
Request textDocument/hover failed.

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#3]
switches := []
    switches := switches.Clone()
    switches.push '/x'

When hovering over `Clone` or `push`, I get an error in the Output pane.

> [Error - 6:51:03 pm] Request textDocument/hover failed.
>  Message: Request textDocument/hover failed with message: Maximum call stack size exceeded
>  Code: -32603 

In the real script, `switches` is a function parameter, and its initial Array is provided by the caller.

**Comment by thqby** [comment]
This will be fixed in v0.6.9
