### ISSUE TITLE
Fail to parse object with property defined by an expression

### ISSUE THREAD

**Issue by aseiot** [thqby/vscode-autohotkey2-lsp#30]
Demonstrated  as follow:

`o := { (true ? "x" : "y") : "value"}`

**Comment by thqby** [comment]
```
o := { %(true ? "x" : "y") %: "value"}
```

**Comment by thqby** [comment]
```
o := { %(true ? "x" : "y") %: "value"}
```

**Comment by aseiot** [comment]
I can't remember whether the syntax is allowed officially, and I can not found related instrument in document as well.
But the code I posted is working.

Anyway, I will change my code to suppress the alert. Thanks!

**Comment by thqby** [comment]
![image](https://user-images.githubusercontent.com/28240311/125155112-5145c800-e190-11eb-941e-a420a5eaeabe.png)
Tested with AutoHotkey_L v2.0-a138-7538f26

**Comment by aseiot** [comment]
Sorry, It may due to I am running my custom build of AHK, which object literal is supporting "string" as the property name as before. I will double check the issue with official AHK release before reporting next time.
