### ISSUE TITLE
Syntax highlight error

### ISSUE THREAD

**Issue by anonymous1184** [thqby/vscode-autohotkey2-lsp#303]
When using WinAPI calls (with or without parenthesis), only the first call to the function is highlighted as function, next calls have a `variable` semantic type.

![](https://user-images.githubusercontent.com/53758552/226297276-f596f47e-96e7-4a5f-9bdf-08ed05c660da.png)

Also, those shouldn't be highlighted the same as built-ins? Given that are built into the interpreter? And only after being declared highlighted as a user function?

A whole block of code shows that even after 4 calls not being highlighted, the last one is (given that is the first call to that particular function).

![](https://user-images.githubusercontent.com/53758552/226300962-112d1757-64d8-4563-bd53-c759d7622423.png)

Thanks for your time and amazing ideas and tools.

**Comment by thqby** [comment]
The editor has not yet implemented the winapi call information, which is another bug

**Comment by thqby** [comment]
Now supports WinAPI calls, and provide function name completion by adding `;@include-winapi`

**Comment by anonymous1184** [comment]
Awesome, thank you!
