### ISSUE TITLE
angle bracket include paths not being detected correctly

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#304]
Type: <b>Bug</b>

* use an `#include` with `<` and `>` for the path

### Expected

No issues

### Result

![image](https://user-images.githubusercontent.com/328761/226935606-16c48d68-ce4f-41d4-819b-78de7af4b2df.png)

The path gets marked as an error even though when setting the static path `(lib\path\to\library.ahk)` works just fine.

The path exists and the script is working fine, is just that the highlighter thinks the path doesnt exist.

### Notes

When opening a folder the `#include` is **not marked** as an error.
This only happens when trying to type the path with angle brackets (which also doesnt give suggestions).

Seems like it is looking at my `Documents\Autohotkey\Lib` path, and ignoring the local library.

![image](https://user-images.githubusercontent.com/328761/226936429-bb901ebe-3095-4bc1-b6de-54d97803bdc7.png)

_Even though I'm explicitly telling it to only look for the local library and ignore others._

--- 

Extension version: 1.9.5
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (18.90GB free)|
|Process Argv|--crash-reporter-id 5662df70-51fa-468c-b034-629cf5419c2f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30677849
pythonb192:30669360
azdwalk:30687957
pythonms35:30686772

```

</details>

**Comment by thqby** [comment]
`AutoLibInclude` only affects completion.

The issue is not reproduced.
Maybe the lib folder appears after the file is opened. 
Maybe the current file tree structure leads to misjudgment.
