### ISSUE TITLE
Option to turn off missing return value warning?

### ISSUE THREAD

**Issue by lstrfwp** [thqby/vscode-autohotkey2-lsp#305]
I redefined `SplitPath` to return an object, but I get a warning that the function is missing a return value. 
Is there an option to turn it off?

```
SplitPath.DefineProp "Call", {
    Call:(this, Path, &outFileName?, &outDir?, &outExt?, &outNameNoExt?, &outDrive?) => (
        (Func.Prototype.Call)(this, Path, &outFileName?, &outDir?, &outExt?, &outNameNoExt?, &outDrive?),
        {FileName: OutFileName, Dir: OutDir, Ext: outExt, NameNoExt: OutNameNoExt, Drive: OutDrive}
    )
}

path := SplitPath("D:\Test\Dir\File.txt")
OutputDebug path.FileName ", " path.Dir ", " path.Ext ", " path.NameNoExt ", " path.Drive
```

**Comment by thqby** [comment]
`path := (SplitPath("D:\Test\Dir\File.txt"))`

**Comment by thqby** [comment]
or set `AutoHotkey2.Diagnostics.ParamsCheck` to `false`.

**Comment by thqby** [comment]
or create a new `.d.ahk` file with the same name in the same directory, and add the following similar code.
```
SplitPath(Path [, &OutFileName, &OutDir, &OutExtension, &OutNameNoExt, &OutDrive]) => _PathObj

class _PathObj {
	static FileName
	static Dir
	static Ext
	static NameNoExt
	static Drive
}
```

**Comment by lstrfwp** [comment]
> create a new `.d.ahk` file with the same name in the same directory

I was not sure what this meant at first until I searched the code and found `file + '.d.ahk'`. Now I understand. Thanks.

**Comment by lstrfwp** [comment]
How do I show custom parameter hints for class methods? Parameter hints are not showing when I define it in the `.d.ahk` file. In my script, I have:
```
({}.DefineProp)(String.Prototype, "TestMethod", {Call:(this, a, b, c) => MsgBox("Test " a " " b " " c)})

Object.Prototype.DefineProp("Test", {Call:(this, a, b, c) => MsgBox("Test " a " " b " " c)})

x := Object()
x.Test(1, 2, 3)

"str".TestMethod(1, 2, 3)
```

**Comment by lstrfwp** [comment]
Using `;@include custom.d.ahk`  also works but it keeps warning about conflicting class.

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/110793221/b65cf600-19dd-4815-9915-fa7288099325)

**Comment by thqby** [comment]
If you do not inherit the original class, you will lose methods, properties, etc.

The above `String` will be used as an object instead of a string type.

**Comment by lstrfwp** [comment]
I see, `@extends` is still needed. The path to the vscode-autohotkey2-lsp folder changes every update. Can `@extends` use a relative path?

**Comment by thqby** [comment]
`~\syntaxes\ahk2\Object`, Relative to the plug-in root
