### ISSUE TITLE
Symbol Renaming from definition not working as expected

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#306]
Type: <b>Bug</b>

![GIF 4-5-2023 08-38-37](https://user-images.githubusercontent.com/328761/230083078-1e0b0392-eb1b-4fa3-a329-bbd9f62cb661.gif)

* Create File1.ahk with this code:

```
#Include test2.ahk

test.selectfile()
test.selectfile()
test.selectfile()

class test
{
	__New()
	{
		test.selectfile()
	}

	static selectfile()
	{
		sleep 10
	}
}
```

* Create file2 with this code
```
#include file1.ahk

test.selectfile()
test.selectfile()
test.selectfile()
test.selectfile()
```
* On **FILE 1** click on `selectfile` and hit f2. Rename to `SelectWorkingFiles`
* All instances get changed on `File 1` but **not on File 2**.
* Reset
* On **FILE 2** click on `selectfile` and hit f2. Rename to `SelectWorkingFiles`
* All instances on `File 2` get updated and **only the definition on File 1 gets updated**, calls to the method on `File 1` get ignored.

### Expected

I would assume that if the symbol was identified, renaming it should rename the definition and all the calls to that method in the current file and all files where the method is being called.

---

Extension version: 1.9.6
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (20.68GB free)|
|Process Argv|--crash-reporter-id 5662df70-51fa-468c-b034-629cf5419c2f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
pythonb192:30669360
azdwalk:30687957
pythonms35:30701012
pythonclientmvcf:30705674

```

</details>

**Comment by Zach47** [comment]
I have encountered similar problems: sometimes it seems like the vs code editor cannot recognize the same function defined and used on different ahk files even thought these files are properly included.
我也遇到类似的问题：好像VS Code编辑器有时无法识别出同一个函数，特别是当它的定义和使用分别处于不同的ahk文件中时，哪怕是这些文件都使用了合理的include语句。

By the way, the example yous posted seems like will causes recursive include?

**Comment by RaptorX** [comment]
> I have encountered similar problems: sometimes it seems like the vs code editor cannot recognize the same function defined and used on different ahk files even thought these files are properly included. 我也遇到类似的问题：好像VS Code编辑器有时无法识别出同一个函数，特别是当它的定义和使用分别处于不同的ahk文件中时，哪怕是这些文件都使用了合理的include语句。
> 
> By the way, the example yous posted seems like will causes recursive include?

Yeah I didnt think the example through that much, but I only `#include file2.ahk` on the main file, so in the actual code I only have one include and I still have the same issue.

**Comment by thqby** [comment]
> By the way, the example yous posted seems like will causes recursive include?

Not if you don't use `#InlucdeAgain`.

The above issue may have been omitted when dealing with them.

**Comment by RaptorX** [comment]
> > By the way, the example yous posted seems like will causes recursive include?
> 
> Not if you don't use `#InlucdeAgain`.
> 
> The above issue may have been omitted when dealing with them.

The actual code is:

`File1.ahk` includes `File2.ahk`

`File2.ahk` doesnt include anything... 

I still get the same behavior.

The Gif is wrong because i made the example pretty quickly.
