### ISSUE TITLE
Issue with class extends declaration diagnostics when classes locate at different scripts

### ISSUE THREAD

**Issue by aseiot** [thqby/vscode-autohotkey2-lsp#31]
In case we have two scripts, one is something like this:
```
class a extends b               ; b will report unknown error.
{
}

#include b.ahk
```

while b.ahk contain the define of **class b**
```
class b
{
}
```

**Comment by thqby** [comment]
When opening this script, the include file may not be found. Reopen this script or edit it once, it will re-diagnose.

**Comment by aseiot** [comment]
I just tried. Reopen or edit are not working.

**Comment by thqby** [comment]
![image](https://user-images.githubusercontent.com/28240311/125155354-c534a000-e191-11eb-9dc3-db7f763a1103.png)

**Comment by aseiot** [comment]
ok, after reopen several times, the demonstrated code is not report error anymore. 
But my real complicated scripts still fail to recognize the base class. I will try to narrow down the issue, and report it later.

**Comment by aseiot** [comment]
After more tests. Although the problem is not solved, but I believe the issue is not cause by scripts in separated scripts. I will close this Issue.

**Comment by aseiot** [comment]
After more tests. Although the problem is not solved, but I believe the issue is not cause by scripts in separated scripts. I will close this Issue.

**Comment by aseiot** [comment]
Seems related with **traverseinclude** in **Lexer.ts**

```
	function traverseinclude(include: any, cururi: string) {
		let s = '';
		for (const uri in include) {
			if (fileuri === uri) {
				has = true;
				if (!list[cururi])
					list[cururi] = include[cururi] || { path: s = URI.parse(cururi).fsPath, raw: '' }, count++;
			}
			if (doc = lexers[uri]) {
				if (!list[uri])
					list[uri] = include[uri], count++;
				if (cururi !== uri)
					traverseinclude(doc.include, uri);
			}
		}
	}
```
Which cause **"Maximum call stack size exceeded error"**
Change to this, fix the problem.
```
	function traverseinclude(include: any, cururi: string) {
		let s = '';
		for (const uri in include) {
			if (fileuri === uri) {
				has = true;
				if (!list[cururi])
					list[cururi] = include[cururi] || { path: s = URI.parse(cururi).fsPath, raw: '' }, count++;
			}
			if (doc = lexers[uri]) {
				if (!list[uri]){
					list[uri] = include[uri], count++;
					if (cururi !== uri)
						traverseinclude(doc.include, uri);
				}
			}
		}
	}
```

**Comment by thqby** [comment]
What caused this error?

**Comment by aseiot** [comment]
Those code make Lexer fail to parse the include libs, which coincidently make parent class not be found. Actually, this error make something like "Goto Definition" across script files failed as well.
