### ISSUE TITLE
Feature Request: Indent Options in For Loops, Loops, If, Else, Switch, Case

### ISSUE THREAD

**Issue by sousvideonlow** [thqby/vscode-autohotkey2-lsp#310]
I know many people do write one line of code after For Loops or Loops

However I personally do not, and it would be great to have an option to turn off indent on the next line after For Loops, Loops, If, Else, Switch, Case, etc.

I usually write my code like this

```
for key, value in SomeMap
{
    Do something indented
    and another action
}
```

Currently the automatic step will be this

```
for key, value in SomeMap
    {
        Double Indents?
    }
```

**Comment by thqby** [comment]
set `editor.formatOnType` to `true`.

**Comment by sousvideonlow** [comment]
Hmm @thqby, that uses
https://en.wikipedia.org/wiki/Indentation_style#K&R_style K&R but how do I
set it to Allman?
https://en.wikipedia.org/wiki/Indentation_style#Allman_style

**Comment by sousvideonlow** [comment]
Hmm @thqby, that uses https://en.wikipedia.org/wiki/Indentation_style#K&R_style K&R but how do I set it to Allman? https://en.wikipedia.org/wiki/Indentation_style#Allman_style

**Comment by thqby** [comment]
set `FormatOptions.brace_style` to `Allman`

**Comment by sousvideonlow** [comment]
I put this in settings.json and it does the allman brace now but after
Loops the return is still tabbed in

"AutoHotkey2.FormatOptions": {
        "brace_style": "Allman"
    },
    "editor.formatOnType": true

**Comment by fade2gray** [comment]
Just an FYI - Requires triple backticks for code blocks.

```
"AutoHotkey2.FormatOptions": {
        "brace_style": "Allman"
    },
    "editor.formatOnType": true
```

looking like this

```
for i,v in test
    {

    }
```

**Comment by thqby** [comment]
![2](https://user-images.githubusercontent.com/28240311/232483019-583c2011-ca03-46cf-bb38-342ae600f562.gif)

**Comment by sousvideonlow** [comment]
Oh nice thank you, it's working now, Thanks for showing how to implement it.
