### ISSUE TITLE
isset not defined

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#312]
Type: <b>Bug</b>

As of 1.9.8 IsSet is not defined as a function. Instead is being treated as a keyword as an `other.operator`.

![image](https://user-images.githubusercontent.com/328761/233515130-1f2fbacc-b06c-49dc-9444-b36924ef438c.png)

---

Extension version: 1.9.8
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (19.84GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\Dropbox\\Guests\\the-Automator\\Client Work\\KellyCoughlin\\Format Converter\\src --crash-reporter-id 5662df70-51fa-468c-b034-629cf5419c2f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30705553
azdwalk:30687957
pythonms35:30701012
03d35959:30706073
pythonfmttext:30716742

```

</details>

**Comment by thqby** [comment]
see #298

**Comment by RaptorX** [comment]
What broke is that before `1.9.8` when you typed it, the parenthesis would be autocompleted, now it is not working as expected.
It was perfectly fine before due to the fact that it aligns more with how the interpreter is really expecting it to be used.

I don't agree with the new change:

keyword `IsSet` is *reserved* so as to not be used as a variable. 

here are some examples of operators:

```
if var1 and var2
    msgbox true

if var1 is String
   msgbox true

if isset var      ; this will fail spectacularly because IT IS NOT AN OPERATOR...
   msgbox true
```

You get the following error when you try to use it as an operator:

![image](https://user-images.githubusercontent.com/328761/233639105-417ff7e0-ea20-4b9c-b826-4fbafff4d36a.png)


So it **must** be used as a function call at all times even thought It **might be considered** an operator. 
That's the key point there: `it MAY be considered X` doesn't mean that `it IS`.
For lexical purposes I think It should be back to how it was working before.

**Comment by thqby** [comment]
> the parenthesis would be autocompleted

It need set `AutoHotkey2.CompleteFunctionParens`.

> Although IsSet uses the same syntax as a function call, it may be considered more of an operator than a function.

This is described in the help documentation, and users cannot define a function named `IsSet`.

c++ also has operators like `sizeof`, it's used the same way as a function.
