### ISSUE TITLE
增加对`...) {...`中的花括号对的缩进支持

### ISSUE THREAD

**Issue by XMB-7** [thqby/vscode-autohotkey2-lsp#315]
例如对于函数定义, 这是我个人的代码书写习惯, 目前第320-334行的函数参数部分可以折叠, 但是335-384的函数主体部分无法折叠.
<img src="https://user-images.githubusercontent.com/65625632/233843345-3fd8eda4-af8c-44da-aef3-47f4367c78f5.png" width="300">

所以期望能够增加此类折叠支持, 实现类似如下效果, 非常感谢.
<img src="https://user-images.githubusercontent.com/65625632/233843750-04aa7b45-a79d-45d7-b893-d30c6b242710.png" width="300">

**Comment by thqby** [comment]
缩进还是折叠？
函数主体是可以折叠的

**Comment by XMB-7** [comment]
抱歉，标题写错了，是折叠。
我这边函数主体似乎折叠不了，亦即图1中第335行并没有折叠箭头的标志存在。至于图2则是另一个ahkv1插件的折叠效果。

**Comment by thqby** [comment]
![image](https://user-images.githubusercontent.com/28240311/233847695-b4adb647-7082-4366-9124-66a2046844be.png)

**Comment by XMB-7** [comment]
非常感谢, 设置后就可以折叠了.
