### ISSUE TITLE
Variable Initialization with postfix

### ISSUE THREAD

**Issue by wilkster** [thqby/vscode-autohotkey2-lsp#319]
; Below will flag a warning about index not being assigned a value
dummyFunction1() {
   someArray := Array()
   index++ := someArray.Length
}
; Below works fine
dummyFunction2() {
   someArray := Array()
   index := someArray.Length
}

Either is valid syntax wise

**Comment by RaptorX** [comment]
Autohotkey v2 will throw a warning with the first function.

You must assign a number before using the `++` opera d.

```
index := 0
Index++ ; all is good
Msgbox index
```

```
index++ ; this will get a warning
Msgbox index
```

Try it. :)

**Comment by sousvideonlow** [comment]
Yes it seems for good reason that version 2 requires variables to be explicitly declared before we can perform any arithmetic function on them.

**Comment by wilkster** [comment]
Being a postfix operator isn't:
index++ := someArray.Length
the same as
index  := someArray.Length + 1
or
index := someArray.Length
++index

So it is initialized, then incremented
Seems to work that way in AHK V2 anyhow (C works that way as well as I recall)

**Comment by rebornsick** [comment]
Seems like I have the same issue. Every first variable that WingetPos/MouseGetPos asked get a warning. This showcase from documentation have 5 warnings:
```
EWD_MoveWindow(*)
{
    CoordMode "Mouse"  ; Switch to screen/absolute coordinates.
    MouseGetPos &EWD_MouseStartX, &EWD_MouseStartY, &EWD_MouseWin
    WinGetPos &EWD_OriginalPosX, &EWD_OriginalPosY,,, EWD_MouseWin
    if !WinGetMinMax(EWD_MouseWin)  ; Only if the window isn't maximized 
        SetTimer EWD_WatchMouse, 10 ; Track the mouse as the user drags it.

    EWD_WatchMouse()
    {
        if !GetKeyState("LButton", "P")  ; Button has been released, so drag is complete.
        {
            SetTimer , 0
            return
        }
        if GetKeyState("Escape", "P")  ; Escape has been pressed, so drag is cancelled.
        {
            SetTimer , 0
            WinMove EWD_OriginalPosX, EWD_OriginalPosY,,, EWD_MouseWin
            return
        }
        ; Otherwise, reposition the window to match the change in mouse coordinates
        ; caused by the user having dragged the mouse:
        CoordMode "Mouse"
        MouseGetPos &EWD_MouseX, &EWD_MouseY
        WinGetPos &EWD_WinX, &EWD_WinY,,, EWD_MouseWin
        SetWinDelay -1   ; Makes the below move faster/smoother.
        WinMove EWD_WinX + EWD_MouseX - EWD_MouseStartX, EWD_WinY + EWD_MouseY - EWD_MouseStartY,,, EWD_MouseWin
        EWD_MouseStartX := EWD_MouseX  ; Update for the next timer-call to this subroutine.
        EWD_MouseStartY := EWD_MouseY
    }
}
```
Every first "X" like `&EWD_MouseStartX` `&EWD_OriginalPosX` `&EWD_MouseX` `&EWD_WinX` warned not being assigned a value.

**Comment by wilkster** [comment]
@rebornsick Yes, similar issue,
WinGetPos &EWD_WinX, &EWD_WinY, , , EWD_MouseWin
Will flag a warning, where
WinGetPos(&EWD_WinX, &EWD_WinY, , , EWD_MouseWin)
Will not

**Comment by wilkster** [comment]
Perfect, thank you!
