### ISSUE TITLE
部分情况下无法识别自定义函数和全局变量

### ISSUE THREAD

**Issue by Zach47** [thqby/vscode-autohotkey2-lsp#321]
## 问题：打开单个文件时，拓展无法识别自定义函数和全局变量。
**相关资料**：以下为两张截图，以及相关AHK脚本的源码。

图1：打开单个文件时，拓展无法识别自定义函数和全局变量。
图2：将涉及到的文件全都打开，且同时排布显示。此时拓展可以识别自定义函数，但是依然无法识别全局变量。

![pic1](https://github.com/thqby/vscode-autohotkey2-lsp/assets/20013248/3205cab6-aae7-448a-9040-bcef721a2eb5)
![pic2](https://github.com/thqby/vscode-autohotkey2-lsp/assets/20013248/574528d4-2931-4791-b1b9-96b4ce6af0d9)

```
;------------------------------
;file: main.ahk
;------------------------------
#Requires AutoHotKey v2.0

global_a := "Apple"

#Include include_all.ahk


;------------------------------
;file: include_all.ahk
;------------------------------
#Include "a_libs\my_functions.ahk"
#Include "b_scripts\my_script.ahk"


;------------------------------
;file: a_libs\my_functions.ahk
;------------------------------
show_Tips(text, t_ms)
{
    ToolTip(text)
    SetTimer(ToolTip, -abs(t_ms))
}


;------------------------------
;file: b_scripts\my_script.ahk
;------------------------------
Space & d::
{
    global global_a

    show_Tips(global_a, 7000)
}
```

**Comment by Zach47** [comment]
那么是否可以为扩展增加一个配置字段，允许将当前仓库中的某个AHK脚本设置为优先解析？
比如：
```
    "settings": {
        "mainscript": "main.ahk"
    }
```

**Comment by XMB-7** [comment]
我记得以前的版本好像是正常的, 从主脚本拆分出若干子脚本, 即便不给子脚本加#include也并不会遇到这个问题.

---

> 由于解析顺序原因或未加#include，在打开脚本子文件时，不一定能识别出整个脚本的所有文件。
 
我在main.ahk里面导入utils.ahk和test.ahk. 在utils.ahk中, 定义一个类HotkeyHelper并实例化为hotkey_helper. 然后在test.ahk中调用实例方法. 
结果如下图所示, 虽然提示找不到该实例及其实例方法, 但当我多打一些字符后, 发现其实已经识别了的, 所以或许并不是因为解析顺序的原因而无法识别, 而是其实已经识别但不知何故被当成未识别了. 

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/65625632/eb06de1e-5510-4b8c-8459-9de863eb1098)
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/65625632/6e4aa185-eba4-4344-ab65-adbd2a5e68f9)

**Comment by thqby** [comment]
已修复打开文件夹时，缓存被清理的情况。

给每个脚本加上#include可以确保在打开单一文件时，都能提供完整的分析。

**Comment by Zach47** [comment]
请问`;@include xxx.ahk` 是 `vscode-autohotkey2-lsp` 专门添加的语法特性吗？谢谢

**Comment by thqby** [comment]
是的
