### ISSUE TITLE
Always prompt EISDIR

### ISSUE THREAD

**Issue by aseiot** [thqby/vscode-autohotkey2-lsp#325]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/600263/8a6016a5-52d8-4817-b0f7-3777918f314e)

**Comment by RaptorX** [comment]
I think you should add some context as to what were you trying to do or what does that directory contains and other things, the error by itself might not be enough for the author to fix the issue my man 😅

**Comment by aseiot** [comment]
That is really a difficult to narrow down the issue by specific the directory, and that is why I was request feature to able to define the while and black list of directory (#326 ).

**Comment by thqby** [comment]
This error may occur with 8.3 Short filenames.
