### ISSUE TITLE
Maximun call stack size exceeded when hover the property of an object

### ISSUE THREAD

**Issue by aseiot** [thqby/vscode-autohotkey2-lsp#330]
Demonstrated as follow, reproduce by mouse hove the position as shown.
```
Obj(o?){
	if !IsSet(o)
		return Obj({prop:10})
	return o
}

S := Obj()

Msgbox S.prop
```

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/600263/1cbe1639-af0f-4a22-a547-1ff125d62b52)

**Comment by RaptorX** [comment]
+1 it has been happening to me as well with GUI object properties.
