### ISSUE TITLE
Unassigned variables used with IsSet still generate a warning

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#334]
```AutoHotkey
MsgBox IsSet(nope)
```

> Variable 'nope' appears to never be assigned a value

One use of IsSet is to check for the presence of a class, function or other variable in a script which may or may not define it. For instance, a file may be used both standalone and as an #include.
  - In the former case, the variable is not defined. There is no warning from AutoHotkey, and getting a warning from the editor is distracting.
  - In the latter case, the main script can define a variable which affects the behaviour of the #include. An assignment cannot be included to suppress the warning, because the variable may be defined by a class or function. If the overall script defines a class or function, the interpreter would flag the assignment as an error.

For `#Warn VarUnset`, `IsSet(nope)` provides a way to suppress warnings about a specific global variable while still allowing the use case described above.

`IsSet(nope)` should not cause a warning even if the variable is not assigned. It should prevent other references to the variable from causing this warning.

**Comment by thqby** [comment]
Yes, this has not yet been implemented. I don't know how to identify this situation yet. `IsSet(a?b:c)`

**Comment by Lexikos** [comment]
Identify it for what purpose/in what way?

AutoHotkey doesn't support that. IsSet's parameter expression should be only a plain variable reference or dynamic reference, nothing more complex.
