### ISSUE TITLE
Autocomplete missing for DoubleClick event on Text Control

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#335]
Type: <b>Bug</b>

* Create a GUI
* Add a control
* Use the `OnEvent` method
* Type `DoubleC`

No suggestion for DoubleClick is given.

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/c94373d2-b3a7-463c-a068-e53493bcf7f1)

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/0d05ab46-7dbf-4b20-9d2e-100292dbb94b)

### Notes
The documentation asserts that DoubleClick is accepted by Text controls.

https://www.autohotkey.com/docs/v2/lib/GuiOnEvent.htm#DoubleClick

---

Extension version: 2.0.4
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (21.98GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\Dropbox\\Guests\\Scripts to Work On\\Libraries\\joe\\LaunchEditor v2.ahk --crash-reporter-id 5662df70-51fa-468c-b034-629cf5419c2f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
pythongtdpathcf:30739705
dh2dc718:30763024

```

</details>

**Comment by thqby** [comment]
These are not provided by the extension, but by vscode.

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/28240311/a156550b-20ea-4855-b37b-e3be1076a1de)
