### ISSUE TITLE
Incorrect warning for outer variable only assigned in closure

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#338]
```AutoHotkey
memoize(f) {
    local value ; value is underlined with a warning marker
    return () => IsSet(value) ? value : value := f()
}

m := memoize(() => MsgBox("called",,"y/n"))
MsgBox m() ; Displays "called" and answer
MsgBox m() ; Displays answer
```

> Variable 'value' appears to never be assigned a value

It is assigned a value in the closure.  It appears that the extension considers it a separate variable; I presume this is why Rename Symbol changes either the first occurrence or the other three, not all four at once.

For reference:
> By default, a nested function automatically "captures" a non-static local variable of an outer function when the following requirements are met:
>  - The outer function must refer to the variable in at least one of the following ways:
        a. By declaring it with local, or as a parameter or nested function.
        b. As the non-dynamic target of an assignment or the reference operator (&).
>   - The inner function (or a function nested inside it) must refer to the variable non-dynamically.

The scope is established by `local value` and the absence of a declaration in the nested function.

**Comment by thqby** [comment]
I fixed this a few days ago, but didn't notice that some of the code was in the wrong order.

**Comment by lstrfwp** [comment]
The warning is still there if the variable is assigned using a function's byref parameter.

**Comment by thqby** [comment]
> The warning is still there if the variable is assigned using a function's byref parameter.

What do you mean?

**Comment by lstrfwp** [comment]
Variable `var` appears to never be assigned a value
```
foo() {
    local var
    bar()
    bar() {
        function(&var)
    }
}

function(&v) {
    v := 1
}
```
