### ISSUE TITLE
No indent on #HotIf

### ISSUE THREAD

**Issue by wsw70** [thqby/vscode-autohotkey2-lsp#340]
When using `#HotIf` it would be great if the code beneath would be indented. Currently the following code

```autohotkey
#HotIf !GetKeyState("NumLock", "T")
    NumpadAdd:: Send("hello")
#HotIf
```
gets forcefully reformatted to

```autohotkey
#HotIf !GetKeyState("NumLock", "T")
NumpadAdd:: Send("hello")
#HotIf
```

**Comment by thqby** [comment]
set `AutoHotkey2.FormatOptions.indent_between_hotif_directive`

**Comment by wsw70** [comment]
Thank you very much!
