### ISSUE TITLE
# Maybe a bug or the problem was created by myself

### ISSUE THREAD

**Issue by robin758** [thqby/vscode-autohotkey2-lsp#343]
# Maybe a bug or the problem was created by myself

Hi, bro!
## So when i run the ahk_scirpt, i have this problem---the script was not running, but this warning😂
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/83524955/3655ac4c-706a-4212-80a4-f7c58cf0ecb0)

**Comment by PythonYunfei** [comment]
@robin758 Maybe he needs you to explain a bit more. 😂 Or it's not a matter.

**Comment by PythonYunfei** [comment]
@robin758 
Oh. Maybe because I often keep it newest.
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/3d612648-3103-474b-9c5f-dcdb299931a5)
