### ISSUE TITLE
Request textDocument/(hover||completion) failed Code: -32603 

### ISSUE THREAD

**Issue by 8CTN8** [thqby/vscode-autohotkey2-lsp#347]
output error:
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/52889675/a04a7cac-ba54-407d-9ac1-525410feb866)
hover:
```js
[Error - 1:28:58 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Maximum call stack size exceeded
  Code: -32603
```
completion:
```js
[Error - 1:32:32 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Maximum call stack size exceeded
  Code: -32603
```

I have a custom class "UISettingsData()"
```ahk
class UISettingsData {
	__New(ui := Gui()) {
		this.gui := ui
		this.title := ''
		this.window := {
			x: 1940,
			y: 460,
			width: 500,
			height: 200,
		}
		this.Init()
	}
	
        ; some more methods here
}
```
in my main script i impliment this like 
```ahk
Global ui := UISettingsData()
```
when i hover over anything coming after ui it throws the hover error.
```ahk
ui.title := 'Twitch Chat Settings'
```
hover over "title" and the error is thrown.

The completion error appears when i write out `ui.` and then also doesnt attempt to complete.

context:
- the UISettingsData class is an external script included as a library `#Include <utils\import>`
- The errors started to appear yesterday (15-07-2023) for the first time.

Hypothesis: 
I use a lot of ui references, the fact that it says `Maximum call stack size exceeded` leads me to think that it hit some kind of limit with how many implementations it can handle at once. i tested this by removing some line but it didnt seem to remove the error. This could still be true if the implementations were somehow cached in any way.

**Comment by thqby** [comment]
The above code does not reproduce the issue.

`Maximum call stack size exceeded` error is caused when the recursion is too deep while deriving the type.
