### ISSUE TITLE
extension fails to get environment variables

### ISSUE THREAD

**Issue by Hifilo** [thqby/vscode-autohotkey2-lsp#349]
Thanks for making this extension!

I noticed that setting language to v2 bugs out vscode. v1 works fine, but v2 gives errors.

![2iMvm0UdGx](https://github.com/thqby/vscode-autohotkey2-lsp/assets/92943726/e30aba57-675a-49e4-ae3f-eaeb7a5486d3)

![Code_tItHKA4k1k](https://github.com/thqby/vscode-autohotkey2-lsp/assets/92943726/2dec3c4c-6074-42d7-813e-3baf48f17d50)

output:
![Code_ZQmIo7JKfV](https://github.com/thqby/vscode-autohotkey2-lsp/assets/92943726/4cf410da-b638-482d-a07b-6267afa1456b)

If it makes any difference, I use both wsl2 & windows. when I work with ahk scripts I launch vscode in windows OS.

**Comment by thqby** [comment]
When the extension is started, an ahk process will be started to obtain some environment variables, such as `A_MyDocuments`, `A_Desktop`, `A_AhkPath`, `A_ProgramFiles` and `A_Programs`, which may be used in `#include`. Resolving these paths will help to introduce correct other scripts and provide features such as completion and symbol finding.

The above error occurs when the ahk process cannot be started.

**Comment by Hifilo** [comment]
I see, this is odd. I can run all my ahk scripts fine. however trying to launch `autoHotkey64.exe` or the `AutohotkeyUX.ahk` gives me the error script file not found. 

![explorer_uSJAavvAbm](https://github.com/thqby/vscode-autohotkey2-lsp/assets/92943726/3783be5f-1bcd-4729-b9b5-634705bdc956)

I'm not quite sure why.

**Comment by thqby** [comment]
launch `AutoHotkey64.exe` will execute `AutoHotkey64.exe AutoHotkey64.ahk`.

Under what circumstances does the above error `This app can't run on your PC` occur?
Non-windows environment?

**Comment by Hifilo** [comment]
> launch `AutoHotkey64.exe` will execute `AutoHotkey64.exe AutoHotkey64.ahk`.
> 
> Under what circumstances does the above error `This app can't run on your PC` occur?

same issue on re install. I also tried installing using `for this user` option. same result.

it happens, on launch, or when I open a script that uses v2.

**Comment by thqby** [comment]
If the file `C:\Program Files\AutoHotkey\v2\AutoHotkey.exe` does not exist, will show error `The AutoHotkey interpreter does not exist, re-specify in 'Settings-AutoHotkey2.InterpreterPath'`.

What is the status of your `v2\AutoHotkey.exe`?

**Comment by Hifilo** [comment]
![explorer_vUD5HqfooZ](https://github.com/thqby/vscode-autohotkey2-lsp/assets/92943726/fef0a6cc-03d8-44f2-b62b-a20522e524de)

it's there, but its a 0kb file. It's a reinstall, so as far as I can tell its as vanilla as it gets

**Comment by thqby** [comment]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/28240311/0b8ad1a6-d637-4df8-b016-7fba4998c45b)
it is a symlink.

**Comment by Hifilo** [comment]
> ![image](https://user-images.githubusercontent.com/28240311/256268963-0b8ad1a6-d637-4df8-b016-7fba4998c45b.png) it is a symlink.

okay. so the installer wasn't creating the symlink. force deleting the file & reinstall created symlink. I reset interpreter back to original path. seems to be working as expected now.
