### ISSUE TITLE
Auto add asterisk on multiline comment

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#350]
Type: <b>Feature Request</b>

I use multiline comments with asterisks at the beginning for styling purposes.

It would be great if the lexer could detect if a line has an asterisk and when I press enter it would add it to the next line as well like this:

![Code_SU2HV1GF6U](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/45886b98-f685-4dde-94f3-2793899671ec)

---

Extension version: 2.0.8
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by thqby** [comment]
![2](https://github.com/thqby/vscode-autohotkey2-lsp/assets/28240311/5ebd375d-3f64-4406-bb60-4ad3220e27cf)

That's the way it is right now.

**Comment by RaptorX** [comment]
Hmm...
I guess it is because im missing the additional asterisk at the top... Ill give it a try, thanks!

**Comment by RaptorX** [comment]
Not working on my end.

Do I have to set some settings?

![Code_95rTzBvLuJ](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/78051aa5-b5bf-4bc8-84bc-bfbcd794a90f)

**Comment by thqby** [comment]
No need for additional settings, I don't know why you can't do it there.

**Comment by RaptorX** [comment]
Maybe a conflicting extension?

I don't have any extension that messes with the comments though, but I'll take a quick look.

Is there a way to reset your extensions settings without having to uninstall?

**Comment by thqby** [comment]
Probably not.

**Comment by RaptorX** [comment]
It is indeed interacting with another extension. I will let you know which one after I continue testing.

**Comment by RaptorX** [comment]
When this setting is set like this I get the issue shown above:

```
"editor.autoIndent": "brackets"
```

Can you check if you can replicate?

**Comment by thqby** [comment]
yes, i see that.
