### ISSUE TITLE
Not detecting V1 scripts

### ISSUE THREAD

**Issue by markhavemann** [thqby/vscode-autohotkey2-lsp#352]
If I open a v1 script, I get multiple parsing errors popping up every second.

First the output shows: 
`This might be a v1 script, and the lexer stops parsing. Try switching to AutoHotkey v1.`

then every second it will pop up multiple errors relating to v1, eg.
`Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'toLowerCase')`

I have included v1 requires in my scripts but still the extension tries to parse them:
`#Requires AutoHotkey v1.1.33+`

**Comment by thqby** [comment]
`switching to AutoHotkey v1` requires an ahk v1 extension.

**Comment by RaptorX** [comment]
You might want to install this guy: [Mark viemers Autohotkey Plus Plus](https://marketplace.visualstudio.com/items?itemName=mark-wiemer.vscode-autohotkey-plus-plus)

**Comment by markhavemann** [comment]
Thanks for the feedback. Installing a v1 extension seems to have fixed this.
