### ISSUE TITLE
How does the quickHelp function work?

### ISSUE THREAD

**Issue by mark-wiemer** [thqby/vscode-autohotkey2-lsp#353]
Hi, I'm trying to understand the AHK snippet that powers the automatic search in [`quickHelp`](https://github.com/thqby/vscode-autohotkey2-lsp/blob/fa0782e8a221e54e5755358eb594ae9cc872ca1a/client/src/extension.ts#L348), but it seems like there are some magic numbers. I want to provide this same function in my extension (ref https://github.com/mark-wiemer-org/ahkpp/issues/78), but I don't want to blindly copy code without understanding what it does.

Can you explain where some of these magic numbers come from in the `NumPut` calls? And how the function works in general?

**Comment by mark-wiemer** [comment]
For example, I'm trying to make it work with v1 help, but it's always opening a new window. I haven't changed the code at all but I've confirmed the v1 help window has the same `ahk_class` and `ahk_exe` as v2 😔

```ahk
; Find existing help window if it exists and set it on top
chm_hwnd := 0, chm_path := '${helpPath}', DetectHiddenWindows(true), !(WinGetExStyle(top := WinExist('A')) & 8) && (top := 0)
for hwnd in WinGetList('AutoHotkey ahk_class HH Parent')
    for item in ComObjGet('winmgmts:').ExecQuery('SELECT CommandLine FROM Win32_Process WHERE ProcessID=' WinGetPID(hwnd))
        if InStr(item.CommandLine, chm_path) {
            chm_hwnd := WinExist(hwnd)
            break 2
        }
if top && top != chm_hwnd
    WinSetAlwaysOnTop(0, top)

; Create new help window if necessary
if !chm_hwnd
    Run(chm_path, , , &pid), chm_hwnd := WinWait('AutoHotkey ahk_class HH Parent ahk_pid' pid)
```

**Comment by thqby** [comment]
> For example, I'm trying to make it work with v1 help, but it's always opening a new window. I haven't changed the code at all but I've confirmed the v1 help window has the same and as v2 😔`ahk_class``ahk_exe`
> ```
> if InStr(item.CommandLine, chm_path)
> ```

Check the command line parameters of the process corresponding to the open help window and file path of chm.

> Can you explain where some of these magic numbers come from in the `NumPut` calls?

Initialize IID_IAccessible `{618736E0-3C3D-11CF-810C-00AA00389B71}`

This function looks for an open help window or launches a help window and then executes js code through the IID_IHTMLWindow2 interface to find the keyword.

**Comment by mark-wiemer** [comment]
Thanks for the update. I'm curious where some of the `int64` hexadecimal values come from, namely the `NumPut`s here:

```ahk
; Assign magic value to a pointer
NumPut('int64', 0x11CF3C3D618736E0, 'int64', 0x719B3800AA000C81, IID_IAccessible := Buffer(16))

; Send the search if user has selected something
if ${!!searchText} && !DllCall('oleacc\\AccessibleObjectFromWindow', 'ptr', ctl, 'uint', 0, 'ptr', IID_IAccessible, 'ptr*', IAccessible := ComValue(13, 0)) {
    ; Get the HTML window of the opened help file
    IServiceProvider := ComObjQuery(IAccessible, IID_IServiceProvider := '{6D5140C1-7436-11CE-8034-00AA006009FA}')
    ; another magic number
    NumPut('int64', 0x11D026CB332C4427, 'int64', 0x1901D94FC00083B4, IID_IHTMLWindow2 := Buffer(16))
    ComCall(3, IServiceProvider, 'ptr', IID_IHTMLWindow2, 'ptr', IID_IHTMLWindow2, 'ptr*', IHTMLWindow2 := ComValue(9, 0))
```

**Comment by thqby** [comment]
You can find this in the win32 metadata or winapi c++ header file. Then they are represented by two int64.

In win32 metadata.
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/28240311/45b381f1-26dc-4734-a936-8899c575d938)
