### ISSUE TITLE
JSDoc @example minor syntax highlighting issue

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#355]
This is a small styling issue.  

When working inside an `@example` tag and a [`code block`](https://www.autohotkey.com/docs/v2/lib/Block.htm) is created, the JSDoc asterisk prefix `*` of all following lines receives normal code syntax highlighting until the line after the closing brace `}` instead of being comment styled.  

This styling only affects syntax highlighting in the editor and doesn't affect how the Intellisense tooltip looks.  

Not a big deal but I wanted to get it documented as a bug.  

How it looks:
![example code prefix error](https://i.imgur.com/ltQhkRS.png)

How it should look:
![example code fixed](https://i.imgur.com/aFq8DjJ.png)

**Comment by thqby** [comment]
This conflicts with highlighting code in comments. In what case was the following picture obtained?

**Comment by GroggyOtter** [comment]
I'm not sure I understand the question.

The top picture is a screenshot I took of an example I typed up to illustrate the issue.  

The second one is a Paint edit to show how I thought it should look.

The asterisk `*` highlight discrepancy seems to only happen on new lines of code blocks in an example.

**Comment by thqby** [comment]
The code blocks between `{` and `}` are rendered as a whole. Separating them makes the textmate scopes of a normal code block not as expected. It's not worth the cost to fix them.

**Comment by GroggyOtter** [comment]
> It's not worth the cost to fix them.

I've been in situations where it's not worth the time to fix a little thing.  
Completely understandable.

Closing.

**Comment by RaptorX** [comment]
I usually leave examples without asterisks, but i guess you'd have to remove them if they get added automatically:
```
/*
 * - `ComObj` - ComObject returned by the application based on the type selected by idObject
 *
 * ### Examples:
 * Get the application object from MS Word
 * ```
	wd := ObjectFromWindow(OBJID_NATIVEOM, "- Word ahk_class OpusApp", "_WwG1")
	wd := wd.Application
 * ```
 * Get the application object from MS Excel
 * ```
	xl := ObjectFromWindow(OBJID_NATIVEOM, "- Excel", "EXCEL71")
	xl := xl.Application
 * ```
 */
 ```
