### ISSUE TITLE
How do you test your extension?

### ISSUE THREAD

**Issue by mark-wiemer** [thqby/vscode-autohotkey2-lsp#357]
I'm looking at incorporating some of this logic into my extension, but I don't see any unit tests or other automated tests here. How do you ensure you don't break anything when you change functionality?

**Comment by thqby** [comment]
I haven't used unit testing yet. I usually open script library files one by one to determine if there are any obvious bugs.

**Comment by RaptorX** [comment]
> I'm looking at incorporating some of this logic into my extension, but I don't see any unit tests or other automated tests here. How do you ensure you don't break anything when you change functionality?

It breaks sometimes 😂

Doesn't happen often but now that I see his reply I understand the reason. He is very responsive though, bugs don't last more than a few days.

But having unit testing is a plus.

I'm really happy to see you working on updating the v1 extension, I was going to update it to the lsp version but life has gotten in the way. I really think this v2 one is the best one or there even compared to other languages, so it's great to see you in contact with thqby.

Good luck!

**Comment by mark-wiemer** [comment]
Great to hear :) @thqby, if you ever need help setting up unit testing, just let me know, I'd be happy to open a PR on this repo :)
