### ISSUE TITLE
無法正確解析在 #Include 的檔案路徑中的 %A_UserName%

### ISSUE THREAD

**Issue by nperovic** [thqby/vscode-autohotkey2-lsp#358]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/122501303/5e1c2270-3a4c-4eac-aaab-aa26d1b3f08d)
在 VSCODE 中提示錯誤，但 ahk 實際上可以正確解析，文檔中也有說明可以使用 `A_UserName`

**Comment by fade2gray** [comment]
Double quotes needed, maybe?  - `#Include "C:\Users\%A_UserName%\OneDrive\Lib_script.ahk"`

**Comment by nperovic** [comment]
> Double quotes needed, maybe? - `#Include "C:\Users\%A_UserName%\OneDrive\Lib_script.ahk"`

Unfortunately, it doesn't help.

**Comment by fade2gray** [comment]
`#Include "C:\Users\" A_UserName "\OneDrive\Lib_script.ahk"` ?
`#Include "C:\Users\" . A_UserName . "\OneDrive\Lib_script.ahk"` ?
