### ISSUE TITLE
Custom #Requires String

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#359]
Type: <b>Feature Request</b>

I would like to customize the `#Requires` string that gets added automatically when creating a new `.ahk` file.

I usually add `; prefer 64-Bit`. It would be nice if we could set the full `#Requires ` string on the extension settings.

Extension version: 2.1.0
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by thqby** [comment]
Maybe you can add user-defined snippets.

**Comment by RaptorX** [comment]
I have hotstrings for those.

The problem is that when I create a new blank ahk file in vscode it seems that the extension automatically adds the `#Requires` directive.

If that's the case, it would be cool to allow for customization of what the string should be

**Comment by thqby** [comment]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/28240311/0fd78ede-50d0-4911-acf6-dae85ed60022)

Set the template in ahk dash.

**Comment by PythonYunfei** [comment]
Yes, it just a matter of creating new file or a template file to copy.  If this is implemented in a plugin, it's difficult to cater for everyone's personal tastes.

**Comment by Lexikos** [comment]
> Set the template in ahk dash.

@thqby, does that mean the extension should use whatever template is set as default?

I'm not seeing that behaviour at all. I get an unwanted "#Requires AutoHotkey v2.0" in each new file, regardless of what the default template is. I had it unset, which defaults to "Empty" in ui-newscript.ahk. Setting "Empty" explicitly and setting the default to an actual file had no effect on your extension.

**Comment by thqby** [comment]
This happened a few weeks ago, and I didn't implement the feature in the extension, so I guess it may be caused by the settings in dash.

However, when I disable `mark-wiemer.vscode-autohotkey-plus-plus` extension, this no longer happens.

**Comment by Lexikos** [comment]
@thqby thanks, I confirm the same. I didn't realize I had that extension enabled in some workspaces and not others.
