### ISSUE TITLE
Module file "/home/domen/vscode-autohotkey2-lsp/server/dist/server.js" not found for LS "lsp-ahk2"

### ISSUE THREAD

**Issue by DomenickD3** [thqby/vscode-autohotkey2-lsp#360]
I was trying to install this for a few hours now, and am running into an issue.

Error:
Module file "/home/domen/vscode-autohotkey2-lsp/server/dist/server.js" not found for LS "lsp-ahk2"

- I followed the install instructions listed for "Other Editors: Vim or Neovim"
- I ran node install.js, and the server.js file is located at the path I specified in CocConfig (I verified this).

<img width="958" alt="module file not found" src="https://github.com/thqby/vscode-autohotkey2-lsp/assets/11238549/e85942af-ab48-4623-892a-040746cd4abd">

Extension Version:
thqby.vscode-autohotkey2-lsp v2.1.0 is the latest version.

Environment:
Windows, MSYS2, bash, vim 9.0.1403

**Comment by thqby** [comment]
`~/vscode-autohotkey2-lsp/server/dist/server.js`

**Comment by DomenickD3** [comment]
with: 
~/vscode-autohotkey2-lsp/server/dist/server.js

I get:
[coc.nvim] Module file "C:\Users\domen/vscode-autohotkey2-lsp/server/dist/server.js" not found for LS "lsp-ahk2"

but, that's not my home directory from:
domen@DD3-THINKPAD[~/node-testing]$echo $HOME
/home/domen
domen@DD3-THINKPAD[~/node-testing]$echo ~
/home/domen

**Comment by thqby** [comment]
What's your version of nodejs? for windows?

**Comment by DomenickD3** [comment]
Node.js v18.16.1.
Windows 11.

Shall I find the windows path of where the extension is installed in vscode and use that?

**Comment by thqby** [comment]
So you should use the windows version of vim or nvim, not the linux version.

**Comment by DomenickD3** [comment]
OK,
 
 For reference, I just tested with this, and this got me past the error:
  "module": "C:/Users/domen/.vscode/extensions/thqby.vscode-autohotkey2-lsp-2.1.0/server/dist/server.js",

**Comment by DomenickD3** [comment]
Closing as completed. Thank you.
