### ISSUE TITLE
New syntax in v2.1-alpha.2

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#361]
These new constructs are currently flagged as errors by the extension:
  - `a?.b` or `a?.()` - this is a combination of maybe (`?`) and member access (`.`). There can be space between the two operators.
  - `a? ?? b` (it's redundant but valid; but `a?.b? ?? c` is not the same as `a?.b ?? c`)
  - `a ??= b`

There is also `#DefaultReturn`, but it may be removed, and it doesn't appear to cause an error or warning.

**Comment by thqby** [comment]
I added this support last week, but it hasn't been released yet.

> There can be space between the two operators.
Currently, Spaces between `?` and `.` cause syntax errors.
