### ISSUE TITLE
Some not highlighted

### ISSUE THREAD

**Issue by yw4z** [thqby/vscode-autohotkey2-lsp#362]
Hi thanks for your efforts on this one

this ones not highlighted

Built in > ComObject(), ComValue(), Buffer(), Map(), IsSet()

Gui related > Gui(),Gui.Add(),Gui.AddEdit(),Gui.AddButton(),Gui.Show(),Gui.SetFont(),Gui.Destroy()
, GuiControl.Opt(), GuiControl.OnEvent()
Built in methods > .call , .bind , .push , .ExecQuery()
User Class methods
User Functions

i guess you didn't highlight user functions and methods with purpose
Highlighting gui() and its methods would be better for reading

have a nice day

**Comment by thqby** [comment]
Are you sure your current language mode is ahk2 and not ahk.

**Comment by yw4z** [comment]
yes im on ahk2

![Screenshot-20230820183814](https://github.com/thqby/vscode-autohotkey2-lsp/assets/28517890/0c951cb8-1d11-4482-a3d0-15c2785f06ed)

looks like it works normal but not works on this theme
https://marketplace.visualstudio.com/items?itemName=ullissescastro.theme-bracketsdark

also i tried on this as alternative theme
https://marketplace.visualstudio.com/items?itemName=Sukadia.sukadia-dev-dark

**Comment by thqby** [comment]
This is a matter of theme, and some tokens are not given corresponding colors.

**Comment by yw4z** [comment]
yes i m looking to json files of builtin themes, i guess he/she skipped one. thanks again
