### ISSUE TITLE
希望 当输入所有字符时自动关闭补全选框

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#365]
目前，当补全选框中剩下0个选项时，补全选框会自动关闭。
当补全选框中剩下1个选项时，且该选项所有字符都已经输入时，也希望补全选框能自动关闭。
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/079b4f41-fda5-41f1-8d48-e86e5575605c)

**Comment by thqby** [comment]
没这功能

**Comment by PythonYunfei** [comment]
> 没这功能

@thqby Pycharm等编辑器 输满字符后会自动关选框的
