### ISSUE TITLE
Error: Request textDocument/hover failed

### ISSUE THREAD

**Issue by The-CoDingman** [thqby/vscode-autohotkey2-lsp#368]
I have found that the mouse passing over certain values produces an error with the textDocument/hover every time, even if the mouse just passes over the value briefly.

Any value that seems like it should produce the hover message that is prefaced with "this.gui." produces an error.

Examples: this.gui.Hwnd, this.gui.Add, this.gui.Func(), etc.

> Message: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'relevance')

**Comment by thqby** [comment]
The information provided is not sufficient to reproduce the issue.

**Comment by The-CoDingman** [comment]
I've made a short video of producing the errors.  Essentially, I'm passing my mouse over certain lines of code
`this.gui.Hwnd
this.gui.Maximize()
this.gui.Add("Button", "", "Click me")`
it produces an error every time.  It only produces an error on the last property of each line, not on the `this` or `gui`.

https://imgur.com/a/wRG31O9

**Comment by thqby** [comment]
Unable to access the link, please provide code snippets.

**Comment by The-CoDingman** [comment]
Well, while writing up an example for you I was able to pinpoint a key piece in producing the errors.

```
class Example {
    gui := unset ;errors are produced when this line is present
    __New() {
        this.gui.Hwnd
        this.gui.Maximize()
        this.gui.add("Button", "", "Click me")
    }
}
```

**Comment by thqby** [comment]
Still unable to reproduce.

**Comment by The-CoDingman** [comment]
I don't know then, that's the entire code for this test file. Once saved as an ".ahk" file, the error can be produced for me.

https://github.com/thqby/vscode-autohotkey2-lsp/assets/119650557/89fb030b-79fc-4f64-b887-2aadb5422ae2

**Comment by thqby** [comment]
Does the issue still exist? I still can't reproduce it.

**Comment by The-CoDingman** [comment]
The issue still exists, but as I mentioned before it was only occurring if `gui := unset` was declared as well. So for now I've commented out that line of code.

**Comment by thqby** [comment]
Has it been updated to the latest version?

**Comment by The-CoDingman** [comment]
Just updated and confirmed that it is still happening.

**Comment by thqby** [comment]
This issue can be reproduced when using ahk_L as the interpreter.

**Comment by RaptorX** [comment]
I am able to reproduce it with `AutoHotkey  v2.0.4`
and `AutoHotkey v2 Language Support  v2.1.4 `

```
2023-09-04 13:37:16.796 [error] [thqby.vscode-autohotkey2-lsp] provider FAILED
2023-09-04 13:37:16.797 [error] Error: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'relevance')
	at c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.1.2\client\dist\extension.js:1:38068
	at ie (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.1.2\client\dist\extension.js:1:38362)
	at c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.1.2\client\dist\extension.js:1:33146
	at Immediate.<anonymous> (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.1.2\client\dist\extension.js:1:33166)
	at process.processImmediate (node:internal/timers:466:21)
2023-09-04 13:37:24.987 [info] ExtensionService#_doActivateExtension pejmannikram.vscode-auto-scroll, startup: false, activationEvent: 'onLanguage:log'
```
