### ISSUE TITLE
Suggested Feature: Exception List for textDocument/hover feature

### ISSUE THREAD

**Issue by The-CoDingman** [thqby/vscode-autohotkey2-lsp#369]
I would love to see an option added for allowing the users to add keywords to an exception list for the textDocument/hover feature.  As an example of reasoning, I don't need to see the popup for MsgBox or Tooltip but I do still want to see it for things like DllCall and other more complicated or less used functions.

**Comment by thqby** [comment]
`textDocument/hover` only fires when the mouse is over a word. If you don't want to see this prompt, you are unlikely to actively move the mouse over the word.
