### ISSUE TITLE
Formatting problem when calling chained method.

### ISSUE THREAD

**Issue by NKU100** [thqby/vscode-autohotkey2-lsp#374]
I think it should be formatted like this:
```
m := Map()
    .Set("a", 1)
    .Set("b", 2)
    .Set("c", 3)
```
Actually:

```
m := Map()
    .Set("a", 1)
        .Set("b", 2)
            .Set("c", 3)
```

Is it possible to make it like what I want? I'm now using default formatting options.

**Comment by ZhuangQu** [comment]
see https://github.com/thqby/vscode-autohotkey2-lsp/issues/371

**Comment by NKU100** [comment]
Thank you. You are doing a nice job.
