### ISSUE TITLE
Possible bug with constant condition

### ISSUE THREAD

**Issue by mark-wiemer** [thqby/vscode-autohotkey2-lsp#375]
This line in Lexer.ts will always be true as it's an assignment, not a comparison. Is this intentional?

https://github.com/thqby/vscode-autohotkey2-lsp/blob/7411ae53a434beea314e9e18a4320d8e9ce1b3ed/server/src/Lexer.ts#L5885

**Comment by thqby** [comment]
yes, it's bug.
