### ISSUE TITLE
Feature request: #Warn All/LocalSameAsGlobal highlighting

### ISSUE THREAD

**Issue by Descolada** [thqby/vscode-autohotkey2-lsp#382]
Would it be possible to add a feature that would highlight all local variables inside functions and methods that haven't been explicitly declared as `local` whenever the script has `#Warn All` or `#Warn LocalSameAsGlobal`?  

Meaning that whenever that directive is enabled, then in the following function
```
Test() {
    out := "test"
    return out
```
the variable `out` would have a yellow squiggly-line underneath it, but not in this case:
```
Test() {
    local out := "test"
    return out
```

**Comment by thqby** [comment]
`#Warn` is applied to multiple files of the script. But in the editor, a file can be referenced by multiple scripts, and their `#Warn` may conflict. And I think turning on `#Warn LocalSameAsGlobal` will only increase useless tips.

**Comment by Descolada** [comment]
Perhaps there's some other way to determine which local variables might conflict with global ones in the currently open file? I've gotten GitHub issues opened for some of my libraries because people using `#Warn All` were getting LocalSameAsGlobal errors. Eg the user writes script.ahk
```
#include "Test.ahk"
#Warn All
out := 123
```
and I've written library Test.ahk:
```
Test() {
    out := "test"
    return out
}
```

The user will now get an error, because I forgot to mark `out` as local. Since it's fairly difficult to notice and manually define all short-name locals (such as i, j, x, y, out, ret etc...) which might conflict with locals, then I'm making this feature request.

**Comment by Descolada** [comment]
The situation in your screenshot is exactly what I'd like, yes!

> The current syntax is unlikely to conflict with global variables, so it is time to delete #Warn LocalSameAsGlobal.
I'm not quite sure what you mean by this. Current syntax allows reading global variables from inside functions but not writing to them. This means that the following is allowed and causes a warning:
```
#Warn LocalSameAsGlobal, MsgBox
out := "hello"
Something()
Something() {
    if out == "something"
        MsgBox "is something"
}
```
It's highly unlikely to be writing a library and use `out == "something"` without defining it first, because in that case the global `out` wouldn't be defined and your current syntax highlighting then highlights `out` as undefined local. This means that if Something() were inside a library, then only the following is possible:
```
out := "hello"
Something()
Something() {
    out := ""
    if out == "something"
        MsgBox "is something"
}
```
Since in this case the local variable can't rewrite the global one, the warning caused by LocalSameAsGlobal is unnecessary and it follows that LocalSameAsGlobal could be removed altogether. Is this what you meant?

**Comment by thqby** [comment]
> Since in this case the local variable can't rewrite the global one, the warning caused by LocalSameAsGlobal is unnecessary and it follows that LocalSameAsGlobal could be removed altogether
yes. because there is a super global variable in v1, it is easy to get a bug in a big script because the global variable is wrongly written. In this case, `#warn LocalSameAsGlobal` is useful.

**Comment by Descolada** [comment]
Thanks for your input. I agree it was a lot more useful in v1 and border-line unnecessary in v2, except perhaps for beginner users who are not using a good editor with syntax highlighting. 
I'll close this request for now, but I'd still like to ask you to consider adding this in a future update (as very low priority).
