### ISSUE TITLE
Continuation section Comment option not recognized

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#384]
> Comments (or **Comment** or Com or C): Allows semicolon comments inside the continuation section

"C", "Com" and "Comments" are highlighted as valid continuation section options, but "Comment" is highlighted red with strikethrough.
```AutoHotkey
x :=
(Comment
; Comment in an expression
"foo"
)
y := "
(Comment
; Comment in a string
foo
)"
```

----

As an aside, continuation sections are highlighted inaccurately:
  - `; Comment in a string` is not highlighted as a comment, but AutoHotkey interprets it as one when C option is present. 
  - It interprets escape sequences as normal even when the `` ` `` (literal/auto-escape backtick) option is present; i.e. highlighting `` `n `` when `n` isn't actually part of the sequence.

I understand that these and other inaccuracies with continuation sections might not be worth fixing.

There are some more inaccuracies that maybe you shouldn't fix, as AutoHotkey v2.1 could fix them instead:
  - `; Comment in an expression` is still interpreted as a comment if the C option is removed, whereas AutoHotkey currently treats it as an error.
  - `/*` is interpreted as a comment (unless it is in a string), whereas AutoHotkey currently treats it as an error.

**Comment by thqby** [comment]
> `; Comment in a string` is not highlighted as a comment, but AutoHotkey interprets it as one when C option is present.

Because it is complicated to implement, there are only differences in highlighting, so I am too lazy to do it. I will consider it.
