### ISSUE TITLE
希望只显示一个工作文件夹的警告

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#385]
希望只显示当前工作文件夹的警告，而不是显示整个工作区的警告。
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/43a67559-6688-4bbe-9c20-3fe8cd07c50f)
如图，一个工作区下往往有很多个工作文件夹。开发者新建某个工作文件夹的本意正是希望自己只专注于当前这个工作夹的任务，而不希望 被之外的其他工作文件夹的内容  所分散注意力。
因此，插件的行为也最好应如此。希望插件也能像工作文件夹的本意一样，只显示当前文件所处的 工作文件夹的 警告。

**Comment by thqby** [comment]
只关注一个文件夹，那就只打开一个文件夹就好了。
要分开管理不同工作文件夹需要启动多个nodejs进程，在每个nodejs进程中都要保留很多相同的缓存（本地库，用户库等），还不如根据需要打开目标文件夹

**Comment by PythonYunfei** [comment]
目前是已经建了工作区懒得改了..
目前情况是插件要把整个工作区中每一个工作文件夹的警告都要搜索并缓存一遍
若能在这种情况下 采取建议：只储存一个文件夹的警告；切换文件夹后，再储存另一个文件夹文件的警告。
  那么这样的话，  缓存只会更少，不必要的开销也减少了..

**Comment by thqby** [comment]
设置`AutoHotkey2.Files.Exclude`

**Comment by PythonYunfei** [comment]
> 设置`AutoHotkey2.Files.Exclude`

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/bbaafb44-f097-457a-ac9e-7a6eea98e96f)
现在即便排除了所有，还照样显示其他工作文件夹的警告
