### ISSUE TITLE
没有#include，出现一长溜随机字符

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#386]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/f4f0fff9-073c-454d-9092-b703be3125a2)

**Comment by thqby** [comment]
文件里没有就是其他插件引入的

**Comment by PythonYunfei** [comment]
在codeGPT插件中删掉apikey后没事了
