### ISSUE TITLE
#HotIf snippet missing space

### ISSUE THREAD

**Issue by lstrfwp** [thqby/vscode-autohotkey2-lsp#389]
https://github.com/thqby/vscode-autohotkey2-lsp/blob/bf32d1dcae0a47391211a957baf5d5ccb89df8bd/syntaxes/ahk2.json#L19

Why is `#HotIf` the only directive snippet with no space at the end?

**Comment by nopdan** [comment]
Save issue as `#MaxThreadsBuffer`

**Comment by lstrfwp** [comment]
> #HotIf can be used alone.

I forgot about that.
