### ISSUE TITLE
Case应该和Switch对齐

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#393]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/60c4a910-9390-4ee2-9770-72557c1d39cb)
希望Case往左移一下。就像`elseif`和`if`对齐一样。也和文档中的写法一样：
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/5ea1667f-c482-428b-a585-db90e130b162)
和`elseif`、`if`那样，它们本是平级。
感觉连着一两个关键字 二次缩进，并没好处..

**Comment by RaptorX** [comment]
Yes!

This should be optional though, cause some people like it as it currently is.

But I rather have it default to have cases line up with the switch command. That is standard in many styles and is the same style used in the documentation as well.

**Comment by PythonYunfei** [comment]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/82ffff69-af70-48f2-b642-3532c8c323d4)
希望能再加个选项。目前VSCode界面中好像没看到入口..
