### ISSUE TITLE
Can't find appx/MSIX hardlinks

### ISSUE THREAD

**Issue by Descolada** [thqby/vscode-autohotkey2-lsp#394]
Hello,
It appears that the Interpreter Path in User or Workspace can't be a hardlink from the `C:\Users\user\AppData\Local\Microsoft\WindowsApps` folder and results in a "not find!" error. This is probably because it's linking to a restricted folder and the file size appears as 0 bytes, which might cause `fs.existsSync` to falsely report false. 
If you don't know what appx/MSIX is: it's Microsofts packaging format which Microsoft Store uses for its apps and installs them in a sandboxed environment. MSIX packages are installed to `C:\Program Files\WindowsApps` which by default can't be read or written to by regular users, but hard links for the apps are created in `C:\Users\user\AppData\Local\Microsoft\WindowsApps` folder. This means that multiple users can use a single sandboxed app. For example, AHK v1 is available in Microsoft Store in this format.

How to reproduce this issue without installing anything extra:
Set any program from `C:\Users\user\AppData\Local\Microsoft\WindowsApps` folder as the Interpreter Path and try running a script with Ctrl+F5 hotkey. For example, using a non-symlinked program such as `C:\Program Files\Mozilla Firefox\firefox.exe` launches it just fine, whereas `C:\Users\user\AppData\Local\Microsoft\WindowsApps\skype.exe` throws the error.

Alternatively install AutoHotkey v1 Store Edition from Microsoft Store:
This path works fine: `C:\Program Files\WindowsApps\HaukeGtze.AutoHotkeypoweredbyweatherlights.com_1.1137.101.0_x64__6bk20wvc8rfx2\AutoHotkey.exe`
Whereas this doesn't: `C:\Users\user\AppData\Local\Microsoft\WindowsApps\AutoHotkey.exe`

Why this matters? I'm planning on getting AHK v2 added to Microsoft Store to be used in settings where AHK can't be installed normally (eg restricted corporate environments, which might allow Store apps but ban everything else). Because users can't inspect  `C:\Program Files\WindowsApps` then it would be better if the AppData one also worked. 
Alternatively, perhaps alias support could be added? For example the AHK v1 Store version creates a `AutoHotkey.exe` alias which can be run from Command Prompt directly without a path. This would be the easiest for endusers, since the Interpreter Path could simply be `AutoHotkey.exe`.

**Comment by thqby** [comment]
v2's autohotkey.exe also is a
