### ISSUE TITLE
Debugger only showing Local variables for nested function with Gui OnEvent Callback

### ISSUE THREAD

**Issue by sousvideonlow** [thqby/vscode-autohotkey2-lsp#398]
<img width="536" alt="image" src="https://github.com/thqby/vscode-autohotkey2-lsp/assets/96741275/6db26648-8b22-46f0-bd43-660eba743302">
<img width="546" alt="image" src="https://github.com/thqby/vscode-autohotkey2-lsp/assets/96741275/63f0bc05-9978-43cf-8353-d4e313a4bfcc">

**Comment by thqby** [comment]
This ahk bug. Fixed by v2.0.9.
https://www.autohotkey.com/boards/viewtopic.php?f=14&t=121496
