### ISSUE TITLE
End of continuation section not recognized

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#4]
a := '
		(
			...
		)x'
	b := 1

When the ending quote mark is not immediately after the closing parentheses of the continuation section, it is not recognized. The remainder of the file (if it contains no `)'`) is highlighted as a string. In my real script, I am using a continuation section to make a RegEx pattern more readable:

	v2_qstr := '(?:
		(Join| `
			"(?:[^"`\r\n]|`.)*"
			'(?:[^'`\r\n]|`.)*'
		))'

The start `(?:` and end `)` are purposely outside the continuation section, but still inside the string.

It is an error for a continuation section to lack a closing `)`, and an error for a quoted string to lack an ending quote, but in this case neither the continuation section nor the quote mark are flagged as errors.

Quoted strings cannot span multiple lines on their own. Even if the ending quote isn't recognized, the `)` on the last line ends the continuation section, so the string cannot extend to subsequent lines (unless there are more continuation lines or sections).

Currently an unclosed `"` without a continuation section is correctly marked as an error, but the remainder of the file is also highlighted as a string (up to the next `)"`, even though there is no continuation section).

Another highlighting issue with the code above, although a very minor one, is that `` `\ `` and `` `. `` are highlighted as invalid escape sequences. They aren't escape sequences: the continuation section's `` ` `` option marks all `` ` `` within the section as literal.

**Comment by thqby** [comment]
the continuation section of string end with `` /^\s*\).*[`'"]/ `` ?

**Comment by Lexikos** [comment]
Not quite.

To be clear, it is a continuation section *inside* a string. The continuation section ends with `)`, and the string ends with `'` or `"` (as appropriate) *outside* the continuation section. For most cases, the string will end on the same line.

Continuation sections are a preprocessing feature which can be used with any code.  In my last example, the continuation section is preprocessed to form the following:

    v2_qstr := '(?:"(?:[^"``\r\n]|``.)*"|`'(?:[^`'``\r\n]|``.)*)'

This is parsed as an expression at a later stage.  Notice that the `` ` `` option serves to double up the escape characters, the `'` quote marks are automatically escaped, and the join character `|` is inserted.

When a continuation section *begins inside a quoted string*, it automatically escapes quote marks. For a syntax highlighter, you could say there are two types of continuation sections:
  1. Continuation sections inside quoted strings.
  2. Continuation sections everywhere else.

Type 1 only contains literal text, because every quote mark is interpreted literally; the string can only end outside the continuation section. To the right of the `)`, the normal rules apply: the string ends with the *first unescaped* `'` or `"` matching the symbol that started it, and the string cannot extend to the next line (unless there is another continuation section).

0.6.9 highlights the following incorrectly (c is highlighted as string, but it is not inside a string):

    a := "
	(
		...
	) b " c " d "

Type 2 permits the normal interpretation of quote marks. For example, this produces "b c":

    a :=
    (
    "b" A_Space "c"
    )

You can consider both types of continuation section to be a way of "escaping" any newline characters, preventing the statement, expression or string from ending at the end of the line.
