### ISSUE TITLE
另外一个增强建议：希望 在文件已打开或打开时 才显示警告

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#402]
希望增加一个可设置选项：在文件已打开或打开时才显示警告。
此法同样可以极大化地减少开销。并显著减少视觉负担。但似乎实现起来要比之前的建议中的方式 要简单。
虽然随着V2版本的迭代，虽然喜欢把脚本收集在一起；但是收集的脚本按用途进行文件夹分类了，就不好再按新旧版本来分类。因此有了这个选项，就可以只专注于自己想专注的信息。
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/05e48fa5-3ba4-4b05-9516-9e94a6d898c1)

**Comment by thqby** [comment]
未打开未被引用的文件不会收到诊断

**Comment by PythonYunfei** [comment]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/f382bc3d-abbd-41b2-9ce1-e9baef9ddf12)

图片上显示的诊断，都是未打开但已被插件引用的文件，但这些文件都没有被已打开的文件所`#include`；此时只要打开VSCode，这些诊断都就会显示。
故希望可以的话 能列入计划 加个选项：勾选后，99%~100%的未打开文件都不会收到诊断；即 只要这些未打开的文件没有被已打开的文件`#include`，就不会收到诊断。
