### ISSUE TITLE
Comment area not marked correctly after #Requires

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#405]
Small issue and I'm sure a quick fix.

When putting a comment after a `#Requires` directive, everything between the last character of the directive and the start of the comment is erroneously marked as a comment.  

`#Requires` is the only command I've found where this happens.

https://i.imgur.com/7gvsbbQ.png

As always, thanks so much for maintaining and updating such an essential addon for v2 users.

**Comment by thqby** [comment]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/28240311/3a56efc8-184d-4f1e-aebb-320921156c88)
What do you mean? And the image cannot be displayed.

**Comment by PythonYunfei** [comment]
他可能是说分号前面的某部分变成了注释
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/7412e714-cece-4873-bca7-669e2da22443)

**Comment by RaptorX** [comment]
> And the image cannot be displayed.

Nah, is just that imgur sucks when displaying images that are not in a standard size:

![Screenshot_20231013_081031_Chrome](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/67451c61-df3b-4383-8a8a-24f42c5870fd)


The image was so thin it was blending in with the site 🤣

**Comment by GroggyOtter** [comment]
Thanks thqby :)
I know it's a stupid, small thing, but it was really bugging me.
Can confirm this is fixed.  

I appreciate you and all the work you do :)
