### ISSUE TITLE
Why can't I use Run("Code.exe test.txt") to open a file with vscode during debugging?

### ISSUE THREAD

**Issue by 6Tom** [thqby/vscode-autohotkey2-lsp#406]
For example, this ahk file works fine when run alone. But if you run it with F5 (Debug) in vscode, nothing will happen.

Sorry I'm a beginner, I'm not sure. Are these some special limitations of vscode?

```AutoHotkey
#Requires AutoHotkey v2.0

Run("`"D:\Microsoft VS Code\Code.exe`" D:\test.txt")
```

----------------------------------------
Chinese

比如，这个 ahk 文件单独运行时可以正常工作，但是如果以 F5（调试）的方法运行它，就会发生个寂寞。

原谅我比较菜，我不太清楚，这是 vscode 的一些特殊限制吗？

**Comment by thqby** [comment]
也许是限制，Ctrl+F5(运行脚本)也无法工作，但是通过终端命令行可以工作

**Comment by 6Tom** [comment]
貌似确实有这个限制，甚至由调试拉起的独立 cmd 窗口里，都无法用 vscode 打开文件

```AutoHotkey
#Requires AutoHotkey v2.0

Run("cmd.exe /k start `"`" `"D:\Microsoft VS Code\Code.exe`" D:\test.txt")
```
在这个被打开的 cmd 窗口里输入这种命令也没有作用
```cmd
"D:\Microsoft VS Code\Code.exe" D:\test.txt
```
----------------------------------------

甚至不光是 AutoHotkey，别的语种貌似也这样，连调试 bat 也这样，比如用扩展 [batch-runner](https://marketplace.visualstudio.com/items?itemName=NilsSoderman.batch-runner) 打开独立 cmd 窗口对 bat 文件进行调试，这个命令`"D:\Microsoft VS Code\Code.exe" D:\test.txt`就没有作用，**必须用终端打开才有用**

真是令人费解的限制啊，感谢回复，既然是 vscode 自身的限制，那我就先关闭此问题吧，祝愉快

**Comment by 6Tom** [comment]
貌似确实有这个限制，甚至由调试拉起的独立 cmd 窗口里，都无法用 vscode 打开文件

```AutoHotkey
#Requires AutoHotkey v2.0

Run("cmd.exe /k start `"`" `"D:\Microsoft VS Code\Code.exe`" D:\test.txt")
```
在这个被打开的 cmd 窗口里输入这种命令也没有作用
```cmd
"D:\Microsoft VS Code\Code.exe" D:\test.txt
```
----------------------------------------

甚至不光是 AutoHotkey，别的语种貌似也这样，连调试 bat 也这样，比如用扩展 [batch-runner](https://marketplace.visualstudio.com/items?itemName=NilsSoderman.batch-runner) 打开独立 cmd 窗口对 bat 文件进行调试，这个命令`"D:\Microsoft VS Code\Code.exe" D:\test.txt`就没有作用，**必须用终端打开才有用**

真是令人费解的限制啊，感谢回复，既然是 vscode 自身的限制，那我就先关闭此问题吧，祝愉快

**Comment by 6Tom** [comment]
得，懒是第一生产力，我后来琢磨了个办法，可以做一个专门用于“调试的时候用 vscode 打开指定文件”的函数

比较拙劣，不怎么样，但是是可以工作的，调试的时候用用还行，我把它贴出来😂

```AutoHotkey
; Usage
Open_A_File_With_Vscode_During_Debugging("D:\test.txt")

Open_A_File_With_Vscode_During_Debugging(File_)
{
    Bat_ := "vscode_temp.bat"
    Text_ :=
    ( LTrim
        "chcp 65001
        start `"`" `"D:\Microsoft VS Code\Code.exe`" `"" File_ "`"
        del /f /q `"%~f0`""
    )

    try FileDelete(Bat_)
    FileAppend(Text_, Bat_, "UTF-8-RAW")
    Run("explorer.exe " Bat_)
}
```

**Comment by lstrfwp** [comment]
You can use this to run a file with VS Code during debug mode:
```
ShellRunAsUser("D:\Microsoft VS Code\Code.exe", "D:\test.txt")

; https://www.autohotkey.com/boards/viewtopic.php?p=489732#p489732
ShellRunAsUser(filePath, arguments := "", directory := "", verb := "", show := 1)
{
   static VT_UI4 := 0x13, SWC_DESKTOP := 0x8
   ShellWindows := ComObject("Shell.Application").Windows
   Shell := ShellWindows.Item( ComValue(VT_UI4, SWC_DESKTOP) ).Document.Application
   Shell.ShellExecute(filePath, arguments, directory, verb, show)
}
```

**Comment by 6Tom** [comment]
Thanks a lot, bro! This is really much better. I find that this function is already here: `AutoHotkey\UX\inc\ShellRun.ahk`😂😂😂Thanks for your guidance.

It can also be used to run a target with non admin, even if the current script is running as admin.
