### ISSUE TITLE
Anything starting with "default" inside a switch is syntax highlighted as a case

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#409]
If any variable that starts with `default` is used inside a switch, it's highlighted using `keyword.control.default.ahk2` instead of `variable.other.ahk2`.  
It doesn't have to be the first word, either.  If you assign a value that starts with default, such as `default_value`, it highlights the default part as `keyword.control.default.ahk2` and the rest of the word gets the `meta.body.switch.ahk2` style.

Example: All the `default` words in this picture should be yellow.
![](https://i.imgur.com/ZSu2baE.png)

Thank you for keeping this addon up-to-date and maintained.

**Comment by lstrfwp** [comment]
When semantic highlighting is enabled,  only the variable name `default` itself will be highlighted as `keyword.control.default.ahk2`. Hovering over `=` shows the error: `Missing operand`.

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/110793221/9a9b4417-b854-4781-af98-7bea225804f3)
