### ISSUE TITLE
[改进建议：]希望局部变量this可以改名

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#412]
希望内部static函数中，名为this的局部变量可以改名
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/e69f7d58-e997-49f3-b157-54d9194fcd4c)

**Comment by thqby** [comment]
可以改的

**Comment by PythonYunfei** [comment]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/4e46d008-124d-458c-a16a-dded9ffcf714)
重启了看起来还是不能改。
```
Class CCC{
	__New() {
		static Cll(enum,obj,ags*){
			this.prtSt('ele',vl)
			,this.yieldFn()
		}
	}
}

```

**Comment by thqby** [comment]
这是另一个bug造成的
