### ISSUE TITLE
[2.2.1] Break/Continue must be enclosed by a Loop

### ISSUE THREAD

**Issue by Descolada** [thqby/vscode-autohotkey2-lsp#413]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/16986957/ea0e43f6-d4cd-467f-b899-3e431507bdad)

```
while (1) {
    if (0)
        continue
}
```

Perhaps you'd consider making a testing/alpha version of the extension, so these kinds of bugs could be caught earlier?

**Comment by wilkster** [comment]
I am seeing the same issue with the latest release, but with a "break" in a while loop as well.

**Comment by GroggyOtter** [comment]
To be clear, this error only applies to while-loops.  
Regular loops, parse-loops, for-loops, etc seem unaffected.

![](https://i.imgur.com/xp9X5M9.png)
