### ISSUE TITLE
重命名预览增强建议

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#417]
有时看到某变量时，想知道 该变量在函数中出现了几次。是否只出现一次。
故当按f2时，希望能不用改变量名就可以按shift+enter进行重命名预览。目前没输入新变量名就按shift+enter，会没反应。
另外，重命名预览时，若能显示该变量在对应作用域的数量就更好了。
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/7337860c-1987-40d2-8dee-a0445901dd7d)

**Comment by thqby** [comment]
这不是重命名的功能，这是查找所有引用
