### ISSUE TITLE
F1 to open Help files

### ISSUE THREAD

**Issue by XangelMusic** [thqby/vscode-autohotkey2-lsp#421]
So with VS Code, F1 is already bound to Open Command Palette, but so is Ctrl+Shift+P.

I believe the key can be used to open AutoHotKey Help Files instead.

**Comment by GroggyOtter** [comment]
This is already built into the addon, Xangel.

Click the "Manage" gear > Keyboard shortcuts > type `ahk quick help` in the search bar > rebind to F1.

**Comment by XangelMusic** [comment]
I didn't realise this. Thanks.
