### ISSUE TITLE
Missing JSDoc tags in autocomplete

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#424]
Im not sure if your lexer is the one providing JSDoc autocomplete support but it seems to be missing a few tags that [can be found here](https://jsdoc.app/#block-tags)

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/93ff27d2-08f1-477c-a456-f941e3e6785f)

**Comment by thqby** [comment]
Not all tags are useful, I have selected some commonly used ones.

**Comment by RaptorX** [comment]
I was surprised i didnt see '@member' or others.

Btw do you have styling control on how vscode displays intellisense?

I would like to play a bit with how those are formatted: ex. `@returns {integer}` highlights the type in the comment but not in the intellisense popup. And other minor things.

**Comment by thqby** [comment]
@returns `integer`

Is it highlighted like this?

**Comment by RaptorX** [comment]
no.

this is the comment
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/615f1cfe-429b-43b5-aa7e-6fb785b3e03a)

this is the intellisense popup
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/dbc0f448-92fc-48e0-919a-0bab5da4271f)

something similar happens when referring to parameters types:
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/0963f045-8341-4374-a63b-8dcd906569a2)

in this case the type has some styling (italics) but they blend in too much.
probably having them with a different color (like they are highlighted in the comment) would make it easier to spot.
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/c825fb32-631b-4811-9c93-e0a2c2db6816)

**Comment by thqby** [comment]
can't change their color, just add this background.  `integer`

**Comment by GroggyOtter** [comment]
> Not all tags are useful, I have selected some commonly used ones.

Could you please provide us with a list of tags that are supported?

**Comment by thqby** [comment]
arg, example, link, linkcode, linkplain, overload, param, prop, property, return, returns, type, var

**Comment by GroggyOtter** [comment]
> arg, example, link, linkcode, linkplain, overload, param, prop, property, return, returns, type, var

Thanks again THQBY. 😃
