### ISSUE TITLE
command 'ahk2.run' not found

### ISSUE THREAD

**Issue by 1040536527** [thqby/vscode-autohotkey2-lsp#425]
When I run an AutoHotkey script in VSCode by clicking the "Run" button in the top right corner of the page, it gives me a message saying "command 'ahk2.run' not found". How can I fix this? This issue only occurs on one of my two computers.

**Comment by thqby** [comment]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/28240311/e1f33ba4-0ffd-409b-9a29-bf932a3a1ced)
Are you sure the extension is running?

**Comment by RaptorX** [comment]
I experienced the same today on a clients machine. the extension was running according to this screen.

none of the exported features were working: `ahk.run`, `ahk.debug`, and others

**Comment by qylgy530** [comment]
I had the same problem before, the solution is to update vscode to the latest version

**Comment by thqby** [comment]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/28240311/e0e81d54-5810-4709-a5e7-7d3eca572988)

see output of AutoHotkey2, there may be a hint that the minimum version is required.
