### ISSUE TITLE
#Include tries to resolve relative path but adds script file name

### ISSUE THREAD

**Issue by stavros-k** [thqby/vscode-autohotkey2-lsp#432]
Plugin Version: `v2.2.6`

```
StartApps
├── exits
│   └── exit`.ahk
├── partials
│   ├── Constants.ahk
│   ├── FillAppList.ahk
│   └── WriteExample.ahk
├── StartApps2.ahk
└── StartApps2.ini
```

In StartApps2.ahk

```ahk2
#Include "partials/Constants.ahk"
```

Produce an problem on vs-code
```
'~/auto-start-apps-script/StartApps/StartApps2.ahk/patials/Constants.ahk' not exist
```
Notice the `StartApps2.ahk` in the path!

Note that this works fine when run.
I can get the error to go away by doing `#Include "../partials/Constants.ahk"`
But of course this does not work when run.

Thanks

**Comment by thqby** [comment]
Cannot reproduce the issue.

**Comment by stavros-k** [comment]
Hmm, I've tried on another Windows machine and I can't reproduce there.
Is there any chance that it does not work on Linux? (The extension, I know that AHK does not!)

**Comment by thqby** [comment]
Different path slashes may produce unexpected results.

**Comment by stavros-k** [comment]
Hmm, changed slashes to `\` but same effect :/
I suppose we can close this, since I cant repro in a windows machine. 
Might be something on my system

**Comment by thqby** [comment]
This is handled differently in the internal function uriToFsPath.
