### ISSUE TITLE
Leading spaces not preserved when tabbing.

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#434]
Type: <b>Bug</b>

When modifying the indentation of selected text leading spaces are not preserved (which are usually used for aligning code).

I noticed that if I do the actions of `Tab` or `Shift+Tab` when selecting comments created by the extension, the leading spaces are preserved.

I was wondering if we can do the same for all code, not just comments.

![Recording](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/4af21582-0701-4792-8028-ce00f30d3291)

---

Extension version: 2.2.6
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (19.12GB free)|
|Process Argv|--crash-reporter-id 3e042e59-cb22-4371-968a-6f3e35abe666|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by thqby** [comment]
The above situation has not been handled. This is the default behavior of vscode after adding `autoClosingPairs`.

```
"autoClosingPairs": [
	{
		"open": "/**",
		"close": " */",
		"notIn": [
			"string"
		]
	}
]
```

**Comment by GroggyOtter** [comment]
@RaptorX

Wait, how did you get JSDoc tags to work with backward tabbing???  
The only time my tags maintain correct positioning is if I multi-select each line and tab forward.  

[I can't even backtab b/c that messes up indentation.](https://i.imgur.com/tpyP628.mp4)  

If highlighting the text normally, I [can't tab or backtab](https://i.imgur.com/YHBI3kX.mp4) without messing up indentation.

Help me out here. What setting does that?

**Comment by RaptorX** [comment]
> @RaptorX
> 
> Wait, how did you get JSDoc tags to work with backward tabbing??? The only time my tags maintain correct positioning is if I multi-select each line and tab forward.
> 
> [I can't even backtab b/c that messes up indentation.](https://i.imgur.com/tpyP628.mp4)
> 
> If highlighting the text normally, I [can't tab or backtab](https://i.imgur.com/YHBI3kX.mp4) without messing up indentation.
> 
> Help me out here. What setting does that?

That's exactly why I opened this issue. I cant use tab/shift+tab without losing space indentation.
Then I noticed that if you open a comment with `/**` and use the extension comment, then somehow you dont lose indentation  even when tabbing / shift+tabbing as shown in the gif above.

That lead me to believe that somehow the extension could potentially manage that.

@thqby mentioned something regarding the auto-close setting for the extension but I wasn't lucky with that.

It seems like he found a way to fix the issue, so, Ill be testing soon :)
