### ISSUE TITLE
[Question] 获取环境变量失败, 怎么解决

### ISSUE THREAD

**Issue by doit132** [thqby/vscode-autohotkey2-lsp#436]
# 问题

在启动 vscode 打开一个 ahkv2 项目的时候, 右下角弹出一个错误窗口

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/117004316/fc92f8d5-78af-4d46-be33-bd63b1001816)

下图是在系统环境变量中设置的关于 AHK 的环境变量

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/117004316/3ff6d8dc-5208-4bb8-a89c-4e966c976904)

# 系统信息

版本 Windows 11 专业版
版本 23H2

**Comment by thqby** [comment]
设置项`AutoHotkey2.InterpreterPath`

**Comment by doit132** [comment]
> 设置项 `AutoHotkey2.InterpreterPath`, 该环境变量是 `A_` 开头的 ahk 变量。

什么意思, 没明白, 下图是我的设置

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/117004316/5ce324b7-c984-4550-a6d3-0072a2445354)

**Comment by thqby** [comment]
不用UX目录里的呢

**Comment by doit132** [comment]
> 不用 UX 目录里的呢

我知道问题在哪了, 之前也尝试过不使用UX目录里的, 而是使用 `D:\Programs\AHK_V2\v2\AutoHotkey64.exe`,  结果也会报错

没想到使用 AutoHotkey32.exe 就不会报错了 😂😂 (哭笑不得啊!!!)

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/117004316/15d9b5fd-2c2b-4cbb-9494-2593e40bc4b7)

**Comment by thqby** [comment]
32位系统？

**Comment by doit132** [comment]
> 32 位系统？

我电脑是 64 位的, 所以我不理解为什么 AutoHotkey64.exe 会报错

**Comment by thqby** [comment]
获取环境变量失败？

**Comment by doit132** [comment]
但是 Autohotkey32.exe 不报错, 我只使用了一款安全软件: 火绒, 关掉火绒, 切换到 Autohotkey64.exe 还是报错

**Comment by thqby** [comment]
https://github.com/thqby/vscode-autohotkey2-lsp/blob/main/server/src/server.ts#L231-L240

不管错误， 运行这个有输出吗
