### ISSUE TITLE
New line at end of @param JSDoc tag not working

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#438]
The `@param` JSDoc tag does not respect new-line markdown at the end of the line.  
I ensured there were 2 spaces at the end of the line (as required for a new line).

     * @param {(Integer)} Index - Index to insert value(s).  
     * An index of 0 is the same as `array.Length + 1` and works identical to `Push()`  

Current result.  
New line on @param line is ignored but subsequent new lines are respected:

![Screenshot](https://i.imgur.com/mykHfsS.png)

Expected result:
![Screenshot](https://i.imgur.com/o3DiH22.png)

***

Adding a new paragraph works, but this produces a larger gap than desired.

     * @param {(Integer)} Index - Index to insert value(s).  
     * 
     * An index of 0 is the same as `array.Length + 1` and works identical to `Push()`  

![Screenshot](https://i.imgur.com/7KIcHYp.png)

***

Thank you for all the work you do maintaining the addon.

**Comment by thqby** [comment]
The markdown format is like this. If there is a long continuous line, isn't it interrupted after the line break?

**Comment by GroggyOtter** [comment]
> The markdown format is like this. 

No, this is not expected behavior.  
Please review [new-line formatting for markdown](https://www.markdownguide.org/basic-syntax/#line-breaks).  

2 spaces + new line = Markdown new line  
0-1 spaces + new line = Markdown line continuation

The `@param` tag is the only tag I've found that doesn't respect this markdown formatting rule.  

Also, the `mailto:` URI for the @author tag converts the characters to HTML symbol entities which makes the address unusable unless the receiving mail app knows how to decode it. GMail does not recognize it as a valid address. (Included in screenshot)

![](https://i.imgur.com/6NY45F1.png)

**Comment by thqby** [comment]
> 2 spaces at the end of the line

Oh, I just skipped some information.


> Also, the mailto: URI for the https://github.com/author tag converts the characters to HTML symbol entities which makes the address unusable unless the receiving mail app knows how to decode it.

Has not implemented any related features.
