### ISSUE TITLE
IsSet 出了点毛病

### ISSUE THREAD

**Issue by vvyoko** [thqby/vscode-autohotkey2-lsp#44]
非常感谢大佬的扩展

提个 IsSet  的小问题
首先是不自动补全了
然后是没有函数提示了（提示 保留字'IsSet'不得用作变量名）

然后某些语句中会提示出错了 （实际上正常运行）
比方说下面这样都会提示出错
```
i := IsSet(v)
i := IsSet(v) ? v : 0
Test()
{
    if A_Args.Length
        o := "test"
    return IsSet(o) ? o : ""
}
```

**Comment by vvyoko** [comment]
另外想知道 智能提示
的快捷键是什么，我知道悬停可以触发
第一次输入时可依次触发

可后面再怎么依次查看？
试了CTRL + 左右方向  不行

**Comment by thqby** [comment]
isset不久前修复了
参数提示？ctrl+shift+space
