### ISSUE TITLE
Differences between tooltip/widget headers

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#441]
Currently, there are different rules used for different widget headers (autocomplete and hover widget/calltip).  

When hovering over a method, the hover widget header applies syntax highlighting.  
This looks great.  

![AutoHotkeyU64_TdiETtiofz](https://github.com/thqby/vscode-autohotkey2-lsp/assets/29220773/74a90d52-6b20-4892-83c6-ae9d3e5be70f)

*** 
However, when typing the method, AutoComplete's hover widget doesn't apply syntax highlighting to the header:

![AutoHotkeyU64_VB9t9IBACI](https://github.com/thqby/vscode-autohotkey2-lsp/assets/29220773/d7766edd-5525-4770-9fcc-5784270d1250)

***
When inside the method's parameters, this behavior continues:

![AutoHotkeyU64_bo8LxVAxwo](https://github.com/thqby/vscode-autohotkey2-lsp/assets/29220773/85064c67-89f8-45c1-b89e-1c0ed5079651)

Could you make it so all headers are syntax-highlighted?

***
Aesthetic Request:  
Would you please consider a header style that looks like this?

2-line headers.  
Syntax highlighted.  
Top row: Details about the method/function/object/etc.  
Bottom row: Object inheritance.  

![AutoHotkeyU64_TdiETtiofz 2](https://github.com/thqby/vscode-autohotkey2-lsp/assets/29220773/ebc08b17-83ab-4cc6-b32b-1494f226cbee)

**Comment by thqby** [comment]
The highlighting styles of hover and signature are the default and cannot be modified.
