### ISSUE TITLE
改了类名需要重启vscode

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#442]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/be82abbd-32cc-4991-a2a0-1b8c58e9a726)
目前，改了类名后，需要重启vscode才能在引用该类的其他脚本中更新补全提示和诊断提示。目前，即便重新打开其他脚本的标签页也不行。不知在完全不影响性能的情况下有没办法方便些。
Ps: 毕竟极少改类名，所以远非刚需

**Comment by thqby** [comment]
补全提示是即时更新的，诊断可以用`ahk2.diagnostic.full`命令刷新

**Comment by PythonYunfei** [comment]
好吧，也非刚需

**Comment by PythonYunfei** [comment]
不过目前补全提示和诊断提示都认为 `PropertyRdErrorS`是个类名；那一次，补全提示没有将`PropertyRdErrorS`即时更新成`PrtRdErrS`
