### ISSUE TITLE
Add setting to be able to switch to english

### ISSUE THREAD

**Issue by dmtr99** [thqby/vscode-autohotkey2-lsp#45]
Is it maybe possible to add a setting to be able to switch to english for the syntaxes files?
Great extension.
I could provide these if you create an option to switch.

**Comment by thqby** [comment]
If these files exist, it can automatically load different files according to the vscode language locale without additional settings

**Comment by dmtr99** [comment]
Thanks a lot 😃 

I just used google translate (and with just I mean I used a script to translate it in pieces 😄 .
I added some extra info regarding the Gui.Add... functions to display, but it is far from complete.
Question: do you know by any chance if it is possible to define choices in the typescript files? 

If possible, I would advice to also make it so that the default installation view is in english when the native language is in english, as the Chinese sings scares probably a lot of potentional users. I think this will greatly boost the users.

I also figured out how to modify them in my current extension.
The files where located in: C:\Users\%UserName%\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.0.2\syntaxes

[English Syntaxes - 1.zip](https://github.com/thqby/vscode-autohotkey2-lsp/files/7164240/English.Syntaxes.-.1.zip)
