### ISSUE TITLE
`UnZip()` return value defined as `void`.

### ISSUE THREAD

**Issue by anonymous1184** [thqby/vscode-autohotkey2-lsp#451]
On [ahk2_h.d.ahk:116][1] the return value for `UnZip()` is `void` and should be `Integer`:

<https://hotkeyit.github.io/v2/docs/commands/UnZip.htm>

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/53758552/64e7c735-adb5-4e66-9dc1-71e7a2602ddf)

[1]: https://github.com/thqby/vscode-autohotkey2-lsp/blob/698acb1457b9df590bdc00860110095fe2d30faa/syntaxes/ahk2_h.d.ahk#L116

**Comment by thqby** [comment]
The return value is meaningless because an error is thrown on failure.

**Comment by anonymous1184** [comment]
Awesome! much better that way... silly me didn't test for a fail scenario.

Just a head up: the message of the exceotion/error is prepended by 8 tab characters (I know that is AHK_H, but just in case you want to look at it).

As always, thanks for your time!
