### ISSUE TITLE
[Suggestion:] 希望设置了‘不警告没括号’后 也加个选项

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#452]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/dbc8dcd1-788f-4dd7-af77-d3805661d7f2)
希望能再加个选项，希望当函数或类名和`(`之间存在空格时，给予警告。 因为在没有括号警告的情况下，如果不小心键入了这种空格，那么这种意外的错误可能将非常难以察觉。可能怀疑个遍也不会怀疑到这个错误的头上。目前，插件对于这个的警告依赖于括号警告：
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/e9d438fe-fb66-4f76-b2a4-0ca88c054881)
但感觉这仍然不够，因为文档中有大量的代码是无括号的；如果会复制文档或他人的代码，括号警告是有可能关掉的。
而这种函数/类名后跟 逗号表达式的写法，混淆性极强，基本不会考虑这么写，且有更好的写法替代(只需对最后一个表达式赋予一个变量`v:=`即可)。
所以希望能另加此警告，发生上面情况后，则可以提示"Space between caller and parentheses is extremely rarely used."之类的。

**Comment by GroggyOtter** [comment]
这不可能。
编辑器无法区分表达式旁边的变量名和编写错误的函数之间的区别。

我用谷歌翻译来写这篇文章。
