### ISSUE TITLE
[2.2.8] Minor issue with optional parameters in JSDoc/tooltips

### ISSUE THREAD

**Issue by OpalMonkey** [thqby/vscode-autohotkey2-lsp#453]
A minor bug with JSDocs for optional parameters and their default values. This is based on my understanding of JSDoc syntax, which could be flawed. May be loosely related to a previous issue I submitted #200. The tooltip was working with the correct syntax at that time.

```
/**
 * Test function.
 * @param {any} [one=1] - Using proper JSDoc syntax
 * @param {any} two=2 - Removing the square brackets fixes the
 * tooltip, but is incorrect syntax and breaks highlighting.
 */
Test(one:=1, two:=2) {

}
```

Resulting tooltip. The default value is missing from the first parameter—which has the correct syntax—but shows for the second.
![Screenshot 2023-12-11 052433](https://github.com/thqby/vscode-autohotkey2-lsp/assets/1016179/bb5509ea-c2eb-4219-80ab-70156158c924)

And syntax highlighting of the code:
![Screenshot 2023-12-11 052606](https://github.com/thqby/vscode-autohotkey2-lsp/assets/1016179/cccf397c-4261-40f7-8fe8-2a8d52e4c71e)

**Comment by thqby** [comment]
The second incorrectly identifies `two=2` as the parameter name.

**Comment by OpalMonkey** [comment]
> The second incorrectly identifies `two=2` as the parameter name.

Ah, right, that makes sense now that I'm looking at it closer. Thanks for the comment to draw attention to that. It is much nicer having the proper layout now.

Thank you for the fix, as always! I cannot overstate how helpful this extension—and your consistent maintenance—has been.
