### ISSUE TITLE
JSDoc markdown new line syntax not being respected

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#456]
This is the same problem from [issue #438](https://github.com/thqby/vscode-autohotkey2-lsp/issues/438).

I had previously posted that lines after an `@Param` tag wouldn't render correctly.  
This problem applies to the @Return tag as well

The code:

```
 * @returns {(Object)}  
 * Reference to the object the property was added to.  
```

The result:

![](https://i.imgur.com/nrG2D0t.png)

There are 2 spaces after `@returns {(Object)}  `.  
This should cause a new line but does not.  

Adding 2 new lines does create a new paragraph, but that's not the desired outcome here.

***
After double checking, the `@param` tag is demonstrating this behavior, too.  
The fix for issue #438 has been broken since:

![](https://i.imgur.com/BquhWFt.png)

***  
And other `@tags` like `@throws` don't work correctly.

However, `@description` tags seem to be working correctly on some types like properties and methods 

![](https://i.imgur.com/xNop4Cz.png)

But does not work on something like a class.

![](https://i.imgur.com/MPOBXuV.png)

**Comment by Tomshiii** [comment]
The tooltips seem to no longer render codeblocks at all

v2.2.9;
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/53557479/8f5bcf93-62f6-4b25-919f-7c6fa0deca9c)

v2.2.8;
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/53557479/71722320-4bcb-4a92-b99f-c3fe56f7e46b)

**Comment by thqby** [comment]
you can use `@example`.
```ahk
/**
 * @returns {object}
 * @example
 * ae := winget.AEName()
 */
```
