### ISSUE TITLE
JSDoc @param requires text after variable name

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#457]
Text is **required** to come after a variable name.   
Line breaks are ignored until that text is found, causing a formatting error.  
In this case, a bulleted list is expected to start but fails because the @param line is expecting text after the variable name.

There are 2 spaces after `Option` even though it's not necessary  
(A bullet forces a new line in Markdown)

```
 * @param {(String)} Option  
 * - Hotstring = An activation string and options using the {@link https://www.autohotkey.com/docs/v2/Hotstrings.htm|`::Hotstring`} format.  
```
![](https://i.imgur.com/U6dJmVO.png)

When some text is inserted and the requirement is met, the bulleted list on the next line is respected:

```
 * @param {(String)} Option - Arbitrary text
 * - Hotstring = An activation string and options using the {@link https://www.autohotkey.com/docs/v2/Hotstrings.htm|`::Hotstring`} format.  
```

![](https://i.imgur.com/f5Glkmx.png)

***

**Comment by GroggyOtter** [comment]
Any update on this?

**Comment by lstrfwp** [comment]
It's still an issue. A bullet list doesn't start a new line if nothing follows after the parameter name.
Two spaces can start a new line, but I can't use two spaces because I enable the option: `files.trimTrailingWhitespace": true`.

```
/**
 * @param name
 * - one
 * - two
 * - three
 */
foo(name) {
}
```

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/110793221/18c935ac-7f2c-4ef2-99e7-c6fb31f75fb0)

**Comment by thqby** [comment]
```
/**
 * @param name
 * 
 * - one
 * - two
 * - three
 */
```

**Comment by lstrfwp** [comment]
I was hoping the old behavior could be reverted but this works.

**Comment by thqby** [comment]
What other symbols are used at the beginning of a line?

**Comment by lstrfwp** [comment]
These symbols start a new line in `v2.2.7`
```
/**
 * @param name
 * + one
 * + two
 * + three
 */
foo(name) {
}

/**
 * @param name
 * - one
 * - two
 * - three
 */
foo(name) {
}

/**
 * @param name
 * * one
 * * two
 * * three
 */
foo(name) {
}

/**
 * @param name
 * 1. one
 * 2. two
 * 3. three
 */
foo(name) {
}

/**
 * @param name
 * #### heading
 */
foo(name) {
}

/**
 * @param name
 * > quote
 */
foo(name) {
}

/**
 * @param name
 * ```
 * code
 * ```
 */
foo(name) {
}
```
