### ISSUE TITLE
#Include reference error

### ISSUE THREAD

**Issue by IceWeet** [thqby/vscode-autohotkey2-lsp#459]
Suppose I have a test.ahk file, the content is:
```
#Include A.ahk
#Include B.ahk
```
In this case, I can use the variables in A.ahk directly in B.ahk, and it can run normally, but the editor will report an error, saying that the variable cannot be found

**Comment by thqby** [comment]
After you open `test.ahk`, and then re-open or modify `B.ahk`, this warning will disappear.
