### ISSUE TITLE
Syntax highlighting error with first key of literal objects

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#460]
The first key of a literal object doesn't have correct syntax highlighting when it's on a separate line from the starting curly brace:

On same line as curly brace:

![](https://github.com/thqby/vscode-autohotkey2-lsp/assets/29220773/3fbbaff5-33a8-4451-9afb-1bb0a6931320)

On different line:

![](https://github.com/thqby/vscode-autohotkey2-lsp/assets/29220773/59df3b56-585f-4da5-8d21-446b9084d531)

**Comment by thqby** [comment]
Enable semantic highlighting to provide full syntax highlighting.
