### ISSUE TITLE
[No Issue] A thank you and an offer for an update to the addon

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#463]
Hi, THQBY.

I know I've said it before, but I cannot thank you enough for the time and effort you've put into making and maintaining the v2 addon, including the multiple quick fixes to almost every issue that gets reported.  
It makes coding so much easier.

One thing I really like about the addon is that it comes with IntelliSense calltips.  
It shows the user information about any given item/function/property/method/directive/etc.  

But I noticed that not *everything* had a calltip.  
Or some didn't have the information I wanted.  
Or maybe they lacked return value info.

Starting last spring, I began updating the `ahk2.d.ahk` file with stuff I wanted to see.  
As I did it, your file exposed me to JSDocs and so I dove down that rabbit hole.  
They're pretty great and I'm so glad you included support for them!

Then I found out VS Code supports [markdown formatting](https://www.markdownguide.org/cheat-sheet/), so I started testing what VS Code supports and doesn't support.  
(Side question: do you have control over markdown? Are you able to change things? Like can you enable table borders? Because they currently don't have them and it bugs me.)

After learning about JSDoc tags and markdown support, I decided to start a project where I would rewrite the definition file and heavily apply these things to it.  
This evolved into a kind of goal/project of making something that the entire community could use.  
Ultimately, I was hoping you'd review it and like it enough to use it as the addon's new definition file.  

I've gone through every single function, class, method, and property and applied a general set of JSDoc tags to each one.  
I've ensured every parameter is included and has an assigned type.  
All methods and functions have a return value and assigned type.  
Each gui control now has individualized methods and properties with info that applies only to those controls.  
I've added MANY handwritten examples for the `@example` tag (and I'll continue to add more), trying to keep each example small while still showcasing how to use it in a functional way.  
There's a lot more information in the Reddit link below. Like how I added a RegEx cheat sheet to the bottom of the two regex functions. And I included an InputBox object class in the def file and associated it with the return value of InputBox() so objects returned by InputBox() now show they contain a `value` and `result` property in the autocomplete menu.

While adding all these tags, I applied various markdown formatting to give each calltip more depth, more structure, make it easier to read, and again, to make things more aesthetically pleasing.  
And there are plenty of hyperlinks provided. Each "thing" has a link to its respective online docs (something I've seen multiple people on the subreddit mention they wish the addon had) and a multitude of other links to items related to the current calltip.

[Here's the big Reddit post](https://www.reddit.com/r/AutoHotkey/comments/18wmyt1) I made to showcase a lot of the new things.  
Lots more information there plus pictures and video examples of the changes and updates.  

In addition to the definition file, I also did quite a few updates to the `ahk2.json` file.  
[Video showing a few of the changes](https://i.imgur.com/lQGyN2g.mp4).  
Added quite a few auto-complete features.

As of December, everything was finished and I've been doing revisions, fixing errors, etc.  
This took countless hours and I'm at a point where I'm comfortable showing it to you and getting your impression of it.  
Could you find time to test out these two files and let me know what you think?  

I'll be continuing to update this file, fixing errors, reformatting/rewording things to make them fit better or make more sense, adding functions/classes/methods/properties from future v2 updates (or removing deprecated ones), and maintaining things like `#Requires` version numbering.  

I'm always open to constructive criticism.  
Or discussing changes you might want to implement.

I'm looking forward to hearing back from you.  
If you'd prefer to email, you can reach me [here](groggyotter@gmail.com).

[GitHub Main](https://github.com/GroggyOtter/ahkv2_definition_rewrite)  
[`ahk2.d.ahk`](https://raw.githubusercontent.com/GroggyOtter/ahkv2_definition_rewrite/main/ahk2.d.ahk)  
[`ahk2.json`](https://raw.githubusercontent.com/GroggyOtter/ahkv2_definition_rewrite/main/ahk2.json)  

Cheers, THQBY 🥂

**Comment by RaptorX** [comment]
I will be testing these two files soon! Seems like great work.

I've found myself wanting some additional information about the returned object in some functions (like inputbox) directly in the intellisense tip but never got to adding it myself due to lack of time.

Why not create a pull request?
He can easily merge the changes that way. As far as I've seen thqby is really responsive and open to changes.

**Comment by thqby** [comment]
I want to extract detailed documents directly from the help file, which can reduce the maintenance work of the `.d.ahk` file during ahk updates.

**Comment by GroggyOtter** [comment]
So...no interest at all?  
Did you try it?  
DId you not like it?

**Comment by PythonYunfei** [comment]
> I want to extract detailed documents directly from the help file, which can reduce the maintenance work of the `.d.ahk` file during ahk updates.

Maybe @thqby is right. Documents often change when AHK updates.

**Comment by thqby** [comment]
> So...no interest at all? Did you try it? DId you not like it?

No, I'm too lazy to adapt to the Chinese version of these files. But I will add settings to specify the path of these files.

**Comment by Descolada** [comment]
I'm with @RaptorX here that I'll definitely be testing this out. I've also found myself going to the docs to find info about return values, hotstring options etc. 

@thqby extracting directly from the help file would be easiest to maintain, but probably not best to use. I view the help file as an atlas: a thick book full of dense information, which is useful if you have some time to set aside and dig into it. The tooltip in the extension is more like a pocket guide, containing selected high-value information meant for quick consumption. Following this logic I think a manually crafted mini-helpfile for the extension would offer more value to users, but at the cost of maintainability. The question is whether *you* specifically would need maintain it, as it seems people are willing to just submit pull requests for updates. 
Is adapting the Chinese version of these files technically necessary (that is, would letting it remain unchanged break something)?

I propose an alternative solution: extend your locale support and let the user choose (eg a combobox in the settings). The default could be `en-US` which either uses the current hints or extracted text from help files. Then, additionally there could be `en-ext` which would contain this proposed solution. This could also open up possibilities for translations to other languages.

**Comment by thqby** [comment]
> extracting directly from the help file would be easiest to maintain, but probably not best to use.

I agree.

>

**Comment by thqby** [comment]
@GroggyOtter 
I found a mistake. The first parameter of OSError is ErrorCode.
