### ISSUE TITLE
Debug buttons disabled when reloading VSCode

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#465]
Type: <b>Bug</b>

• Create breaking point
• Run a debug session (vscode-autohotkey-debug)
• Reload VSCode using `Developer: Reload Window` command

### Result

Run and Debug buttons are disabled and can only be re-enabled by switching tabs.

### Notes

This issue is **NOT** present if:
1) Open VSCode from scratch (from explorer or start menu)
2) Dont run a debug session
3) Completely close (clicking the X) and reopening VSCode after debug session.

---

https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/a9a098d3-b112-434d-bf63-8041cecaaafd

---

Extension version: 2.3.0
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (22.59GB free)|
|Process Argv|S:\\Youtube\\Subtitles Search --crash-reporter-id 3e042e59-cb22-4371-968a-6f3e35abe666|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by thqby** [comment]
This seems to be a vscode bug. After `Reload Window`, the enabling condition `resourceScheme == file` of the command is not established.

https://github.com/thqby/vscode-autohotkey2-lsp/blob/585d16f3856f12c68dda5a878ff43892bcd63758/package.json#L328
