### ISSUE TITLE
VSCode Run Script incorrect executable path

### ISSUE THREAD

**Issue by QuarTheDev** [thqby/vscode-autohotkey2-lsp#467]
Hello, the path the Run Script attempts to use is `C:\Program Files\Autohotkey\v2\AutoHotkey.exe`, but it is `C:\Users\Quar\AppData\Local\Programs\AutoHotkey\v2\AutoHotkey64.exe`.

Error preview
![VSCode Error](https://github.com/thqby/vscode-autohotkey2-lsp/assets/70469187/5b02dc66-7f81-4de1-9805-8a407e9279d0)

`C:\Program Files\Autohotkey\v2\AutoHotkey.exe` is not a valid path, the Autohotkey folder does not exist in this location.

Temporary fix: you can change the interpreter with the 'Select AutoHotkey2 Interpreter' button in the bottom left of VSCode, but by default it chooses the aforementioned incorrect path.

Edit: added temp fix

**Comment by PythonYunfei** [comment]
When install AHK as administrator choosing `for all users`, it will be in `C:\Program Files\Autohotkey\v2\AutoHotkey.exe`. Then everything will be right.

**Comment by QuarTheDev** [comment]
Sorry, I forgot about this function, that is correct. Perhaps the extension can run a check with known good directories (starting with Program Files and then trying AppData) to avoid confusion

**Comment by PythonYunfei** [comment]
> Sorry, I forgot about this function, that is correct. Perhaps the extension can run a check with known good directories (starting with Program Files and then trying AppData) to avoid confusion

There are two extensions. Another is for debug.
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/2b8653f1-b6a9-4186-a58d-c72ef6e2697e)
By default, it also cannot support the feature you mentioned. The default path is also `C:\Program Files\Autohotkey\v2\AutoHotkey.exe`.
