### ISSUE TITLE
[增强建议：] 希望增加注释折叠功能

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#471]
目前Vscode自带的那三个命令均无法折叠`AHK`中的注释或块注释：
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/aafa6ba6-9dad-4fd4-a44f-e2d4f2843a02)

故希望增加两个命令：折叠所有整行的单行注释、或折叠所有整行的块注释。
这样，在不需要看注释、需要快速浏览代码的时候，会更加方便。

**Comment by thqby** [comment]
测试了第一个可以折叠

**Comment by PythonYunfei** [comment]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47076058/7bf1a458-06d9-4d83-b4f0-d00e27d71a56)
之前这样的块注释无法折叠，我所以我以为都无法折叠。现在发现，多行块注释用自带的命令是可以折叠的。
所以现在，我希望多行的连续的单行注释也能折叠。
