### ISSUE TITLE
Autocomplete doesn't work for keyword "Static" inside classes

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#474]
Autcomplete from the ahk2.json file doesn't work with the keyword `static` while inside of a class. 
It only works inside of a function definition.

```
{
	"body": "static ${1:name}${2| := , += , -= |}${3:Value}",
	"description": "A static variable or function persists through the life of the script and does not get erased at the end of a function call.",
	"prefix": "static"
},
```

https://github.com/thqby/vscode-autohotkey2-lsp/assets/29220773/2b54d88b-e0d3-4faf-af7d-5bbac58daef5

**Comment by thqby** [comment]
There are only two keywords in the class, which are hard-coded.

**Comment by GroggyOtter** [comment]
The keyword static works inside functions and not inside classes.  

Static is a valid keyword in both contexts and should populate inside both functions and classes.

**Comment by GroggyOtter** [comment]
Thank you.
