### ISSUE TITLE
两个格式化问题

### ISSUE THREAD

**Issue by Frozen1084** [thqby/vscode-autohotkey2-lsp#475]
1，每次格式化的效果如图
![1](https://github.com/thqby/vscode-autohotkey2-lsp/assets/88446922/85de3ce8-db19-4842-aff9-0df53573dc9f)

触发条件： 1，行前有制表符；2，在函数参数内有多行的 "(`n)"

2，能否优化多行对象定义时的格式化效果。当前效果：
```
	t := { a: 1, b:
		[{ a: 1, b: 2 }, {
			a: 1,
			b: 2
		}, {
			a: 1,
			b: 2
		}]
	}
````

希望呈现类似 .tojson(4)的效果：
```
{
    "a": 1,
    "b": [
        {
            "a": 1,
            "b": 2
        },
        {
            "a": 1,
            "b": 2
        },
        {
            "a": 1,
            "b": 2
        }
    ]
}
```

**Comment by thqby** [comment]
第一个重复不出来

**Comment by Frozen1084** [comment]
1的代码：
```
	a := 1

	b := Map("a", "
	(
	aaa
	)")

	MsgBox
```
测试方法是用AutoHotkey向它发送 "!+f"


========

AutoHotkey v2 Language Support v2.3.2

vsc:
版本: 1.85.1
提交: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
日期: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by thqby** [comment]
第二个格式太多了，有不展开的，有展开的，有展开部分的

**Comment by thqby** [comment]
array_style和object_style调整样式
