### ISSUE TITLE
Request: When passing a GUI to a for-loop, have the values be marked as `Gui.Control` type.

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#486]
Would you please consider updating the addon so when a gui object is passed to a for-loop, it treats the provided values as `Gui.Control` objects.  
This would provide the proper methods and properties to those values when used in the for-loops code block.

Example:
```
goo := Gui()
con := goo.AddText()
con.
```
![Accessing con produces the expected autocomplete widget with properties and methods.](https://i.imgur.com/BdB8jAD.png)

However, when the controls are gotten from the for-loop, the addon assigns no "type" to them, preventing autocomplete from activating and populating with the properties and methods of the `Gui.Control` class:
```
goo := Gui()
goo.AddText()
for con in goo
    con.
```
![Fails to produce any type of autocomplete widget.](https://i.imgur.com/JSod0CU.png)  

Obviously, it would be difficult to determine each individual control's type, such as `Gui.Button` or `Gui.Edit`, but they could blanket-labeled as `Gui.Control` types, thus providing the basic properties and methods that all gui controls possess.

**Comment by thqby** [comment]
This statement is not supported at present. You can mark the variable type.
```
goo := Gui()
goo.AddText()
/** @type {Gui.Control} */
con := unset
for con in goo
    con.
```

**Comment by thqby** [comment]
https://github.com/thqby/vscode-autohotkey2-lsp/blob/d16848c3e679edf4b0f1d80202e292fa4d5e0a7f/syntaxes/ahk2.d.ahk#L3537-L3610

See `ahk2.d.ahk` for changes.
