### ISSUE TITLE
hover failed with message issue

### ISSUE THREAD

**Issue by wilkster** [thqby/vscode-autohotkey2-lsp#488]
Since 2.3.6 I have been getting a lot of these messages. 2.3.5 has been rock solid.
[Error - 7:13:41 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Invalid regular expression: /^\s*@(var)\s+{(.*[^\])?}\s+hout(\s|$)/im: Unterminated character class
  Code: -32603 
[Error - 7:14:47 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Invalid regular expression: /^\s*@(var)\s+{(.*[^\])?}\s+guiSnips(\s|$)/im: Unterminated character class
  Code: -32603 

[Error - 7:21:34 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Invalid regular expression: /^\s*@(var)\s+{(.*[^\])?}\s+hOut(\s|$)/im: Unterminated character class
  Code: -32603 
[Error - 7:22:33 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Invalid regular expression: /^\s*@(var)\s+{(.*[^\])?}\s+hOut(\s|$)/im: Unterminated character class
  Code: -32603 
[Error - 7:22:43 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Invalid regular expression: /^\s*@(var)\s+{(.*[^\])?}\s+hOut(\s|$)/im: Unterminated character class
  Code: -32603

**Comment by SaifAqqad** [comment]
Having a similar issue as well (`Request textDocument/completion failed`), it seems to happen whenever the annotation description contains an inline `@link` tag.

I think there's also an issue with regex for the `@type` tag in the hover window

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/47293197/813982ff-7a99-4797-9f91-bf6347b3e082)

Can be repro with [this file](https://github.com/SaifAqqad/VMR.ahk/blob/v2/src/VMR.ahk#L48), [vscode.dev link](https://vscode.dev/github/SaifAqqad/VMR.ahk/blob/v2/src/VMR.ahk#L48)
