### ISSUE TITLE
Type maybe not VarRef error with 3.2.8 update

### ISSUE THREAD

**Issue by wilkster** [thqby/vscode-autohotkey2-lsp#491]
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/1711579/70732ba0-1473-451c-b2aa-3636c5b9d48b)
I am seeing the error above for optional parameters starting with 3.2.8. Is anyone else seeing this?

**Comment by GroggyOtter** [comment]
Can confirm.

![Code_w1y8wNssNz](https://github.com/thqby/vscode-autohotkey2-lsp/assets/29220773/1c481c9a-18f4-4f44-9924-f0cf8fd84d3c)

Seems to happen with any optional VarRef parameter that's left empty.
