### ISSUE TITLE
Hotkey + Down marked as problem

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#492]
Type: <b>Bug</b>

Im getting some problems marked when using they `Down` keyword with hotkeys.

```
Lbutton Down::
{

}

LButton Up::
{

}

Shift Down::
{
	
}
```

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/874dd098-f9ea-4002-b7b0-229bf0ec0950)

---

Extension version: 2.3.8
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (19.29GB free)|
|Process Argv|--crash-reporter-id 3e042e59-cb22-4371-968a-6f3e35abe666|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30991133
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470

```

</details>

**Comment by RaptorX** [comment]
The weird thing is that even when I install older versions I get the same problem...
was that a problem all the time?

I hadnt notice that tbh.

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/c03f5f44-b330-411a-9c19-f95342dff7c9)

**Comment by thqby** [comment]
`Lbutton Down::` is not a hotkey line. What do you expect?

`Unexpected ":"` will also prompt you if you run it.

**Comment by RaptorX** [comment]
Im just stupid, sorry
