### ISSUE TITLE
[Help] Settings for Autohotkey v1

### ISSUE THREAD

**Issue by pidgeon777** [thqby/vscode-autohotkey2-lsp#494]
Hello, I had a look at the readme file but I'm having issues with configuring the LSP.

Actually I tried to run it on V1 scripts, and the LSP itself started.

However, when working with V1 scripts:

- Should I use the V1 or V2 AHK executable?
- Should I add some directives to the script header?
- Should I configure the LSP in a specific way?

Or, more in general, it is possible to configure the LSP to work with V1 scripts so that V2 errors are not generated?

My editor is Neovim, if that matters.

Thanks for your help!

**Comment by thqby** [comment]
This extension only supports ahk v2.0+.

**Comment by pidgeon777** [comment]
Ok, thanks for the clarifications 👍.
