### ISSUE TITLE
Ctrl+F1 Open V1 Help file

### ISSUE THREAD

**Issue by Xeo786** [thqby/vscode-autohotkey2-lsp#498]
Type: <b>Bug</b>

I installed the V1 First then installed the V2 and now everytime When I presses Ctrl+F1 it opens the V1 file

Extension version: 2.4.1
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (20.02GB free)|
|Process Argv|S:\\ScreenScale --crash-reporter-id b21eb880-a99b-4b14-a020-77af67742cbd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by RaptorX** [comment]
If you use the UX > install-version.ahk script, this bug is "fixed".

But i guess anybody who has installed v1 first will have this issue.

**Comment by thqby** [comment]
Unable to reproduce this issue, check the extension's setting `AutoHotkey2.InterpreterPath` first.

**Comment by RaptorX** [comment]
I checked with him and another person.
interpreter path was correct.

both my teammates had the same issue as described. both installed v1 first. weird.

I'll try and reproduce on a sandbox.

**Comment by thqby** [comment]
> interpreter path was correct.

What is set? and the directory structure.
Whether it conflicts with other extensions?

It still can't be reproduced.

**Comment by thqby** [comment]
> interpreter path was correct.

What is set? and the directory structure.
Whether it conflicts with other extensions?

It still can't be reproduced.

**Comment by thqby** [comment]
@Xeo786 Can you provide more detailed information?
