### ISSUE TITLE
[v2.4.1] first letter is not removed when selecting JSDoc enum

### ISSUE THREAD

**Issue by lstrfwp** [thqby/vscode-autohotkey2-lsp#499]
```
/**
 * @param {"apple"|"orange"|"pear"} fruit
 */
foo(fruit) {

}
```

If a word is selected from the drop down menu, the first letter is appended to the end of the replacement.

https://github.com/thqby/vscode-autohotkey2-lsp/assets/110793221/1cd8a44f-3334-40bb-bb42-33ecfe18efc2

**Comment by thqby** [comment]
Your caret is behaving erratically, shifting one digit to the left when typing, which is causing this issue.

**Comment by marium0505** [comment]
This seem to happen with js doc completion in general, whether they come from the extension such as ComObject, BlockInput, CoordMode or they're JS Doc made by the user, such as the foo(fruit) example above. 

If you've already written `ComObject("htm")` and then pick `htmlfile `and hits Tab, it becomes `ComObject("htmlfileh")`
If you've already written `ComObject("it")` and then pick `iTunes.Application.1` and hits Tab, it becomes `ComObject("iTunes.Application.1i")`

It is especially clear with the following examples:
`ComObject("Win")` => Pick `WinHttp.WinHttpRequest.5.1` => `ComObject("WinHttp.WinHttpRequest.5.1w")`
If you instead write `ComObject("http")` and then again pick `WinHttp.WinHttpRequest.5.1`, it becomes `ComObject("WinHttp.WinHttpRequest.5.1h")`

Seems like this started with the current version (2.4.1), before that it worked/works fine.
