### ISSUE TITLE
Highlighting of `this` in property getter

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#50]
`this` is not highlighted on the second line:
```AutoHotkey
class X {
    static Y[z] => this.A[1]
            || this.B[1] := C
}
```
but without `[z]`, `this` is highlighted correctly:
```AutoHotkey
class X {
    static Y => this.A[z]
            || this.B[z] := C
}
```

**Comment by thqby** [comment]
Format 1 may also be followed by the block. such as
```
static x[y,
  z] {   ; \w+\[
  if (1) {
    ...
  }
}
```
Textmate does not support backtracking to previous lines, so continuation lines in the format 1 are broken, and the continuation line that operator at the end of the line is supported.

In the following format, the two cases are distinguishable. `x =>` and `x {`
End conditions can be treated differently.

**Comment by Lexikos** [comment]
I am not looking for workarounds - I'm not going to write my code based on whether your extension highlights `this`.

Why do you need to differentiate between these cases? 99% of the time, if the variable `this` is inside a class body, it refers to the hidden `this` parameter.

In my scripts, you'd get it right more often by highlighting `this` unconditionally. I don't really care whether it's highlighted, but having it highlighted sometimes and then sometimes not without apparent reason has been bugging me.

I figured out another cause - it isn't highlighted inside `switch`.
```AutoHotkey
class A {
    B() {
        switch {
        case 1:
            return this
        }
    }
}
```

> Textmate does not support backtracking 

It gets highlighted in methods, and not inside global functions, or inside nested functions when `this` has been explicitly declared local. Lack of backtracking support apparently doesn't prevent that; why should it matter at all?

What happens when the extension fails to detect the line continuation? Does it revert to assuming the expression resides directly in the class body? If so, it **should still be highlighted**. This should also be highlighted, and is not:
```AutoHotkey
class A {
    a := 1
    b := this.a
}
```
`this` is also valid for `static` initializers (in v2); it refers to the class itself.

**Comment by thqby** [comment]
The last two are semantic tokens overwriting TextMate, This is a bug with semanticTokensProvider, and it can be fixed.

```
Y[z] => this.A[1]
            || this.B[1] := C
```
And this one, just looking at the first row, you don't know if it's continuous, so I'm not sure it's going to work out perfectly and not conflict with the other cases. After all, the Textmate Highlighting is based on regex.
