### ISSUE TITLE
#include sometimes gives Invalid file path error

### ISSUE THREAD

**Issue by marium0505** [thqby/vscode-autohotkey2-lsp#500]
I've come across another issue which randomly seems to occur. 

`#include` Sometimes gives the Invalid file path error. 
As seen below:
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/1466933/879a60fa-cf0c-461a-b242-91e5eb1647b8)

VS Code gives the mentioned error, but the stuff in the file is clearly included, which is clear from the console.  
The file structure is as it should be, with the included file being in Lib folder inside the A_ScriptDir "\Lib\"  ; Local library folder.

The lines shown in the photo are the only lines of the including/current file. 
The file being included is https://github.com/G33kDude/cJson.ahk/blob/v2/Dist/JSON.ahk (but with the classname changed to cJson).

When I copy the exact same files with the exact same file/folder structure, no error is given.

**Comment by thqby** [comment]
Sometimes the extension can't correctly identify the directory where a_scriptdir is located, and this error will occur. You can introduce the library through a relative path or set `AutoHotkey2.WorkingDirs`

**Comment by marium0505** [comment]
Okey, I think I'm closing this for the time being. 

Though, one question before I close it. The `Auto Hotkey2: Auto Lib Include` setting, how about making the setting a checkbox based setting instead of a dropdown so that users can pick and choose the combination they want? I would like to combine Local and User, but you can only combine all or just User and Standard.

I can make a new issue for that if you want.

**Comment by thqby** [comment]
Since AHK does not have an official standard library, both the standard library and user library are managed by users themselves. For convenience, they can be merged. Would you like to place libraries separately in these two directories?

**Comment by thqby** [comment]
command `ahk2.setscriptdir` can reset scriptdir.
