### ISSUE TITLE
Pls consider adding extension to Open VSX Repository

### ISSUE THREAD

**Issue by DavidBevi** [thqby/vscode-autohotkey2-lsp#501]
https://open-vsx.org/?search=thqby
I use VSCodium (a Microsoft-less fork of VSCode) which has said repository instead of Microsoft's one.
It would be cool if you add your extension in said repository 😎

**Comment by thqby** [comment]
https://github.com/VSCodium/vscodium/blob/master/docs/index.md#how-to-use-the-vs-code-marketplace

It seems you can install it directly from the vscode marketplace.

**Comment by DavidBevi** [comment]
Yes, following your link ([2 paragraphs above](https://github.com/VSCodium/vscodium/blob/master/docs/index.md#how-to-use-a-different-extension-gallery)) I was able to install your extension on VSCodium. Thanks :smiley:
