### ISSUE TITLE
tab autocomplete for ComObject() appends first already written character to final string (2.4.1)

### ISSUE THREAD

**Issue by marium0505** [thqby/vscode-autohotkey2-lsp#502]
Hey,

I've noticed that when using tab autocomplete for ComObject() and when you've already written one or more characters , the first already written character ends up at the end of the picked suggestion. 

In other words...
If you've already written `ComObject("htm")` and then pick `htmlfile `and hits Tab, it becomes `ComObject("htmlfileh")`
If you've already written `ComObject("it")` and then pick `iTunes.Application.1` and hits Tab, it becomes `ComObject("iTunes.Application.1i")`

It is especially clear with the following examples:
`ComObject("Win")` => Pick `WinHttp.WinHttpRequest.5.1` => `ComObject("WinHttp.WinHttpRequest.5.1w")`
If you instead write `ComObject("http")` and then again pick `WinHttp.WinHttpRequest.5.1`, it becomes `ComObject("WinHttp.WinHttpRequest.5.1h")`

Seems like this started with the current version (2.4.1), before that it worked/works fine.

**Comment by RaptorX** [comment]
I think this is related to #499.

**Comment by marium0505** [comment]
@RaptorX Oh, I didn't notice that issue for some reason. 

Closing this as a duplicate and instead commenting on that one.
