### ISSUE TITLE
Suggestions for improving debugger integration

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#504]
Currently with default settings and an .ahk file open, pressing F5 will activate the `ahk2.debug` command. This is useful because it allows debugging without specifically adding a launch configuration to the workspace. In other words, it is most useful **when there are no launch configurations**.

However, when I have a launch configuration configured and selected, I expect that launch configuration to be used. It is used if I press F5 when any other file type is active.

Unfortunately the user interface has conflicting visual cues:
  - Run and debug has a button with the tooltip "Start Debugging (F5)".
  - The extension has a toolbar with "Debug Script (F5)".

At first it was also unexpected that these two buttons do different things. I understand it now, but do not think it is ideal.

Currently, it seems that Debug Script (`ahk2.debug`) creates its own launch configuration referencing the currently selected interpreter, but all default settings for the debugger. With a launch configuration, a user can [set custom debugger options](https://github.com/zero-plusplus/vscode-autohotkey-debug/wiki/Launch-Mode) and enable useful features like [debug directives](https://github.com/zero-plusplus/vscode-autohotkey-debug/wiki/Debug-directive), but all of that is ignored if the user presses F5 or clicks the debug button on the toolbar of this extension.

---

**Suggestion 1:** Consider adding `!debuggersAvailable` to the `when` condition of the `ahk2.debug` keybinding. This would prevent the default keybinding from overriding the standard launch method when a launch configuration is present.

Note that if the user "removes" the keybinding via the GUI, an entry like this is added to `keybindings.json`:
```
    {
        "key": "f5",
        "command": "-ahk2.debug",
        "when": "shellExecutionSupported && !inDebugMode && editorLangId == 'ahk2'"
    },
```
This appears to be an automatic combination of the [command's enablement condition](https://github.com/thqby/vscode-autohotkey2-lsp/blob/ee80162e628403de356fbd696f602e4033ed6fe1/package.json#L348-L349
) `editorLangId == ahk2 && shellExecutionSupported` and the [keybinding's when condition](https://github.com/thqby/vscode-autohotkey2-lsp/blob/ee80162e628403de356fbd696f602e4033ed6fe1/package.json#L529-L531) `editorLangId == ahk2 && !isWeb && !inDebugMode`, with `!isWeb` presumably "optimized" out.

The documentation doesn't say how `when` is interpreted for removal rules, but my experience is that it is **not** evaluated the same way. Instead, it seems that `when` must be either omitted or exactly match the `when` shown in the GUI. For example, I previously disabled the keybinding of an earlier version via the GUI, and it added something like this to my keybindings:
```
    {
        "key": "f5",
        "command": "-ahk2.debug",
        "when": "!inDebugMode && editorLangId == ahk2 && !isWeb && resourceScheme == file"
    },
```
*This does not work.* In other words, if a user disables the keybinding but [the condition changes](https://github.com/thqby/vscode-autohotkey2-lsp/commit/6052285b9e6866bab7e8625e539602579ad56ef6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L333-R333) (as it did in commit 6052285), the keybinding gets re-enabled. This caused me quite a bit of confusion (zero-plusplus/vscode-autohotkey-debug#323).

However, if a user is aware of the issue, he can disable and redefine the keybinding like this:
```
    {
        "key": "f5",
        "command": "-ahk2.debug",
    },
    {
        "key": "f5",
        "command": "ahk2.debug",
        "when": "!inDebugMode && !debuggersAvailable && editorLangId == 'ahk2' && shellExecutionSupported"
    },
```

---

**Suggestion 2:** Consider adding some way to inject the path of the selected interpreter into a launch configuration. I am guessing there is no direct way for the extension to define a `${variable}` for use in a launch configuration, but I think it could be half done by defining a command which returns the path. The other half would be done by an [input variable](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables) which refers to the command.

---

**Suggestion 3:** If it is possible, consider an option to make the Debug Script button use the currently selected launch configuration if it is `"type": "autohotkey"`. (I suggest that condition only because the button says "Debug *Script*".)

However, note that even if the launch configuration is not ostensibly an AutoHotkey one, and even if the current file is an .ahk file and the launch configuration does not reference that file, it is possible that the user is wanting to use the selected launch configuration and *not* run the script through your extension. For instance, AutoHotkey itself can be debugged in a C++ debugger in VS Code. In some workspaces, I also use configurations where a specific file is launched, or a custom tool or command line is executed; and I don't want to execute the currently active script file (it could be just a library).

---

**Suggestion 4:** If it is possible, consider adding a way to configure options of the launch configuration which `ahk2.debug` presumably creates.

**Comment by thqby** [comment]
Suggestion 1 is not feasible, whether the launch configuration exists does not affect `debuggersAvailable`.

Suggestion 2, the variable `${config:AutoHotkey2.InterpreterPath}` can do the same thing.

Suggestion 3, since we do not know which configuration is currently selected, if there are multiple configurations, should the selection box pop up or default to the first one?

@Lexikos

**Comment by RaptorX** [comment]
> Suggestion 3, since we do not know which configuration is currently selected, if there are multiple configurations, should the selection box pop up or default to the first one?

I'll chime in and say: I personally don't like getting random pop ups unless they are very important. I think defaulting to the first one might be good enough for most situations. If I really care about it I would go and change it manually.
