### ISSUE TITLE
Parameter suggestion not working after update when parenthesis Call not used

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#506]
Type: <b>Bug</b>

• Call a function without parenthesis

### Expected
- Intellisense parameter suggestion and info should pop up

### Result
- Intellisense doesnt show up

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/2ae17843-2ad2-47f2-abb3-037a1ab43cfb)

### Notes

When making a call with the parenthesis the extension behaves as expected.

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/e8c89ebd-5b5e-464c-a7d8-24d0e1f8c92a)

### Code examples

Parameter suggestions arent shown when pressing the comma as before
```
Msgbox 'This is a test',
```

Parameters are suggested as soon as the parenthesis are opened and on each comma after that
```
Msgbox('this is a test',
```

### Additional Wish

Hitting space after the Function name should trigger the Intellisense the same as when you hit the open parenthesis... i.e.:

```
; the intellisense window should open:
Msgbox( ; after hitting opening parenthesis as usual
Msgbox ; after hitting space. This has never worked but i think it would be good to have
```

---

Extension version: 2.4.2
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.22GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\OneDrive\\Desktop\\Format Converter --crash-reporter-id 3e042e59-cb22-4371-968a-6f3e35abe666|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideot:31016892
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31022790

```

</details>

**Comment by thqby** [comment]
This is intentional, space is often used and cause a lot of ineffective triggers.

**Comment by RaptorX** [comment]
Just to clarify, If you typed a command and then pressed a comma the Intellisense window would pop up which is now broken and doesnt happen.

For example typing this opened the Intellisense before after pressing the `,`
```
Msgbox 'This is a test',
```

> This is intentional, space is often used and cause a lot of ineffective triggers.

I would have thought that when you press space you would check if the previous word is a command or not... if it isn't, do nothing.  Probably Im not understanding what are the "ineffective triggers" you are referring to.

**Comment by thqby** [comment]
> Just to clarify, If you typed a command and then pressed a comma the Intellisense window would pop up which is now broken and doesnt happen.

Every time you type a trigger character, it checks to see if it is a function call. This is the default behavior.

> ineffective triggers

When the number of function calls is the majority.

**Comment by RaptorX** [comment]
> When triggered, most cases are not function calls.

Is there a big overhead to something like:

```
if !match(prev_word, command_regex)
    return
    
; code when it is a command
````

I think is totally accetable code (even when the trigger is a space) unless im missing something here.

**Comment by thqby** [comment]
> Is there a big overhead to something like:

I think the overhead of process communication is greater than the overhead of detection.
