### ISSUE TITLE
2.4.2 broke my launch configurations

### ISSUE THREAD

**Issue by greatwhitepine** [thqby/vscode-autohotkey2-lsp#507]
This no longer works in 2.4.2 when I click 'Start Debugging'. It just tries to execute the currently open file. Rollback to 2.4.1 fixes the issue.

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "test",
            "type": "autohotkey",
            "request": "launch",
            "runtime": "C:/Program Files/Autohotkey/v2/AutoHotkey64.exe",
            "program": "C:/dev/ahk/IpTVScanner/IpTVScanner/bin/run_tests.ahk",
            "args": [ "asdfasdf" ]
        }

    ]
}`

**Comment by Lexikos** [comment]
The toolbar has a button labeled `Debug Script (F5)`, which I think belongs to this extension. For me, this launches using the correct `runtime` and `program` from the current launch configuration. I think it was ignoring the current launch configuration before, as explained in #504. This is good. If I re-enable the F5 keybinding belonging to this extension, it works as it should.

`Start Debugging (F5)` in the `Run` menu now prints a message showing that it is using the currently selected launch configuration, and has the correct `runtime`, but incorrect `program`. (I think it did not do this before; I think it just launched the debugger without involving this LSP extension at all.) `>` on the `Run and Debug` sidebar does the same thing.

Some of my workspaces had a `Debug AHK Script (F5)` button which did not behave consistently with the other options, but I found that it belongs to the AutoHotkey Plus Plus extension.

**Comment by Lexikos** [comment]
Even though I changed launch configurations repeatedly before posting the above comment, and it was behaving as described, now `Debug Script (F5)` is not using the currently selected launch configuration. I do not know what changed. (I know thqby said he "could not find the api to get the currently selected configuration".)

Sometimes it uses the first configuration, and sometimes it uses "AutoHotkey Debug", which is not one of my configurations.

**Comment by thqby** [comment]
Currently, the debug session starts with the extension's debug options, and looks for the setting in launch.json that best matches it and overrides the debug options.

The above issue is because the object values are not compared by value and do not match the settings in `launch.json`.

**Comment by greatwhitepine** [comment]
Uhm, I tried F5 and click on the actual icon (play button) that has always worked for me no matter your version #. I absolutely had to have the main file open and focused in the editor for file to run because Visual Studio is completely ignoring my working configuration.

How do I make my configuration work with 2.4.2? Full steps would be nice. I'm not really into troubleshooting stuff that has been working for over a year.

**Comment by greatwhitepine** [comment]
Ah, I see 2.4.3. TYVM! I almost lost it when I couldn't figure this out! :-)
