### ISSUE TITLE
A_TimeSincePriorHotkey, A_TimeSinceThisHotkey empty instead of -1

### ISSUE THREAD

**Issue by Cobracrystal** [thqby/vscode-autohotkey2-lsp#508]
Description states
> The number of milliseconds that have elapsed since A_ThisHotkey was pressed. If A_ThisHotkey is empty, the value of this variable is -1.
> The number of milliseconds that have elapsed since A_PriorHotkey was pressed. If A_PriorHotkey is empty, the value of this variable is -1.

should be
"The number of milliseconds that have elapsed since A_ThisHotkey was pressed. It will be blank whenever A_ThisHotkey is blank."
and
"The number of milliseconds that have elapsed since A_PriorHotkey was pressed. It will be blank whenever A_PriorHotkey is blank."
from [ahkv2 docs](https://www.autohotkey.com/docs/v2/Variables.htm#TimeSinceThisHotkey)

**Comment by RaptorX** [comment]
confirmed they are blank on `2.0.13`

**Comment by RaptorX** [comment]
Confirmed they return blank on `2.0.13`
