### ISSUE TITLE
Request: Prevent cycled parameter hint from resetting

### ISSUE THREAD

**Issue by lstrfwp** [thqby/vscode-autohotkey2-lsp#510]
When multiple parameter hints are available, the parameter hint resets to the first one when typing.
For example, if I type `StrGet(`, press down to show parameter hint 2/2, it resets the parameter hint to 1/2 when I type.
Is it possible to prevent the parameter hint from resetting to 1/x when typing?

https://github.com/thqby/vscode-autohotkey2-lsp/assets/110793221/498cbbe6-5ab1-498f-9481-cb3679808c3c

**Comment by thqby** [comment]
It was like this a few days before I remembered it, but now I can't reproduce it.
