### ISSUE TITLE
Launch configurations configured in settings.json are erroneously modified

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#511]
With only helsmy/autohotkey-debug-adapter and vscode-autohotkey2-lsp enabled and a launch configuration in **settings.json**, the "port" setting in the launch configuration is ignored. Furthermore, it is overridden with the value "9002-9010", which is not valid for this debug adapter, and therefore causes an error message.
```
    "launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Test",
                "type": "ahkdbg",
                "request": "launch",
                "program": "${file}",
                "AhkExecutable": "C:\\Program Files\\AutoHotkey\\v2\\AutoHotkey64.exe",
                "port": 9005
            }
        ]
    }
```
The launch configuration works correctly if either it is moved to **launch.json** or vscode-autohotkey2-lsp is disabled.

In #507, @thqby wrote:

> Currently, the debug session starts with the extension's debug options, and looks for the setting in launch.json that best matches it and overrides the debug options.

I do not understand why you are overriding options of an existing launch configuration.

**Comment by thqby** [comment]
Can't reproduce the issue. May not match to the existence of debugging options?

what's your `AutoHotkey2.DebugConfiguration`?

**Comment by thqby** [comment]
@Lexikos

**Comment by Lexikos** [comment]
> what's your `AutoHotkey2.DebugConfiguration`?

User settings.json contains exactly what I posted plus surrounding braces, nothing else. The workspace settings are empty. There is a launch.json, but configurations is an empty array. The only addition I didn't mention is that vscode-autohotkey-debug is installed but disabled.

> May not match to the existence of debugging options?

I don't know what this means.

**Comment by thqby** [comment]
> There is a launch.json, but configurations is an empty array. 

Remove this empty array and it will work properly.
