### ISSUE TITLE
v2.4.4 breaks code format indentation

### ISSUE THREAD

**Issue by jingyu9575** [thqby/vscode-autohotkey2-lsp#512]
With the following code:
```
if (a) {
	if (b) {
		if (c) {
		}
	}
}
```
v2.4.4 formats it to:
```
if (a) {
	if (b) {
	if (c) {
	}
}
}
```
v2.4.3 does not have this issue.

**Comment by lazulkia** [comment]
I had a similar problem.

```
Menu2(Item, id, menu, *) {

	if id
{
	MsgBox id
}
}
```

**Comment by strawhat-dev** [comment]
Just learned you can downgrade any extension by right-clicking or selecting the gear icon, and selecting 'Install Another Version...' (just in case it wasn't obvious to anyone else)
