### ISSUE TITLE
"Ahk2Exe.exe" was not found!" when not in default location.

### ISSUE THREAD

**Issue by DerDemystifier** [thqby/vscode-autohotkey2-lsp#514]
### Description

I'm encountering an issue where the extension cannot locate the Ahk2Exe.exe compiler when using a custom path.

**Details:**

* The extension has a setting named "Auto Hotkey2: Compiler CMD String" where I've specified the custom path:

```
%MyCustomPath%/AutoHotKey/Ahk2Exe.exe /gui /compress 0 /base ${execPath}
```

* The issue is that I receive an error message stating "Ahk2Exe.exe was not found!" despite the custom path being set correctly.

**Possible Causes:**

* The extension might be looking for Ahk2Exe.exe in the default location instead of the specified custom path.
* There could be a problem with how the extension interprets the custom path string.

**Note:**

* I've replaced `%MyCustomPath%` with the actual path to avoid revealing potentially sensitive information.

**Comment by thqby** [comment]
The extension will search for ahk2exe.exe based on the directory where ahk.exe is located, and the search scope will be consistent with the relative path of the two after installation.

**Comment by DerDemystifier** [comment]
For reference.. This is my directory for both ahk.exe and ahk2exe.exe

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/124774256/f9e5ee42-32d9-46a2-9743-b348d24bf77b)

These are my user settings:

```
    "AutoHotkey2.InterpreterPath": "D:/Users/XXXX/Documents/Portable_Apps/AutoHotKey/AutoHotkey64.exe",
    "AutoHotkey2.CompilerCMD": "D:/Users/XXXX/Documents/Portable_Apps/AutoHotKey/Ahk2Exe.exe /gui /compress 0 /base ${execPath}",
    "AutoHotkey2.CompleteFunctionParens": true,
    "AutoHotkey2.Warn.CallWithoutParentheses": "On"
```

**Comment by thqby** [comment]
Place ahk2exe.exe in the `compiler` directory
