### ISSUE TITLE
[Feature Request] Provide link to official doc when hover.

### ISSUE THREAD

**Issue by Norlandz** [thqby/vscode-autohotkey2-lsp#515]
Provide link to official doc when hover.

eg:
For ahk v1, [AutoHotkey NekoHelp](https://marketplace.visualstudio.com/items?itemName=cat1122.vscode-autohotkey-neko-help) can do this:
![Code-20240511_1417_27876](https://github.com/thqby/vscode-autohotkey2-lsp/assets/43581880/91e17359-9b5b-46c3-a092-54fe4cdb4d7f)

**Comment by fade2gray** [comment]
Click Ctrl+F1 whilst hovering.

**Comment by Norlandz** [comment]
> Click `Ctrl+F1` whilst hovering.

(Sorry I didnt know that. Thanks!)

**Comment by fade2gray** [comment]
If the caret is on an empty line - works by just hovering - but yeah. 😉
