### ISSUE TITLE
Include Files issue - CTRL-V causes duplication

### ISSUE THREAD

**Issue by samfisherirl** [thqby/vscode-autohotkey2-lsp#516]
When using or modifying the #Include section of the script, the extension doubles up included files. 

I recently installed a fresh-no-extension install which allowed me to test if it was caused by anything like extension overlap or otherwise. 

Tested with latest extension release 5-15-2024

https://github.com/thqby/vscode-autohotkey2-lsp/assets/98753696/a10d730b-6fdd-4a86-a6c9-a8e1fda52ecf

**Comment by thqby** [comment]
Can't reproduce this issue.
