### ISSUE TITLE
IntelliSense completion of property string values

### ISSUE THREAD

**Issue by marium0505** [thqby/vscode-autohotkey2-lsp#518]
Hey,

First off, I love your extension. It makes coding in AHK both more fun and much easier. Thank you!

By using Jsdoc, we can specify a lot of information about functions and more. For instance, we can let the user select between multiple strings when writing function parameters by using @ tag. However, it seems like we can't do the same for class properties.

See the screenshot below:
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/1466933/7f17f350-1b72-4300-88a4-91ef66a6e4d9)

I get the autocomplete for the values of the function parameter, but not when trying to set the value of the PropertyName property. Am I doing something wrong, or isn't the latter supported? If it isn't supported, is there any chance it can be added?

Thanks!

**Comment by thqby** [comment]
This is not supported. Annotations in variables also do not support this type of completion.

```
/** @type {'a'|'b'}
var := ''
```

**Comment by marium0505** [comment]
@thqby Thank you for the reply I see. 
Not supported as in not supported by your extension or not possible at all in VS Code (by any extension)?

**Comment by thqby** [comment]
Typescript supports this feature. I will support this feature in a later version.

**Comment by marium0505** [comment]
> Typescript supports this feature. I will support this feature in a later version.

Awesome! 👍🏼 
Thank you for your work and your time! 🙂

**Comment by marium0505** [comment]
Thanks, it works! 

Closing this! :)
