### ISSUE TITLE
Cant Debug currently opened file

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#519]
With the debugger updates you added you can no longer debug the currently selected file if there is a launch config file.

I was able to do this before:

• Hitting F5 follows the launch config file rules
• Clicking the Debug Icon would debug the currently opened file

Now both only obey the launch config file.

I usually had it where F5 would run the unit tests for a script / or the main script regardless of which file I was editing which is configured in the launch config file but clicking the debug icon would run the currently opened file in cases where i have a multi-module script where some modules are independent from the main script.

## Notes
Consider adding a separate hotkey/button for this functionality or maybe bring back the way it was working before.

**Comment by thqby** [comment]
When debugging is started, the first configuration with the same name in the launch file will be inherited. You can modify the name field.

**Comment by RaptorX** [comment]
Yes, I understand, but the problem is that the new way removed a feature that was available before: Some times the file I want to debug in the project is not the same as the one in the launch config file, I dont want to modify it, because the file listed is what i will debug most of the times.

When im debugging a given module i usually just open the file, make changes, run it, and once is good to go i just keep debugging the main file configured on the launch config file :)

**Comment by thqby** [comment]
Assign a unique value to the name field of AutoHotkey2.DebugConfiguration.

This will not be affected by the configuration in launch, nor will it affect the configuration in launch.

**Comment by RaptorX** [comment]
> Assign a unique value to the name field of AutoHotkey2.DebugConfiguration.

This would be on the settings file correct?


```
"AutoHotkey2.DebugConfiguration": {
        "name": "AutoHotkey2Unique",
        "port": "9002-9100",
        "useAnnounce": "detail",
        "useAutoJumpToError": true,
        "useDebugDirective": true,
        "usePerfTips": true,
    },
 ```
 
 Something like that?

**Comment by thqby** [comment]
yes

**Comment by RaptorX** [comment]
Alright, didnt know I could also setup multiple debug configurations in launch config and use them with this:

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/a3f3eab0-a043-4f1e-89f3-a32b6f7ffc34)

My question would be, is it possible to assign a hotkey to those? 
I havent seen that option yet.

**Comment by thqby** [comment]
Probably not.
