### ISSUE TITLE
Disable insertion of () by auto-complete

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#52]
The behaviour I am used to from multiple editors is that <kbd>Tab</kbd> or <kbd>Enter</kbd> inserts the suggestion as shown in the suggestion list. If I want parentheses, I type them. In SciTE, I don't have to press Tab or Enter; typing `dl(` will produce `DllCall(`. In Visual Studio, I type `Fu{enter}(` or `Fu{tab}(` to produce `Function()`.

This extension automatically inserts `()` for functions and methods when I press <kbd>Tab</kbd> or <kbd>Enter</kbd>, and this is nearly never what I want. I end up with `Function(("doesn't", "work"))` or `MsgBox( "I don't want parentheses at all.")` or `OnExit(CloseDoor())` instead of `OnExit(CloseDoor)`.

My searches indicated that some LSPs already behave the way I want, or have individual settings to control it (unique to the LSP). I know almost nothing about the VSCode extension API, but it seems to me that insertion of `()` is hard-coded in [completionProvider.ts](https://github.com/thqby/vscode-autohotkey2-lsp/blob/main/server/src/completionProvider.ts#L483-L484):
```TypeScript
				} else ci.insertText = ci.label + '($0)', ci.insertTextFormat = InsertTextFormat.Snippet;
			} else ci.insertText = ci.label + '()';
```
So please provide a setting to disable this.

My searches also indicated that some LSPs have a setting to control whether typing `(` commits the current auto-complete suggestion, but I could take it either way.

**Comment by thqby** [comment]
`AutoHotkey2.completeFunctionParens` setting item has been added.
