### ISSUE TITLE
Error on include path even when AHK runs correctly

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#520]
When accessing paths using bracket notation `<>` I always get that the path is invalid even though is not. Autohotkey can run the script just fine.

![20240529@11-17-08](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/9996587b-a5e5-4fb0-8b05-fb6ffbf9a77c)

This just started happening, I think it might be related to a vscode update because when I switch to different versions of the extension I get the same error which was not happening until today.

### Notes
This issue might be related to #500

**Comment by RaptorX** [comment]
I think it is related to the same file being included in multiple documents in the same workspace:

e.g.

### Unit Tests: `@S:\PrettyLinks\tests\unit.tests.ahk`

```
#Include ..\PrettyLinks.ahk
#Include ..\lib\classes\PrettyLink.ahk
```

### Main Script: `@S:\PrettyLinks\PrettyLinks.ahk`

```
#Include <gui\main>
#Include <classes\PrettyLink>
```


The main file above shows errors whenever the unit test files are including the files.
When commenting them out of the unit test file and reloading the workspace the problem goes away:

https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/6233c1c6-8af7-4dbd-9e71-6dd548db6c1c

**Comment by thqby** [comment]
In this case, you can only manually specify the script entry to resolve the conflict.

**Comment by RaptorX** [comment]
Yeah never mind, i think the issue is how the test file is setup... I included the main file for testing but when including this way the `#include`s in the main file become invalid. nvm.

**Comment by RaptorX** [comment]
> can only manually specify the

how can i do that?

**Comment by thqby** [comment]
command `ahk2.setscriptdir` can reset scriptdir.
