### ISSUE TITLE
[2.4.5] Intellisense issue with objects stored in properties

### ISSUE THREAD

**Issue by OpalMonkey** [thqby/vscode-autohotkey2-lsp#522]
Intellisense doesn't work when an object is stored in a property. I _thought_ it was working at some point in the past, but I could be mistaken.

```
vObj := Object()
vObj.Prop := Array()
vObj.Prop. ; <- Does not trigger Intellisense when typing the dot.

vObj := Array()
vObj. ; <- Triggers Intellisense as expected.
```

Using JSDoc type tags such as `/** @var {Array} vObj.Prop */`, or any other form of `@var` or `@type` tags I tried had no effect. I'm not sure if those kinds of tags are implemented or not. Just trying to be thorough.

Using an older version of the extension (`2.3.0`), Intellisense triggers, but not specific to `Array`. On `2.4.0` and up, it just doesn't trigger at all unless you start typing after the dot, and it's just a list of everything as though it's not even code. I didn't try any versions between those.

**Comment by thqby** [comment]
IntelliSense only gets the type at variable definition time, does not support adding attributes to objects in the middle of the process.

```
/** @type {{prop: Array}} */
obj := {}
obj.
```

**Comment by OpalMonkey** [comment]
Thanks, that's interesting. Odd that I have never noticed that limitation before.

I find the JSDoc syntax to be a little confusing and the documentation somewhat vague. How would I go about defining more than one property? `/** @type {{prop1: Array, prop2: Map}} */` and the other variants of it that I've tried don't seem to work, and that's the closest I can find in the JSDoc documentation.

**Comment by thqby** [comment]
`/** @type {{prop1: Array, prop2: Map}} */`

That's it.

**Comment by OpalMonkey** [comment]
Ah, sorry, that was my mistake. I was testing it on something a little more complex. I was extending the GUI class and had it like this: `@type {{cText: GuiEx.Text, cButton: GuiEx.Button}}`. The issue was that I hadn't overridden `Button` and was expecting the type to call through. Everything works as expected when I change it to `Gui.Button`.

Sorry for the misunderstandings on my part, and thank you again for giving me a little insight.
