### ISSUE TITLE
"Class Static Member Check" setting is described ambiguously and/or doesn't take effect immediately

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#523]
Consider clarifying the name or description of the "Class Static Member Check" setting. Is "static" meant like `static` as used in the AutoHotkey language, or as in "non-dynamic"?

I was looking for a way to turn off diagnostics for cases like this:
```AutoHotkey
class RtObject extends RtAny {
    static __new() {
        this.DefineProp('ptr', {value: 0})
        this.prototype.DefineProp('ptr', {value: 0})
        this.DefineProp('__delete', {call: this.prototype.__delete})
    }
    __delete() {
        (this.ptr) && ObjRelease(this.ptr)  ; Two diagnostics are shown for `ptr` on this line.
    }
}
```
I found "Class Static Member Check", but turning it off appeared to have no immediate effect. The diagnostics disappeared only after I modified the file. So either the setting does not take effect immediately, or it is not supposed to affect instance members but something else went wrong. It is hard to tell because of the ambiguous wording of the warning.

**Comment by thqby** [comment]
When this feature was first added, it referred to the static properties and methods of ahk, and then gradually extended to non-dynamic properties. It should be called "Class Non-Dynamic Member Check"?

> The diagnostics disappeared only after I modified the file. 

Yes, Modifying the configuration does not take effect immediately until the content changes, as does most of the configuration of the extension.

**Comment by Lexikos** [comment]
> It should be called "Class Non-Dynamic Member Check"?

I think so.
