### ISSUE TITLE
Working together with AutoHotkey Plus Plus

### ISSUE THREAD

**Issue by mark-wiemer** [thqby/vscode-autohotkey2-lsp#530]
Hi @thqby, you've done great work here. I'm back to working on AHK++ (https://github.com/mark-wiemer-org/ahkpp) and I'd like to add v2 support to it for folks that may still use a mix of v1 and v2 scripts. Your repo obviously does a lot and it'll take some time for me to catch up, but would you be open to PRs that fix some code style issues in the short term? That'll help me understand things a bit better and maybe fix some bugs as I go. Let me know if there are any tools you've tried before that you'd like to avoid, I'm thinking of just starting with ESLint for now :)

**Comment by thqby** [comment]
Why do you want to integrate two extensions that are still under maintenance? This increases the workload and distracts attention from the current project. Is there any advantage?

**Comment by mark-wiemer** [comment]
I don't think there will be any increased workload on your side, I'll just be cleaning up code and adding unit tests :)

My goal is to have one extension support both AHK v1 and AHK v2 as v1 is still used by a large portion of developers. Since my extension supports v1, I'll eventually add your extension as a submodule to my own so that there is one extension that supports both. Either that, or we can make an extension pack keeping the extensions separate but "bundled" so users can discover them more easily. That's not something I've explored, but might be ideal in the long run.

Overall, I just wanted to see if you were open to outside contributors adding engineering hygiene checks like formatters, linters, and unit tests. I didn't want to step on your toes there :)

**Comment by mark-wiemer** [comment]
Ref also https://github.com/mark-wiemer-org/ahk-extension-pack

**Comment by thqby** [comment]
> Overall, I just wanted to see if you were open to outside contributors adding engineering hygiene checks like formatters, linters, and unit tests.

Of course you can.
I'm using eslint9 and vscode's eslint extension.
