### ISSUE TITLE
Can't access nlark or taobao to contribute to this project

### ISSUE THREAD

**Issue by mark-wiemer** [thqby/vscode-autohotkey2-lsp#531]
As an American, it seems my access to nlark is either very limited or non-existent. When I clone the main branch of the project and run `npm install`, I get an ENOTFOUND error. Do you know of any way Americans can access nlark, or are you willing to move to a more international CDN by chance? I'd love to help and I can work around this issue in the short term, but to add ESLint and other dependencies I'd have to fly to China!

```
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.nlark.com/yocto-queue/download/yocto-queue-0.1.0.tgz?cache=0&sync_timestamp=1628813299341&other_urls=https%3A%2F%2Fregistry.nlark.com%2Fyocto-queue%2Fdownload%2Fyocto-queue-0.1.0.tgz failed, reason: getaddrinfo ENOTFOUND registry.nlark.com       
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

Ref https://github.com/mark-wiemer-org/vscode-autohotkey2-lsp/issues/2 and https://community.nethserver.org/t/yarn-cannot-download-packages-for-building-ui-on-github/23633

Looks like taobao is having a similar issue. After replacing `nlark` with `npmmirror` and running `npm install`, I got this:

```
npm ERR! code CERT_HAS_EXPIRED
npm ERR! errno CERT_HAS_EXPIRED
npm ERR! request to https://registry.npm.taobao.org/yazl/download/yazl-2.5.1.tgz failed, reason: certificate has expired
```

I'm replacing `npm.taobao` with `npmmirror` as well for now.

**Comment by mark-wiemer** [comment]
I'm also fixing the `npm audit` issues via `npm audit fix --force` as the only update was `vsce`. It's now been renamed `@vscode/vsce` so that should be an easy fix :)

**Comment by thqby** [comment]
I'm currently using the global default install of npm and vsce, and have not noticed their configuration in the project.

**Comment by mark-wiemer** [comment]
Hmm, I'm not sure what you mean when you say you haven't noticed their config in the project. npm is used to install the packages, and vsce is used to package (`npm run package`) the extension. So they're both necessary, the only issue is that we can't access nlark. I think if you move your `node_modules` folder somewhere else and try to run `npm install` you'll get the same issue as me :/

I think I have a fix though, I'm updating my npm to install from npmmirror and then re-installing all packages with the exact versions they have in the current package lock manually, as there aren't that many. From there we should have an international solution that relies on npmmirror :)

**Comment by mark-wiemer** [comment]
Signing off for the night, looking forward to more collaboration going forward :)

**Comment by thqby** [comment]
I use `npm -g npm @vscode/vsce` to install npm and vsce, so the configuration used is not the configuration in the project.
