### ISSUE TITLE
Auto-indent after if/else/loop/etc is broken ?

### ISSUE THREAD

**Issue by vmech** [thqby/vscode-autohotkey2-lsp#535]
I saw [issue #9](https://github.com/thqby/vscode-autohotkey2-lsp/issues/9)
I have the same problem.
A new line inserts 1 indent after any keywords. But when I enter a curly brace, this indentation remains.
This looks like this:
```
if ( a )
	{}
```
Very annoying. Is it possible to somehow solve this problem?

**Comment by thqby** [comment]
https://github.com/thqby/vscode-autohotkey2-lsp/issues/310#issuecomment-1510422359

**Comment by vmech** [comment]
Is this incorrect formatting a «feature» of VSCode?
Doesn't the extension have anything to do with it?

**Comment by thqby** [comment]
vscode also has configuration files that handle this situation, but it does not work in some complex statements. The extension corrects indentation by range formatting, but requires editor.formatOnType to be enabled.

**Comment by vmech** [comment]
TY for the help
