### ISSUE TITLE
Auto-indent problems still here... [Following #535]

### ISSUE THREAD

**Issue by vmech** [thqby/vscode-autohotkey2-lsp#536]
Hi @thqby! Again.
I applied `"editor.formatOnType":true` as you suggested.
But now a new problem pops up caused by auto-formatting...
I prefer to separate expressions in conditional statements from parentheses with spaces. But now the editor is trying to break this habit.
![1st](https://i.imgur.com/PtM3OyW.png)
![2nd](https://i.imgur.com/yZ3TFTi.png)
![3rd](https://i.imgur.com/iBb6EF2.png)
Then I tried to enable the formatting rule `"AutoHotkey2.FormatOptions":{"space_in_paren": true}`
And the result of this is the following:
![4th](https://i.imgur.com/nhEWl5O.png)
But I don't need surrounding spaces in function arguments. If only because now the editor will push these spaces into EVERY function in the code...

How can I get around this misunderstanding? Otherwise, this whole situation is already starting to seem like some kind of madness...
I just wanted the curly braces to be keyword aligned. I don’t need any other auto-formatting anymore, I’ll do everything myself.

PS. And I have not even checked how autoformatting processes lines with other keywords.

**Comment by thqby** [comment]
> I don’t need any other auto-formatting anymore, 

This conflicts with the implementation of automatic indentation and cannot be avoided.

**Comment by vmech** [comment]
> This conflicts with the implementation of automatic indentation and cannot be avoided.

It's a shame that everything is so hopeless.

For now, I've chosen to exclude the extension from interfering with the auto-formatting process in order to set the auto-indents as desired and avoid side effects.
Disabled `"editor.formatOnType":false`
And changed `"editor.autoIndent": "brackets"`
So far I’m happy with everything, it’s better than it was before.
I'll keep looking, I have a lot of code that needs to be worked on.
