### ISSUE TITLE
Question about addon syntax and use

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#541]
First, is there a more appropriate place for me to ask questions like this?

Second, array is defined as `class Array<T = Any> extends Object` in the definition file.  
What does the `<T = Any>` syntax represent?  
I scrolled through and noticed it applies to maps and enumerators as well.  
Is this something that is applied to enumeration?

How does the addon utilize this information?

Edit: Maps are defined as `<K = Any, V = Any>`.  
If `K` = is Key and `V` is Value, why does Array use `T`?
And why isn't array defined as`<I = Integer, V = Any>`, where I = Index and V = Value?

Sorry for all the questions. I just really like this addon and want to understand everything about it so I can make the most out of my own definition file.

Thanks.

**Comment by thqby** [comment]
This is called genericity in other languages. It can be used in type annotations. For example, Array<String> represents an array of strings.
```
/** @type {Array<String>} */
arr := []
```

> Edit: Maps are defined as <K = Any, V = Any>.
If K = is Key and V is Value, why does Array use T?
And why isn't array defined as<I = Integer, V = Any>, where I = Index and V = Value?

yeah. T = Type

**Comment by GroggyOtter** [comment]
Thank you for the explanation. 👍  

***
I do want to ask this again:  
Is this an appropriate forum to ask questions about the addon, being it's not really an "Issue"? Are you OK with it?  
Or do you prefer questions be asked somewhere else?

***
And I did have 1 new syntax question:  

`something => throw`  

Is this indicating "something" is invalid syntax and that it will "throw" an error?  

If yes, it seems returning an Error object indicating an error would be practical, considering `something => throw` is technically invalid syntax.  

Or does the addon utilize `=> throw` in special way?

Thanks.

**Comment by thqby** [comment]
This does not make sense at the moment, just to indicate that the method is not implemented.
