### ISSUE TITLE
Hover features broken inside functions/methods

### ISSUE THREAD

**Issue by JThirGreen** [thqby/vscode-autohotkey2-lsp#542]
The latest version (v2.4.7) seems to have broken hover features for local variables of functions/methods.

v2.4.6
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/35150682/a0881935-f607-4529-9ca0-af65febbd9de)

v2.4.7
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/35150682/1d87a063-3218-4fef-810d-5902af6f0ff3)

**Comment by OpalMonkey** [comment]
I thought I was losing my mind. This also affects things like IntelliSense for `this.` methods in extended classes. Rolling back to v2.4.6 works for me, too.

**Comment by RaptorX** [comment]
I think many things are broken inside function definitions. #540 seems to be related to this report as well.

**Comment by OpalMonkey** [comment]
Yeah, agreed. Not that it's at all helpful, but I expect it's related to #518. At least it's easy to roll back in VSCode.
