### ISSUE TITLE
Bug with function bodies

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#545]
After the latest update, the addon seems broken inside of function bodies.  

I was just trying to create a menu and the intellisense wasn't working. No properties or methods came up.  
Furthermore, the addon doesn't detected the variable as a menu object.  

After some troubleshooting, I realize this only happens inside of function/method definitions.  

In global space, everything works as intended.

This works b/c it's in global space:
```
; Hovering over mu shows it's a menu object
mu := Menu()

; All methods and properties come up when mu. is typed
; Add() shows its parameters in the calltip
mu.add()
```

None of these work.  
No methods or properties come up when `mu.` is typed.  
Hovering over `mu`  shows no information.
```
; Function test
test() {
    ; Hovering over mu shows nothing
    mu := Menu()

    ; Add() is NOT detected
    mu.add()
}

; Method test
class my_class {
    static method() {
        ; Hovering over mu shows nothing
        mu := Menu()

        ; Add() is NOT detected
        mu.add()
    }
    
    method() {
        ; Hovering over mu shows nothing
        mu := Menu()

        ; Add() is NOT detected
        mu.add()
    }
}

; Hotkey test
*#RButton:: {
    ; Hovering over mu shows nothing
    mu := Menu()

    ; Add() is NOT detected
    mu.add()
}
```

***
In the mean time, downgrading to 2.4.6 seems to fix this until 2.4.8 is released.

**Comment by RaptorX** [comment]
#540 and #542 cover some of the issues you mentioned.

**Comment by GroggyOtter** [comment]
> #540 and #542 cover some of the issues you mentioned.

Roger that.

Just doing my job and reporting a bug I found. The posted issue titles didn't seem to jive with my problem so I made a post.  

¯\\\_(ツ)\_\/¯

**Comment by RaptorX** [comment]
Yeah, no worries. I made the comment mainly so that thqby knows those bugs might all be caused by the same problem.
