### ISSUE TITLE
Feature request: A way to specify a multi-option parameter to prevent the caret from moving right

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#547]
The parameter autocomplete provided by the addon is **extremely** helpful and I've been playing with it a lot.  

However, there's one small issue I have with it.

Currently, when an parameter auto-complete item is selected, the text is inserted and then the caret is moved once to the right.  
This puts the caret outside the string.  

For a single-option field, this works perfectly and is a good addition.  

But when working with multi-option fields, this is a nuisance.  
The user must continuously arrow left after each item selection.

I would like to propose a simple solution that should be easy to implement.  

Allow for a way to identify single-item vs multi-item parameter lists.  
Such as prefixing the list with the word `Multi` unquoted.  
That can be used to indicate whether the caret should be moved right after selection.

Examples  
CoordMode() has single options where only one item is ever expected.  
Items are inserted and the caret is moved outside the quotes.  
```
@param {'Caret'|'Menu'|'Mouse'|'Pixel'|'ToolTip'}
@param {'Client'|'Screen'|'Window'}
```
MsgBox() might require multiple options, such as: `YesNo Icon? Default2`  
The user has to arrow back twice to insert each additional item.  
Prefixing the list with `Multi` would indicate the caret should not be moved after item selection.  
```
@param {Multi|'OK'|'OKCancel'|'AbortRetryIgnore'|'YesNoCancel'|'YesNo'|'RetryCancel'|'CancelTryAgainContinue'|'IconX'|'Icon?'|'Icon!'|'Iconi'|'Default2'|'Default3'|'Default4'}
```

Would you please consider implementing some type of option like this?  
Some way to control when the caret is moved.

Thanks, THQBY.

**Comment by thqby** [comment]
Replace `multi` with `string`.

**Comment by GroggyOtter** [comment]
> Replace `multi` with `string`.

Oh my god, you already have this implemented?  
And it's done almost the same way suggested?  
Perfect. Thanks.  

Great minds think alike? ¯\\\_(ツ)\_\/¯
