### ISSUE TITLE
JSDoc  - @type {Array.<String>} and @type {Object[]}

### ISSUE THREAD

**Issue by marium0505** [thqby/vscode-autohotkey2-lsp#549]
According to [JSDoc - Arrays and objects (type applications and record types)](https://jsdoc.app/tags-type#jsdoc-types), this should be possible:
```autohotkey
/**
 * 
 * @param {Object[]} arr1 and @type {Array.<Object>} Should both be treated as an array of objects. 
 * @param {String[]} arr2 and @type {Array.<String>} Should both be treated as an array of strings.
 * @param {Array} arr3 A third array .
 */
ArrayParams(arr1, arr2, arr3) {
}
```

But `arr1` is treated as a single object, not an array with objects and `arr2` is treated as a single string, not an array with strings.

Here is a similar snippet in Javascript with arrays of different types: 
```js
/**
 * 
 * @param {Array.<Number>} arr1 
 * @param {String[]} arr2 
 */
function ArrayParams(arr1, arr2) {
}
```

Here, `arr1` is correctly treated as an array with numbers and `arr2` as an array with strings. 

Would be cool if this could be fixed.

**Comment by thqby** [comment]
`Array<Number>`

Only this form is currently supported.

**Comment by marium0505** [comment]
> `Array<Number>`
> 
> Only this form is currently supported.

Ahh, with the period `.` removed.  
Thanks. 

Also it seems like the extension think that any of the parameters in for loops (including the index) is of any available class,
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/1466933/2f056383-0a37-401c-bf4b-d0975bdfa70a)

Is that on purpose or a bug?
Btw, is there any way we can decide which type each of the parameter is without doing this? 

```autohotkey
/** @type {Integer}  */
index := ""
/** @type {Map}  */
value := ""

For index, value in Obj {
	
}
```

**Comment by thqby** [comment]
```
/** @type {Enumerator<String, Map>} */
obj := Map()
for k, v in obj
	k.
```

forloop's parameters are valid only within loop block.
```
i := 11
for i in [1]
	i++
MsgBox(i)    ; 11
```

**Comment by RaptorX** [comment]
Autohotkey is not a typed language: 

```
/** @type {Number} */
v := 1

v := "this is text now"

; now you might be in for a nice surprise later on
```

That's the reason I think it only makes sense for function/method parameters to be typed, that way you at least know what is expected to be passed. Outside of that, I don't know if it makes sense to set the type of a variable in a block of code.
