### ISSUE TITLE
Document Color issue

### ISSUE THREAD

**Issue by aseiot** [thqby/vscode-autohotkey2-lsp#55]
![image](https://user-images.githubusercontent.com/600263/140461224-cd6de324-fea1-4363-8433-5c7877bc5af3.png)
Seems parsed multiple times.

**Comment by thqby** [comment]
When does this happen?

**Comment by aseiot** [comment]
I just narrow down the code, and found may relate with strings with quote

![image](https://user-images.githubusercontent.com/600263/140527939-6a246de1-2573-4582-9479-c0b1b4465063.png)
