### ISSUE TITLE
Request: Add optional indicator for parameters on calltips

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#550]
Can you please change the display behavior for optional parameters in the calltip?  
Items marked as optional in their JSDoc tag should display as optional in the calltip:  

This is how it's marked in the definition:
`@param {(String)} [Text]`

This is how the calltip looks:  
![Code_LwFNzFRUjg](https://github.com/thqby/vscode-autohotkey2-lsp/assets/29220773/1d03743b-758e-4c6a-b507-27889ec0550b)

This is how I think it should look:  
Adding brackets around the parameter would indicate the parameter is optional, as sometimes it's not apparent in the code line up top.  
(sorry for the crappy Photoshop. not an artist.)  
![Code_LwFNzFRUjg - Copy](https://github.com/thqby/vscode-autohotkey2-lsp/assets/29220773/8dca9731-3135-4f43-b5a2-a30f41899a57)

**Comment by thqby** [comment]
It is clear in the function definition which parameters are optional. Is it necessary to show this again?

**Comment by FuPeiJiang** [comment]
> (sorry for the crappy Photoshop. not an artist.)

since vscode is html, you can inspect element and add the brackets `[Text]`

you do this by running the command: `Developer: Toggle Developer Tools`

but you can't really edit it since once you unfocus or alt+tab, it disappears
you can work around this by making everything pause after 3 seconds: `setTimeout(() => {debugger},3000)` (you run this javascript in the Console tab)
then you can Resume execution by going in Sources tab,
then you can make your screenshot,

**Comment by GroggyOtter** [comment]
> > (sorry for the crappy Photoshop. not an artist.)
> 
> since vscode is html, you can inspect element and add the brackets `[Text]`
> 
> you do this by running the command: `Developer: Toggle Developer Tools`
> 
> but you can't really edit it since once you unfocus or alt+tab, it disappears you can work around this by making everything pause after 3 seconds: `setTimeout(() => {debugger},3000)` (you run this javascript in the Console tab) then you can Resume execution by going in Sources tab, then you can make your screenshot,

I knew about the dev tools but didn't know how to account for it disappearing when I switched Windows. That's a helpful trick. Thanks for posting it.

**Comment by RaptorX** [comment]
> My counter question is "why do you allow for the use of the optional parameter syntax with @param tags if you're not going to do anything meaningful with that information?"

I agree with this sentiment. 

What I was thinking is that the calltip doesn't use colors which might be useful for conveying information without adding characters. 

I love how in the JsDoc comment some keywords are highlighted, but then we lose that highlight in the call tip.

This is another example in which say yellow names are required while gray ones are optional. 

Not sure why not use those things in the call tip, maybe technical restraints? But i think it might be very useful to make the tip easier to read.

**Comment by thqby** [comment]
Optional parameters will be underlined.
