### ISSUE TITLE
In-line comment not detected in switch statement when using multiple case values

### ISSUE THREAD

**Issue by zachpoblete** [thqby/vscode-autohotkey2-lsp#554]
![image](https://github.com/user-attachments/assets/6bdacd1c-1cfa-4236-9e0c-68fb3dd38b72)

**Comment by GroggyOtter** [comment]
Can confirm.  
Happens when splitting a case into multiple lines.
```
switch {
    case not true,              ; No comment highlight
        not false: Msgbox(1)    ; Comment highlight
    default: MsgBox(0)          ; Comment highlight
}
```
![Code_8NvI0AHmZB](https://github.com/user-attachments/assets/fb31111b-e617-4542-b3f8-7a9121e10690)
