### ISSUE TITLE
Syntax highlighting error.

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#555]
The addon currently parses properties incorrectly based on the comma's location
```
obj := {
    first: 'Groggy',   ; Textmate identifier: variable.other.ahk2
    last: 'Otter'      ; Textmate identifier: variable.other.ahk2
}
```

Move the comma to the next line:
```
obj := {
    first: 'Groggy'    ; Textmate identifier: variable.other.ahk2
    ,last: 'Otter'     ; Textmate identifier: variable.other.property.ahk2
}
```

It appears that properties aren't being parsed correctly as properties when declaring objects.  

Both properties are scoped as `variable.other.ahk2`:  
![Code_NV1jL5SFSD](https://github.com/user-attachments/assets/32561f27-a074-4abc-8472-b1fcbddd52ba)

Moving the comma to the next line causes the second item to scope correctly `variable.other.property.ahk2`:
![Code_NvmgdkxZMc](https://github.com/user-attachments/assets/c69240a4-db06-4f3c-bc3c-3c34b5f32a20)

But the first property still remains incorrectly identified as `variable.other.ahk2`:  
![Code_S8zUQwmZ32](https://github.com/user-attachments/assets/a1c54f8c-9176-4f5f-bc44-072699da832e)

Edit:  
Adding a 3rd property to the object without a comma before it still produce an incorrect syntax highlight:  
![Code_WSduiMH94J](https://github.com/user-attachments/assets/cd06b0a0-8a0a-4834-9563-d315067d2e1b)

**Comment by thqby** [comment]
see #460
