### ISSUE TITLE
Using VS Code Timeline for compare to older version causes errors

### ISSUE THREAD

**Issue by wilkster** [thqby/vscode-autohotkey2-lsp#556]
I use the VS Code Timeline to compare current edits to a prior version quite often. I have noticed that when I do so, and then close the temporary file, I get persistent error messages about conflicting declarations and such.  I have to close and restart VS Code to clear the messages.

![image](https://github.com/user-attachments/assets/df9f88bd-0203-4bff-bcf7-7f80ea0eb510)

**Comment by fade2gray** [comment]
A 'quick fix' - instead of restarting VSCode, you can open the AHK v2 extension's settings, select disable, followed by 'Restart Extensions', and then re-enable it.
