### ISSUE TITLE
Adding/preserving new line at the end of file

### ISSUE THREAD

**Issue by AdrianMiozga** [thqby/vscode-autohotkey2-lsp#557]
Is there any way to automatically add or at least preserve new line at the end of file? It’s quite common for formatters like [Black](https://github.com/psf/black), [Prettier](https://github.com/prettier/prettier), or [ktfmt](https://github.com/facebook/ktfmt) to do that.

Right now, it changes all my scripts.
![image](https://github.com/user-attachments/assets/62809d84-30e2-42ec-9f58-8c19657b7318)

**Comment by fade2gray** [comment]
Add `"files.insertFinalNewline": true` to your settings.json.

**Comment by AdrianMiozga** [comment]
Oh, so you can change VS Code setting and this extension will respect it.

Thank you very much!
