### ISSUE TITLE
Names not recognized after discarding changes with Source Control

### ISSUE THREAD

**Issue by zachpoblete** [thqby/vscode-autohotkey2-lsp#564]
In the following example, the test repo contains `main.ahk` which calls `function()` and `#Includes function.ahk` which contains the definition of `function()`.

These files have been commited.

![image](https://github.com/user-attachments/assets/1e1ffef0-e247-43f9-9b00-d1b393cb77cd)

If we close `function.ahk` and rename `function()` to `functionRenamed()` in `main.ahk`,

![image](https://github.com/user-attachments/assets/6eebb2a2-31c8-4292-a7db-881974976479)

it's also renamed in `function.ahk` as expected, which is confirmed by `function.ahk` appearing as changed in the Source Control panel on the right.

![image](https://github.com/user-attachments/assets/270db6d1-bd78-4c3c-9d5e-bbb785a7b672)

But if we discard all our changes through the Source Control panel,

![image](https://github.com/user-attachments/assets/56e5c85b-5316-4eea-8c2a-b1c46a5620f6)

`function()` in `main.ahk` is not recognized as having been defined.

![image](https://github.com/user-attachments/assets/9d1fce5c-0236-4924-ae54-1e699ea666c1)

And if we try to rename `function()`,

![image](https://github.com/user-attachments/assets/91b2509a-4d73-4b17-8821-9a82916fa201)

it isn't renamed in `function.ahk`.

![image](https://github.com/user-attachments/assets/1a67c4f4-0467-43bc-83b2-4201be470ac2)

**Comment by zachpoblete** [comment]
Probably related to #493.

**Comment by thqby** [comment]
This is unrelated. When you close function.ahk, vscode will not monitor the contents of the file for changes. After git retracts the changes, vscode does not notify the extension that the content of the file has changed, thus updating the cache.

**Comment by zachpoblete** [comment]
Hmm, so no way around this?
