### ISSUE TITLE
[Wish] Allow simple math with Update File Version function

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#566]
It would be interesting to have the following behavior:

```
/**
 @description starting with this version
 @version 1.0.0
*/
````

Calling Update File Version and giving it:

• `2.0.0`    -> would replace to `2.0.0`
• `2.+1.+3` -> would update to `2.1.3`
• `3.+1.0`   -> would update to `3.2.0`

So is not full pfledged expressions but only allow to use `+` to add up from the previous version number in the same spot.

**Comment by thqby** [comment]
Compared with the current situation, I don't think entering version numbers in this style will greatly improve convenience.

**Comment by RaptorX** [comment]
Yeah, its a minor thing.

I thought it would be difficult to implement, but if it is, then is not really needed.
