### ISSUE TITLE
[WISH] Consider moving context menu items to a submenu

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#570]
Between this extension and `ahk++`, my context menu grew so much that it became a bit annoying finding the commands I wanted.

I modified the menu to have it like this:
![image](https://github.com/user-attachments/assets/421b18d9-683f-4cf8-af70-f2a095339046)

Can we have that as an option or at least consider it? because when too many extensions add to the main context menu it gets cluttered really quickly.

I did the same with `ahk++` and i feel free again! haha!

Thank you for all the work you do!
awesome work as always.

**Comment by thqby** [comment]
I merged several debugging-related commands into a submenu a few days ago.

**Comment by marium0505** [comment]
Another advantage of putting stuff in a sub-menu is that it is easier to identify (immediately) which extension an item is from.  
And the fact that it reduces clutter is an advantage in itself as it makes it easier to find stuff.
