### ISSUE TITLE
Attach to running script issue with window title

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#573]
Type: <b>Bug</b>

When running the command to attach to a running script I get two errors (they look the same) but if you press continue both times you get a dialog to choose the path to the script you want to connect to.

After that it behaves completely fine.

### Current window title

![image](https://github.com/user-attachments/assets/9c9ce895-16a9-49db-90d3-563c2a3da4f0)

### Regex against Code window

https://regex101.com/r/b4Qaqw/1

### Error 1

![image](https://github.com/user-attachments/assets/f1e27c1c-112e-4ead-b28d-ee290f4cad40)

### Error 2

![image](https://github.com/user-attachments/assets/220fbcf6-bb5b-4e6d-acde-14f17cfd6c09)

### Dialog

![image](https://github.com/user-attachments/assets/09e2b70e-5c5f-43a4-9fbd-415691a84371)

### Correct connection

![image](https://github.com/user-attachments/assets/c8214db9-ce81-4817-adaa-81c471447b30)

### Notes

Im not sure what are the contents of the `title` variable, but i would assume you are getting it from the active window (code.exe in this case?)

But it seems like it needs some work after some recent updates. This was not happening before.

---

Extension version: 2.4.9
VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (20.16GB free)|
|Process Argv|--crash-reporter-id 3e042e59-cb22-4371-968a-6f3e35abe666|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31118572

```

</details>

**Comment by thqby** [comment]
This feature is provided by the debug extension.
