### ISSUE TITLE
Incorrect indent inside and after conditional function definition block

### ISSUE THREAD

**Issue by LifeJustDLC** [thqby/vscode-autohotkey2-lsp#574]
Title is explicit

![屏幕截图 2024-08-22 060152](https://github.com/user-attachments/assets/8d16af84-f114-4c73-927f-c7dfa773c309)

After a brief bisect, it seems be introduced in 2.4.4 but not completely fixed after 2.4.5

**Comment by fade2gray** [comment]
Works for me, v2.4.9.

**Comment by teadrinker2015** [comment]
Same on Mac. v2.4.9

<img width="353" alt="截屏2024-08-22 09 57 24" src="https://github.com/user-attachments/assets/72f89b35-0ebf-4a67-9aef-b8944f7bd9ad">

**Comment by fade2gray** [comment]
Windows 11

https://github.com/user-attachments/assets/2b03b6bc-4bc5-4486-9313-09f5e5822178

**Comment by LifeJustDLC** [comment]
Forget to mention, Windows 10 & Mac

https://github.com/user-attachments/assets/ceeed34d-a546-495b-894d-ffef1f3a6d6b

**Comment by fade2gray** [comment]
Ok, Indentation gets broken if formatted from the context menu.

**Comment by mark-wiemer** [comment]
Plaintext for the curious:

```ahk
if x {
    f() {
        MsgBox("in")
}
MsgBox("out")
}
```
