### ISSUE TITLE
希望添加选项：在不清楚变量内容时不显示警告。

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#578]
![image](https://github.com/user-attachments/assets/e5f078ba-aa50-4726-bf14-4fe280ab8cdc)
![image](https://github.com/user-attachments/assets/9ef96e2a-a88a-45c4-92b4-50bf14d43015)

图片中的代码是可以正常运行的。`xx`变量的内容是一个VarRef实例，符合`VarSetStrCapacity()`的要求。但插件仍然对变量`xx`显示警告。 故希望可以：消除此类警告、或者添加选项消除此类警告。（建议后者）

**Comment by RaptorX** [comment]
When you hover over it it explains what the warning is about:
![image](https://github.com/user-attachments/assets/33afd381-f39f-43c4-8d93-568cce3dbe7a)

While `VarSetStrCapacity(varName)` "works" that form is deprecated and its there for backwards compatibility as far as i remember.

The recomended is `VarSetStrCapacity(&varName)` note the `&`.

Per the documentation you mentioned:
![image](https://github.com/user-attachments/assets/a2e85a0c-1680-4351-9084-fb12d1de5059)

If he decides to remove that i hope that is as an option/setting. I think we should keep warnings about deprecated syntax.

I would agree that the hover tip should be explicit about the fact that the syntax is actually deprecated though.

**Comment by thqby** [comment]
```
/** @type {VarRef} */
v := ''
VarSetStrCapacity(v)
```

**Comment by PythonYunfei** [comment]
> /** @type {VarRef} */

This is a feasible idea.
