### ISSUE TITLE
建议在文档添加对.d.ahk文件的详细说明

### ISSUE THREAD

**Issue by Autumn-one** [thqby/vscode-autohotkey2-lsp#579]
.d.ahk对与第三方库作者是比较重要的问题，目前来看似乎与typescript规则有些相像，是否可以在文档中添加对此类类型定义文件工作原理的指引？包括怎么正确的定义对原型扩展的类型说明

**Comment by Autumn-one** [comment]
例如我希望为字符串的原型添加类型，我不知道如何编写对应的d.ahk文件

**Comment by thqby** [comment]
在.d.ahk中定义

```
/** @extends ~\syntaxes\ahk2\String */
class String {
}
```

**Comment by Autumn-one** [comment]
我这样做会在`class String` 这里报错，目前只有 Array的类型复写是生效的。
我定义了 array.ahk 来复写 Array的原型，然后在同级目录创建 `array.d.ahk`  内容为： `class Array<T = Any> extends Object {}`  在这里复写就能生效，也没使用 `;@include` 语法。但是这个做法在 string 和 object 上面都不生效。

**Comment by thqby** [comment]
`;@reference file.%A_Locale%.d.ahk`

最新版增加了A_Locale变量来支持多语言的声明文件。
