### ISSUE TITLE
Turn off auto-includes

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#58]
How do I stop the extension from automatically inserting an `#include` when I type a function that it can't find in the script?  I could not find this "feature" in the readme, and was not expecting it, especially since I had already noticed the "AutoIncludeLib" setting was turned off.

These silent modifications to files caused me headaches several times. For instance,
  - An *invalid* file containing random snippets has been automatically included without my knowledge, and it causes very confusing error messages that cannot possibly relate to the change I just made.
  - At some point the extension failed to recognize `#include %A_LineFile%\..\xxx.ahk` and `#include 'xxx.ahk'` as the same file, and was highlighting *fake* "duplicate declaration" errors. I do not know why or when the second #include was added, but I know I didn't do it. Now I cannot reproduce the fake error messages; maybe the extension was updated since.
  - I start to write a function *definition*, but before I can get to the open-brace, the extension decides I am trying to call a function from a totally unrelated file that happens to be in the same directory, so it adds an unwanted `#include`.

Some objections I have to this feature are:
  - It is not clear that a modification is going to be made automatically to the file, or where. (Although there is a message in the auto-complete like "auto-import from xxx", its meaning is not clear, and I am used to ignoring the auto-complete tooltip.)
  - The extension can be wrong about whether adding an #include is correct.
  - The extension cannot know how the overall script should be organized; e.g. that if an #include is actually required, I will want it in some other file that #includes this one.
  - If there are no #includes, it is added to the end of the file. If the code within relies on initializing global constants or similar, it will likely not work.
  - If the file ends with `/*`, the #include has no effect because it is inside a comment.
  - It encloses the filename in single quotes, which does not match with the other #includes in my script.

Compare this to Visual Studio's "quick action" light bulbs, which offer similar shortcuts. Quick actions do not make automatic changes to the code; the change is always initiated by the user, so they know it is happening and can verify the result. They offer a visual cue that some additional change might be needed, but the programmer can choose to ignore it. They are also often incorrect or unwanted, so I disable them.

As an aside, I found that AutoIncludeLib=true includes functions from *sub-directories* of a Lib folder, which is not at all how v1 function library auto-include works. For instance, `xxx(` caused `#Include <Unicode_x64\xxx>` to be added. This was a v1 script, so not useful. I use a structure like the following, with symbolic links:
```
Documents\AutoHotkey -> Scripts
Scripts\Lib\
    ANSI
    Unicode
    Unicode_x64
    v2
Program Files\AutoHotkey\
    Lib -> Scripts\Lib\Unicode_x64
    v2-alpha\Lib -> Scripts\Lib\v2
Projects\AutoHotkey\
    v1\bin\
        x64w -> Scripts\Lib\Unicode_x64
        Win32w -> Scripts\Lib\Unicode
    v2\bin\
        x64w -> Scripts\Lib\v2
        ...
```
In practice, I only use Unicode_x64 and v2. I have v1 and v2 versions of some scripts, and `#Include <xxx>` will include the appropriate one.

By contrast, the extension will include the first one that it finds anywhere within the user lib directory tree.

Also, it does not work consistently. At least one function is not discovered, while other functions in the same directory are. I thought it might relate to there always being other files in the same directory that #include it, so I opened a new VS Code window and tried in an untitled document.

In "Untitled-1", the #includes are not added. After trying several times, I noticed there is a second tab named "untitled-1" which contained several duplicate #includes, with two being on the same line.

**Comment by thqby** [comment]
`AutoHotkey2.AutoLibInclude` setting item is adjusted to `'Disabled', 'Local', 'User and Standard', 'All'`.
