### ISSUE TITLE
希望你能注册成为微软认证开发者

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#580]
![image](https://github.com/user-attachments/assets/d4c380a5-8bbe-43cf-af08-9271cbfae71a)
成为注册开发者后名字会变成蓝色，并打勾。很多插件开发者选择注册微软认证开发者，来提高插件的知名度和安装量。虽然他们可能有各自的目的。
但听说成为微软认证开发者并不麻烦。希望本插件能完成这一步骤。

**Comment by thqby** [comment]
域名要钱
