### ISSUE TITLE
Cannot switch to v1 if file is open

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#581]
Type: <b>Bug</b>

I think since 2-3 commits ago I can no longer switch to v1 if the file is already open.

I have to close it and re-open it for the switch to happen.
Not sure if something changed on your extension or @mark-wiemer's AHK++ Extension.

---

https://github.com/user-attachments/assets/8b7871e1-3c47-4c2b-9b8c-40fb0925201b

---

Extension version: 2.5.0
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.71GB free)|
|Process Argv|--crash-reporter-id 3e042e59-cb22-4371-968a-6f3e35abe666|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by thqby** [comment]
https://github.com/thqby/vscode-autohotkey2-lsp/issues/461

You submitted this issue last year.

**Comment by RaptorX** [comment]
> #461
> 
> You submitted this issue last year.

Yes it was fixed for a long time. 

During recent updates it just started happening again. Not sure if it was an update on your end or on his end.

**Comment by thqby** [comment]
This notification window should be from ahk++.

I didn't update this part of the code.

**Comment by RaptorX** [comment]
> This notification window should be from ahk++.
> 
> I didn't update this part of the code.

alright, ill report it there then.

I do get some failed folding notifications from ahk2 but havent been able to reproduce it correctly so havent reported it.

**Comment by thqby** [comment]
> I do get some failed folding notifications from ahk2 but havent been able to reproduce it correctly so havent reported it.

I guess they happen when the extension switches language to v1 and destroys the resource, and some requests that have been initiated access to non-existent resources cause this error.

**Comment by RaptorX** [comment]
> > I do get some failed folding notifications from ahk2 but havent been able to reproduce it correctly so havent reported it.
> 
> I guess they happen when the extension switches language to v1 and destroys the resource, and some requests that have been initiated access to non-existent resources cause this error.

I see, that makes sense, they do tend to happen after trying to switch to v1
