### ISSUE TITLE
希望把调试按钮设置成可选的

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#585]
[调试插件该干的事:](https://github.com/thqby/vscode-autohotkey2-lsp/issues/569#:~:text=%E8%BF%99%E6%A0%B7%E5%A6%82%E6%9E%9C%E6%9C%89%E5%85%B6%E4%BB%96%E8%B0%83%E8%AF%95%E6%8F%92%E4%BB%B6%E4%B9%9F%E5%AE%9E%E7%8E%B0%E4%BA%86%E7%9B%B8%E5%90%8C%E5%8A%9F%E8%83%BD%EF%BC%8C%E5%B0%B1%E6%8A%8A%E8%AF%A5%E5%A4%8D%E9%80%89%E6%A1%86%E7%9A%84%E5%8B%BE%20%E5%8F%96%E6%B6%88%E6%8E%89%E3%80%82%E8%BF%99%E6%A0%B7%E5%B0%B1%E5%8F%AF%E4%BB%A5%E9%81%BF%E5%85%8D%E5%92%8C%E8%B0%83%E8%AF%95%E6%8F%92%E4%BB%B6%E5%86%B2%E7%AA%81%E3%80%82%E6%AF%95%E7%AB%9F%E8%BF%99%E4%B8%A4%E4%B8%AA%E7%89%B9%E6%80%A7%E6%9C%AC%E8%AF%A5%E5%B1%9E%E4%BA%8E%E8%B0%83%E8%AF%95%E6%8F%92%E4%BB%B6%E8%AF%A5%E5%B9%B2%E7%9A%84%E4%BA%8B%EF%BC%8C%E4%B8%8D%E5%B1%9E%E4%BA%8E%E6%9C%AC%E6%8F%92%E4%BB%B6%E8%AF%A5%E5%B9%B2%E7%9A%84%E4%BA%8B)
![image](https://github.com/user-attachments/assets/270118d8-ba34-47c8-99d9-d164fd90f45b)
理由正如上次的帖子中所说。
另外，我想多数用户会通过快捷键进行调试，操作简洁；而非通过按钮进行调试。在这种情况下，新增的调试按钮毕竟会占据标签栏可视区域的空间。希望可以提供选项，使得用户可以取消按钮：
![image](https://github.com/user-attachments/assets/23cb2805-f233-4794-92e3-6d8abc5c4550)

另外，也希望下面的图片中的设置，也能增设复选框，从而也变成可选的设置。出于一致性、以及本插件功能的纯粹性考虑。但更重要的是，添加复选框可以避免和其他调试插件的潜在冲突。（比如某`调试插件A`也从settings.json中读取`launch设置`，这时本插件的这个功能就要取消，以避免重复读取设置）
![image](https://github.com/user-attachments/assets/33d2e727-a3cf-4529-94b7-529b6ad9bbf0)

**Comment by thqby** [comment]
这是运行下拉栏按钮，默认应该显示运行，由于没设置图标显示的是文本。

下面对于不喜欢或不知道创建launch.json的比较有用。设置为空对象即不会起作用。

**Comment by PythonYunfei** [comment]
> 这是运行下拉栏按钮，默认应该显示运行，由于没设置图标显示的是文本。
> 
> 下面的设置对于不喜欢或不知道创建launch.json的比较有用。设置为空对象即不会起作用。
> 
> 使用全局launch配置又会将不相关的调试配置附加到其他项目的调试配置下拉栏中。

可是我前几天的版本，我这里是看不到任何调试按钮的：
![image](https://github.com/user-attachments/assets/a8f4b974-3785-4899-a1f8-5317233ad8b4)
可能是因为我把调试按钮框设置成了浮动的，或者哪里设置了。平时看不见调试按钮，只有在调试的时候，调试按钮才会以悬浮的形式出现：
![image](https://github.com/user-attachments/assets/50ab4514-17dc-43ee-bd3a-f9a6c01d831b)
但是现在，“调试按钮”调试按钮会始终出现。
不管怎样，把上面两个功能设置成可选的，肯定各类用户都能接受。同时也能保持本插件功能的纯粹性和简洁性，不至于随需求增加而成为大杂烩。
甚至另外搞个插件的都有。把上述两个功能改成可选功能，也没啥大不了的..

**Comment by thqby** [comment]
右键隐藏

**Comment by PythonYunfei** [comment]
> 右键隐藏

这个是可以的。只是出于插件改进提issue，没想到可以直接右键😅
那么，现在还剩下第一个建议，理由依然同上：
![image](https://github.com/user-attachments/assets/9c5732d2-3940-401f-b4cc-d38f27c1e7a8)

**Comment by thqby** [comment]
> 设置为空对象即不会起作用
