### ISSUE TITLE
[FEATURE REQUEST] Support showing methods defined through ``[Type].Prototype.DefineProp``

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [thqby/vscode-autohotkey2-lsp#586]
Let's say you have this piece of code below. My expected behavior when typing `testArray.IndexOf` is that there should be some suggestions popping up and showing arguments, and when I hover on them, the ``ArrayIndexOf``'s usage will be shown, like when I hover on ``ArrayIndexOf``

But it seems that the extension looks like ignored them

If this is really hard to make, is there a workaround? I'd like to insert methods by using metatable-like ways, not extending a class and inserting my own methods.

```autoit
; Concatenate all strings in an array ---> only a string
ArrayConcat(array, sep := " ", i := 1, j := false) {
    str := array[i]

    if j = false {
        j := array.Length
    }
    else if i > j {
        throw Error("ArrayConcat: Why i > j?")
    }

    while i < j {
        i++
        str .= sep array[i]
    }

    return str
}

; Get index of the first-found value in array
ArrayIndexOf(array, value, regex := false) {
    if (!IsObject(array) or array.Length = 0)
        return 0
    
    for k, v in array {
        if (regex and v ~= value) or (!regex and v = value)
            return k
    }

    return 0
}

Array.Prototype.DefineProp("indexOf", {Call: ArrayIndexOf})
Array.Prototype.DefineProp("concat", {Call: ArrayConcat})

testArray := [5, 4, 3, 2, 1]
MsgBox(testArray.IndexOf(4))    ; 2
MsgBox(testArray.Concat())      ; 5 4 3 2 1
```

**Comment by thqby** [comment]
https://github.com/Autumn-one/ahk-standard-lib/blob/main/en/array.d.ahk

Redefine the class in the `*.d.ahk` file.
Refer to this to implement.

**Comment by thqby** [comment]
https://github.com/thqby/vscode-autohotkey2-lsp?tab=readme-ov-file#declaration-document

**Comment by SweetSea-ButImNotSweet** [comment]
> https://github.com/thqby/vscode-autohotkey2-lsp?tab=readme-ov-file#declaration-document

Thanks for implementing it, I just saw it. Good approach 👍
