### ISSUE TITLE
[v2.1-alpha.14] Cannot inspect variable if named "info"

### ISSUE THREAD

**Issue by Descolada** [thqby/vscode-autohotkey2-lsp#588]
This bug occurs with v2.1-alpha.14, but not 2.0.18. If a variable is named `info` and is inspected, it shows as not initialized:
![image](https://github.com/user-attachments/assets/e8469dec-a888-4e8c-a026-159305f6d132)

```
#Requires AutoHotkey v2.1-alpha.14
info := Map("hello", "world")
MsgBox info["hello"]
```

**Comment by thqby** [comment]
The extension simply starts the debugger and provides no other debugging-related features.

This is a bug in ahk v2.1 where all variables starting with `inf` will be recognized as floating-point `inf` when debugging.

**Comment by Descolada** [comment]
Is this bug already reported?

**Comment by thqby** [comment]
Not reported yet.

**Comment by Descolada** [comment]
[Reported.](https://www.autohotkey.com/boards/viewtopic.php?f=14&t=132887)
