### ISSUE TITLE
TraySetIcon without first param throws error despite it being suggested in the docs

### ISSUE THREAD

**Issue by EatPrilosec** [thqby/vscode-autohotkey2-lsp#591]
`TraySetIcon( ,, true)` is suggested in the docs here: https://www.autohotkey.com/docs/v2/lib/TraySetIcon.htm#Remarks

yet, when used,  throws an error that its missing a parameter. however, the script runs and compiles as expected:

![image](https://github.com/user-attachments/assets/bc3ccb86-c3c6-42a5-a182-f54320cfa347)

**Comment by thqby** [comment]
Modify ahk2.d.ahk to temporarily fix it.
`TraySetIcon(FileName?: $FilePath, IconNumber := 1, Freeze := false) => void`

**Comment by GroggyOtter** [comment]
> `TraySetIcon( ,, true)` is suggested in the docs here: https://www.autohotkey.com/docs/v2/lib/TraySetIcon.htm#Remarks
> 
> yet, when used, throws an error that its missing a parameter. however, the script runs and compiles as expected:
> 

My [enhanced addon file](https://github.com/GroggyOtter/ahkv2_definition_rewrite) doesn't seem to have this issue.  
Consider giving it a try. You might like it.
