### ISSUE TITLE
Regex + Options = Parenthesis marked as invalid 

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#593]
Type: <b>Bug</b>

When using options in a regular expression the extension marks the closing parenthesis at the end as invalid.

```
RegExMatch(link, 'i)lists\/(?<fName>\d+-).*?\/', &matched)
```

![image](https://github.com/user-attachments/assets/1aa27c83-71f6-4549-af14-418d37f586be)

---

Extension version: 2.5.1
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (19.11GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\Dropbox\\Jeff_B\\CrunchBase Scraper --crash-reporter-id 3e042e59-cb22-4371-968a-6f3e35abe666|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by fade2gray** [comment]
Have you recently updated the extension? See https://github.com/mark-wiemer-org/ahkpp/issues/481

**Comment by thqby** [comment]
![image](https://github.com/user-attachments/assets/7d62aa20-f0a1-47df-8790-119d49677ce0)
Cannot be reproduced.

**Comment by fade2gray** [comment]
https://github.com/user-attachments/assets/e8e49768-51ab-4549-87ef-e64b67a4791f

**Comment by thqby** [comment]
This feature is provided by vscode and is enabled by setting `editor.bracketPairColorization.enabled`. Extensions can only specify which parentheses are not colored, but they are all correctly specified. This should be vscode's issue and seems to only arise when upgrading and extending.

**Comment by thqby** [comment]
This feature is provided by vscode and is enabled by setting `editor.bracketPairColorization.enabled`. Extensions can only specify which parentheses are not colored, but they are all correctly specified. This should be vscode's issue and seems to only arise when upgrading and extending.
