### ISSUE TITLE
Ternary warning inside class

### ISSUE THREAD

**Issue by Descolada** [thqby/vscode-autohotkey2-lsp#594]
Happens if a ternary is inside a class method and contains a `this` property assignment.
![image](https://github.com/user-attachments/assets/e734fd8b-207b-4cff-812b-5de627845c7a)

**Comment by PythonYunfei** [comment]
Maybe it is a bug of AHK rather than the extension.
![image](https://github.com/user-attachments/assets/1c014380-35cb-4bc2-9d65-a4466897029e)
In the above picture. The `,` operator has lower precedence than `?:`. So it will throw.
Therefore, a `:=` between `?:` without parentheses should throw too.

**Comment by GroggyOtter** [comment]
> Maybe it is a bug of AHK rather than the extension.

Your code example is flawed. You've included a multi-statement inside your ternary without putting it in parentheses.

`(1) ? (2, (this.xx:=32)) : 0`

**Comment by PythonYunfei** [comment]
> > Maybe it is a bug of AHK rather than the extension.
> 
> Your code example is flawed. You've included a multi-statement inside your ternary without putting it in parentheses.
> 
> `(1) ? (2, (this.xx:=32)) : 0`

Yes. And the same is to `this.b:=1`. 
But I already know what I mistook.😀
![image](https://github.com/user-attachments/assets/966aed5c-0fcf-4569-9921-495a8d284ad2)
