### ISSUE TITLE
希望给DllCall.Bind增加类型补全提示

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#595]
希望给`DllCall.Bind("xx","ptr")`增加类型补全提示。
有时会把`DllCall.Bind("xx","ptr")`中的`ptr`输成`prt`，故希望增加对应的类型补全提示。

**Comment by mark-wiemer** [comment]
English translation from DeepL:

I want to add a type-completion hint to DllCall.Bind(“xx”, “ptr”).
Sometimes the ptr in DllCall.Bind(“xx”, “ptr”) is lost as prt, so I would like to add the corresponding type-completion hint.

**Comment by mark-wiemer** [comment]
![image](https://github.com/user-attachments/assets/bb85ca23-cca9-4235-9225-e4f1e53f3804)

Fixed with this ^
