### ISSUE TITLE
希望增加`/* @Base {CCC} */`以支持提示静态成员的参数

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#597]
希望增加`/* @equals {CCC} */`以支持提示静态成员的参数。

![image](https://github.com/user-attachments/assets/67073a5e-308e-461d-9265-2cdc6e31b777)
如图所示，类的静态成员的参数有时也需要提示。所以希望增加`/* @equals {CCC} */`、`/* @extends {CCC} */ `来表示该类本身、或其子类。

当然，如果有其他恰当名字 来命名这类注解也可以.. 比如`@Base`。（真心感觉`@Base`非常不错，最能充分表达当前语义，且不失灵活性，强烈推荐）

**Comment by thqby** [comment]
`/** @type {typeof ccc} */`

**Comment by PythonYunfei** [comment]
> `/** @type {typeof ccc} */`

请问`/** @type {typeof ccc} */`在你代码中使用得多吗，如果还不算多，那么我强烈建议把语法改成`/* @Base {CCC} */`。
由于`/** @type {typeof ccc} */`在插件介绍页中并未公开介绍。这说明除了插件作者之外，使用`/** @type {typeof ccc} */`用法的人几乎没有。因此，不如趁`/** @type {typeof ccc} */`还处于待敲定状态，将它的语法改为最好的。
毕竟目前有6万人在使用本插件，并且以后使用本插件的还会越来越多。注解的写法将决定所有人代码的展现形式。因此，能用最好最灵活的语法语义  就用最好的语义。

**Comment by thqby** [comment]
typeof是typescript的一个运算符，适用于jsdoc

**Comment by thqby** [comment]
typeof是typescript的一个运算符，适用于jsdoc

**Comment by thqby** [comment]
typeof是typescript的一个运算符，适用于jsdoc

**Comment by PythonYunfei** [comment]
`/* @type {typeof xx1} */`的意思大概是指：下一行变量`xx2`的类型与`xx1`相同。它只能保证`xx2`与`xx1`类型相同，因此编辑器只能提示补全`对应prototype`中的属性，而不会去补全`xx1`已知的实例属性。
但使用/* @base {xx1} */，则表明：下一行变量`xx2`与`xx1`的所有已知属性相同。因此编辑将提示补全`xx1`中所有已知的属性。
所以功能上可能不太一样。
jsdoc的注解标准毕竟适用于`typescript`，而非众多其他编程语言。如果`AutoHotKey V2`的语法与`typescript`有所不同，那么其注解也可有所出入。
以上仅供参考。如无特别必要，此建议可忽略。😀

**Comment by PythonYunfei** [comment]
typescript也不一定就完美
还是感觉`/* @type {typeof xx1} */`表达的意思和它字面相比有些牵强。可能是它的一个小糟粕。所以咱们可以考虑取其精华、去其糟粕，改为`/* https://github.com/base {xx1} */`。😉

**Comment by thqby** [comment]
typeof可以和对象联用

类似`/** @type {{a: typeof aa, b: typeof bb}} */`
