### ISSUE TITLE
[Enhancement:] 一个不必要的警告

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#599]
![image](https://github.com/user-attachments/assets/04f93bb0-a809-45a1-9a8c-ac9e42685042)

**Comment by thqby** [comment]
加`;@lint-disable class-non-dynamic-member-check`

**Comment by PythonYunfei** [comment]
主要希望开启这类检查。但是希望检查的过程中可以识别`return inst`，从而让后续的`this`获得所有`inst`相关的属性提示或补全。
希望先不关这个，什么时候有时间再去增强这个都行。这个wish完全不着急。

**Comment by thqby** [comment]
这超出静态检查的范围，只有显式声明是支持的。

`static Prototype.count := 0`这也是有效的

**Comment by thqby** [comment]
这超出静态检查的范围，只有显式声明是支持的。

`static Prototype.count := 0`这也是有效的

**Comment by PythonYunfei** [comment]
![image](https://github.com/user-attachments/assets/eb765cbc-951c-4af2-9f3a-652229d9bf8b)

目前没有对 `this` 发挥作用
但静态Call()的返回值必定和this相同。你可以做这个断言。这属于面向对象 的惯例：

类A的构造方法返回的对象X，必须满足：X is A==true

**Comment by PythonYunfei** [comment]
我是感觉只要是面向对象的语言， 肯定会符合面向对象里的common sense的..
主要 你只是对静态Call开了个特殊， 没啥副作用..

**Comment by PythonYunfei** [comment]
> 只有显式声明是支持的。
> 
> `static Prototype.count := 0`这也是有效的

 但这个  毕竟行为不一样
一个是给实例加属性，一个是给prototype加。  这样需要该代码，并破坏 原有的结构设计..

**Comment by PythonYunfei** [comment]
再次说一下，这个不是一定要有，太麻烦就算了..
