### ISSUE TITLE
Typing a full stop triggers completion list unexpectedly

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#6]
This happens in both single-line comments and block comments.

    ; End.   ←  triggers completion list with Add, AddActiveX, etc.

Maybe someone wants it this way, but I assume it's unintended since it's inconsistent with typing `(`, which triggers parameter info only outside of comments.

It's also triggered while typing `.` for concatenation, as in `a . b`. I think that's acceptable, since it's actually valid to write `obj .property` with space in between, but if possible I would set it to pop up only if there is a non-space character preceding `.`.

It's also triggered while typing `.` in a number such as `1.0`. In this case it is at least limiting the list to members of `Any` (so maybe it is recognizing the type of value correctly?), but it seems unnecessarily distracting. The completion list seems unlikely to be useful in this context.

**Comment by thqby** [comment]
This was fixed in v0.6.9
