### ISSUE TITLE
Goto workspace symbol

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#60]
> ### Open symbol by name [#](https://code.visualstudio.com/docs/editor/editingevolved#_open-symbol-by-name)
> Some languages support jumping to a symbol across files with Ctrl+T. Type the first letter of a type you want to navigate to, regardless of which file contains it, and press Enter.

This doesn't work for me; I just get "No matching workspace symbols" no matter what I type.

It would be very handy to have. Currently I navigate by Ctrl+Shift+F, but sometimes there are many results other than the one I want.

The extension seems capable of collecting symbols across files, showing or jumping to definitions in other files, and jumping to a symbol in the current file (Ctrl+Shift+O), so I don't see why it can't do this. I guess it's a bug or missing feature.

**Comment by thqby** [comment]
This feature is not yet available.
