### ISSUE TITLE
Function parentheses and curly braces don't comment out correctly.

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#601]
Function parentheses and curly braces remain syntax highlighted after being commented.  

![Code_c7OijzVk6S](https://github.com/user-attachments/assets/7bdfc993-1d6c-4652-a5dd-df90134ab14f)

![Code_vPW4XMCdOg](https://github.com/user-attachments/assets/71f44ce8-19f7-49d8-a815-3a1cca55f4fd)

Their textmate scope shows as `comment.block.ahk2`, however, the display remains as though `punctuation.section.xxx` is still in effect.  

This persists until something forces the editor to check/update the script's syntax highlighting.  
At that point, it correctly sets all the characters to the correct color.

![Code_DXZbDCBprU](https://github.com/user-attachments/assets/e3bfbdfc-ed16-4ad4-ac05-83c8d54c9a24)

**Comment by thqby** [comment]
Parentheses coloring is a built-in feature of vscode, not provided by extensions.

**Comment by GroggyOtter** [comment]
I'm very aware that coloring option is handled by VS Code.  
And I know how to change the colors as my theme is quite unique and obviously 100% customized.  

The problem is that when commenting out a block of code, multiple characters stay syntax highlighted.  
This applies to YOUR ADDON ONLY.  
If I create a JS file and I follow the exact same steps, the colorization doesn't stay.
That's why I'm reporting it to you and not to the VS Code GitHub.

Can you please start taking reports a little more seriously instead of just responding with default information that isn't applicable?  
Every time I report something to you, you seem to be dismissive like I don't know what I'm talking about or like I'm holding you accountable for things you can't alter. And time after time, that's rarely the case.  

It's not a good way to respond and talk to people who are actively trying to help you make your addon better.
