### ISSUE TITLE
参数提示框有没办法设置成弹出在下面

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#604]
![image](https://github.com/user-attachments/assets/b5f261d1-9261-449c-a569-e97d9c0ecbec)
如图，目前参数提示总是弹出到右上。但是输入参数必然要看上面的变量，如果参数提示框也显示在上面，那么有时难免会对想看的变量造成遮挡。
所以，不知能否提供选项，让参数提示框显示在下面..

**Comment by thqby** [comment]
问vscode官方
