### ISSUE TITLE
代码格式化后数组无法正常折叠

### ISSUE THREAD

**Issue by abgox** [thqby/vscode-autohotkey2-lsp#605]
- 当前，代码格式化后，数组无法正常折叠
- 应该让数组格式化后的结果可折叠
---
![ahk-demo](https://github.com/user-attachments/assets/76883070-c4ec-423c-8186-4f6830ec9279)

**Comment by RaptorX** [comment]
If I remember right, that is a VSCode problem. It creates folding points based on indentation. 

I think the extension would have to force create folding points in certain spots.

**Comment by thqby** [comment]
No, code folding can be set to be provided by the extension. When there are multiple fold points on the same line, vscode should use the first one.

**Comment by abgox** [comment]
- 可不可以让扩展在格式化代码时，就格式化为以下样式呢？这样 vscode 也能根据缩进创建合理的折叠点
```
list := [
    {
        name: 1,
        age: 2
    }, {
        name: 2,
        age: 3
    }
]
```

- 现在，扩展会格式化为以下样式
```
list := [{
    name: 1,
    age: 2
}, {
    name: 2,
    age: 3
}
]
```
- 直接让代码格式化改变一个风格可能会导致喜欢原有风格的人无法接受，所以添加一个扩展配置来控制它可能是一个不错的选择

**Comment by abgox** [comment]
- 同时，对于变量声明，扩展的格式化在我个人看来有些奇怪，这在 AHK 中是正确的代码风格吗？
![image](https://github.com/user-attachments/assets/cc2eb89d-0f81-4889-ad1d-0d4986448bbd)
- 对于我来说，我觉得格式化成下方这样的风格可能更合理，也更美观
![image](https://github.com/user-attachments/assets/f23e95fe-eed4-4a69-b49d-d8b5f810e20a)

**Comment by thqby** [comment]
设置格式化选项中的array_style。

下一种声明，去掉`,`。一般用缩进表示声明的层级

**Comment by abgox** [comment]
- 这样吗，这个格式化似乎也有点奇怪
![image](https://github.com/user-attachments/assets/6ffb40d5-2c18-4341-8f41-af1f9f730a84)

> 下一种声明，去掉 `,`。一般用缩进表示声明的层级
- 你是说变量声明去掉逗号吗？
- 但是我添加逗号的原因是，文档中说，连续的变量声明使用 `,` 对性能可能有帮助

**Comment by thqby** [comment]
实测在v2中性能提升不大，甚至略慢
