### ISSUE TITLE
[Question:] 安装`Material Icon Theme`后，所有`.ahk`的图标都变回了V1的

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#606]
`Material Icon Theme`是一款非常强大精美的图标库插件。 里面有海量的图标。同时也在VSCode必装插件的列表中..

但是安装`Material Icon Theme`后，所有`*.ahk`的图标都变回了V1的图标：
![image](https://github.com/user-attachments/assets/80c34d0b-0b05-4af6-8ace-1af1cb7c39ae)
但是`*.ahk2`的图标仍然保持V2的图标不变：
![image](https://github.com/user-attachments/assets/77554932-9e4f-4a4b-9bef-cdc116c63e00)

有什么比较好的解决方案吗？或是插件哪里需要调整一下..

**Comment by thqby** [comment]
看看安装的扩展的设置项能不能不看扩展名识别文件类型。
