### ISSUE TITLE
Text expansions are doubled

### ISSUE THREAD

**Issue by johnw42** [thqby/vscode-autohotkey2-lsp#607]
It's easiest to explain with an example. Open a new .ahk file and type this in:

```
::a::aaa
::b::bbb
```

Then save the file. The contents look like this now:

```
::a::aaa
::b::bbbbbb
```

This only happens for lines added since the file was opened.

Found in version 2.5.2

**Comment by PythonYunfei** [comment]
> It's easiest to explain with an example. Open a new .ahk file and type this in:
> 
> ```
> ::a::aaa
> ::b::bbb
> ```
> 
> Then save the file. The contents look like this now:
> 
> ```
> ::a::aaa
> ::b::bbbbbb
> ```
> 
> This only happens for lines added since the file was opened.
> 
> Found in version 2.5.2
I've tested it. This doesn't happen in my computer.

**Comment by thqby** [comment]
The issue cannot be reproduced. You can try again after restarting vscode.
