### ISSUE TITLE
`npm run test` failing

### ISSUE THREAD

**Issue by mark-wiemer** [thqby/vscode-autohotkey2-lsp#608]
Hi, I think some recent changes to `extension.test.ts` or something else has caused the tests to now fail. I'm OK with this, as I've learned that these tests use some outdated tools. I wanted to inform you in case you were working on a fix. Otherwise, I'm working on modernization that will allow us to use better tools, but these tests will be broken during the transition. So this is mostly an FYI :)

![image](https://github.com/user-attachments/assets/55adba31-856f-424f-bf7d-ec857174afd4)

<details open><summary>Plaintext output</summary>

```log
~/repos/ahkpp/ahk2 (upstream-main)
$ git log -4
2024-09-27 22:20:20
f254405 thqby v2.5.2 (HEAD -> upstream-main, upstream/main)
f6b0973 thqby fixed #596
5e443f5 thqby fixed #594
[last: 0s]
~/repos/ahkpp/ahk2 (upstream-main)
$ git pull
2024-09-27 22:20:22
Already up to date.
[last: 1s]
~/repos/ahkpp/ahk2 (upstream-main)
$ npm run validate
2024-09-27 22:20:27

> vscode-autohotkey2-lsp@2.5.2 validate
> npm run test-grammar && npm run test


> vscode-autohotkey2-lsp@2.5.2 test-grammar
> vscode-tmgrammar-snap tmgrammar-test/*.ahk

√ tmgrammar-test/0-v2-demo.ahk run successfully.

> vscode-autohotkey2-lsp@2.5.2 test
> tsc && vscode-test


[main 2024-09-28T05:20:31.736Z] update#setState disabled
[main 2024-09-28T05:20:31.738Z] update#ctor - updates are disabled by the environment     
[main 2024-09-28T05:20:31.741Z] Error: Error mutex already exists
    at yt.U (C:\Users\markw\repos\ahkpp\.vscode-test\vscode-win32-x64-archive-1.93.1\resources\app\out\vs\code\electron-main\main.js:118:71351)
Started local extension host with pid 18600.
Loading development extension at c:\Users\markw\repos\ahkpp\ahk2
  0 passing (1ms)
[main 2024-09-28T05:20:35.233Z] Extension host with pid 18600 exited with code: 0, signal: unknown.
Exit code:   0
[last: 8s]
~/repos/ahkpp/ahk2 (upstream-main)
```

</details>

**Comment by thqby** [comment]
![{CA2F46E0-BFF9-4C39-91BD-C4E37B495EB8}](https://github.com/user-attachments/assets/59f9247a-6d0a-4bf5-9c9b-940acf4c2ff8)

**Comment by mark-wiemer** [comment]
Can you try re-cloning the repo? I think you may have some packages or global packages installed that are not part of the repo anymore. I also noticed that package-lock.json wasn't updated for 2.5.2, that may be the case as well. I can try to bisect as well on my end.

**Comment by mark-wiemer** [comment]
@thqby the PR was merged but the issue still stands: I can't run tests, and neither can GitHub Actions :(

**Comment by mark-wiemer** [comment]
Ah, sorry, I see you updated it. Consider this closed, thank you very much!

**Comment by thqby** [comment]
> neither can GitHub Actions :(

https://github.com/thqby/vscode-autohotkey2-lsp/actions/runs/11100952686

**Comment by thqby** [comment]
> neither can GitHub Actions :(

https://github.com/thqby/vscode-autohotkey2-lsp/actions/runs/11100952686

**Comment by thqby** [comment]
> neither can GitHub Actions :(

https://github.com/thqby/vscode-autohotkey2-lsp/actions/runs/11100952686
