### ISSUE TITLE
"For" and "In" have different colors

### ISSUE THREAD

**Issue by john-cj** [thqby/vscode-autohotkey2-lsp#62]
Currently, with the default "Dark+" color theme, `for` and `in` in for-loops have different colors:

![image](https://user-images.githubusercontent.com/18004961/143791266-bbf7966d-3017-4cc8-926d-4e108f3e1e84.png)

As a workaround, the user can use "Dark (Visual Studio)" theme instead, but I think it would be better to "fix" the colors for the default theme as well.

**Comment by thqby** [comment]
see [issues 40](https://github.com/thqby/vscode-autohotkey2-lsp/issues/40#issuecomment-903235546).

**Comment by john-cj** [comment]
Hello, and thanks for this extension. I don't know Chinese, so I tried to translate it with Google Translate. Does the linked issue mean that it is not yet possible to make the colors look consistent in `Foo ... In` loops?

**Comment by thqby** [comment]
`for` is control flow statements keyword, `in` is an operator, that's what I defined in Textmate scope.
And it is also described in the AHK document.

They have different colors in "Dark+" color theme. This is a matter of personal preference. Of course, you can also modify the `syntaxes/ahk2.tmLanguage.json` files to make them the same color.
```
// Move `in` to `reserved` from `operators` category
"operators": [
    {
          "match": "(?<!\\.)\\b(?i:and|or|not|in|is|contains)\\b(?!\\s*:)",
          "name": "keyword.operator.expression.ahk2"
    }
]

"reserved": [
    {
          "match": "(?<!\\.)\\b(?i:break|continue|until|else|for|goto|if|throw|try|finally|return|while)\\b(?!\\s*:)",
          "name": "keyword.control.ahk2"
    }
]
```

**Comment by john-cj** [comment]
Got it, thanks.
