### ISSUE TITLE
Can't Debug AHK Files

### ISSUE THREAD

**Issue by Lunatik6572** [thqby/vscode-autohotkey2-lsp#622]
Since about a month or two ago, I am no longer able to debug AHK files. VS Code always says "Debug extension was not found, please install the debug extension first!  Source: AutoHotkey v2 Language Support" 

Then it lists a few other extensions that are not this extension. I have tried changing settings and reinstalling and nothing seems to make VS Code recognize that the extension is able to debug.

![image](https://github.com/user-attachments/assets/3554dec1-c857-4dbb-844e-1f4bfd501a96)

![image](https://github.com/user-attachments/assets/4430dde6-61db-489f-93a4-3a79c99980ff)

**Comment by thqby** [comment]
Do you have debug extensions installed? Modify DefaultDebugger in the settings, if any. Otherwise, install the debugger.

**Comment by Lunatik6572** [comment]
I have a python extension that can debug, but there are no python files in this project. 

Also, I thought this extension had a debugger built in. It says in the description:
"No additional configuration is required to start the installed Debug extensions, and support debugging with parameters."

Are you saying that the extension cannot debug on its own and that I _must_ install another extension?

**Comment by thqby** [comment]
> Are you saying that the extension cannot debug on its own and that I _must_ install another extension?

Yeah, the extension does not have debugging capabilities, but simply launches the installed debugger without the launch.json configuration file.

**Comment by Lunatik6572** [comment]
My apologies, I assumed it was different. I installed an extension that can debug and it works fine now.
