### ISSUE TITLE
识别到的`TODO`标签，一个大写、一个小写

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#630]
![image](https://github.com/user-attachments/assets/5439c2e0-0524-4b54-a797-c88fddd01086)
当前面连续有两个分号`;`时，识别到的`TODO` Tag 从大写变成小写。

**Comment by thqby** [comment]
`;;`创建的代码标记

**Comment by PythonYunfei** [comment]
所以是By design吗？
那么请忽略..

**Comment by thqby** [comment]
修改commentTags设置项

**Comment by PythonYunfei** [comment]
好吧
