### ISSUE TITLE
Compile script fails 

### ISSUE THREAD

**Issue by kovesp** [thqby/vscode-autohotkey2-lsp#631]
Getting EPERM:operation not permitted, unlink '....exe'.
The file is not protected and compiling from the context menu of the corresponding .ahk file works fine.

**Comment by PythonYunfei** [comment]
> Getting EPERM:operation not permitted, unlink '....exe'. The file is not protected and compiling from the context menu of the corresponding .ahk file works fine.

Maybe more information is needed. 
What protected?  Did you mean antivirus software?

Perhaps you can try compiling by directly double clicking `Ahk2Exe.exe`, in the `Compiler` folder.
![image](https://github.com/user-attachments/assets/3edae454-e6f4-4129-a9bb-423463c0cb97)

If it also fails, then it isn't the fault of the extension.

**Comment by RaptorX** [comment]
He probably meant that the file isn't locked by windows.

This same situation happened to me, maybe its not your case but check if the script loads `.dll` files.
the DLL itself might be locked and if the script tries to use FileInstall on those, it might fail to include them in the compiled script.

**Comment by kovesp** [comment]
I figured out what the problem is. When ahk2exe is called from the command line or from the context menu AND the exe version of the script is running it displays this dialogue:

[cid:3912f58f-2f7a-495e-91c3-fd8570a27526]

If ahk2exe is called with the /silent option, the dialogue is supressed and the compilation fails. Presumably you are doing this, so there is no dialogue.

Options to make this work:

  1.
Simple: run ahk2exe without the /silent option so the dialogue comes up and let the user decide. Still better than having to navigate to the directory in File Explorer.
  2.
Fancy: the following is an outline, therre are many ways to actually implement it.
     *
Run "taskkill /IM <script-name>.exe 2>&1 >%TMP%/error.txt" command to try to kill the running exe. Of course, presumably you don't need a file, just use the appropriate Windows API.
     *
If you used a. above, the file will contain a single line that starts with SUCCESS if the exe was running (and is killed) and with ERROR otherwise. You may need to wait a bit for actual termination.
     *
Run "ahk2exe /in <script-name>.ahk /silent".
     *
If in step b. you got SUCCESS, then the compiled script was running, so restart it by running the exe file just generated in step c.

Regards,
Peter Koves
________________________________

**Comment by PythonYunfei** [comment]
Just try to change the compile settings of the extension.  Then everything will work fine:
![image](https://github.com/user-attachments/assets/22b73eae-090d-480d-a9bf-55ae8489e663)

Perhaps because I have set the settings long ago and the compiling GUI will prompt normally when I right click to compile.  So, I haven't encount this problem.

**Comment by thqby** [comment]
@kovesp You mean the target file was running when you compiled it, and then the compilation failed. In that case, it's not a bug.

**Comment by kovesp** [comment]
IMHO, it is. It makes the extension far less useful than it could be. The hot key to compile the edited file is then useless.

In any case, I indicated how it could be fixed quite easily.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by thqby** [comment]
> In any case, I indicated how it could be fixed quite easily.
> `taskkill /IM <script-name>.exe`

@kovesp 
If this is what you mean, there will be some problems when there are multiple processes with the same name or the process name is the same as the system key process name.

**Comment by kovesp** [comment]
That was an outline of an implementation ... I was an IT architect for 20 years until I retired in January, developer for 25 before that :-). I would use Windows API-s. If I remember correctly, it's possible to get the full name of the running EXE which would rule out almost any confusion since the EXE is typically in the same directory as the source.

Actually what I don't get, is why the dialogue isn't coming up ... the /silent option is not in the configured compile command.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by thqby** [comment]
> Actually what I don't get, is why the dialogue isn't coming up ... the /silent option is not in the configured compile command.

When the target file already exists, first delete the file through nodejs, and then start the ahk2exe process after success, otherwise you will see an error `operation not permitted`.

> I would use Windows API-s. If I remember correctly, it's possible to get the full name of the running EXE which would rule out almost any confusion since the EXE is typically in the same directory as the source.

The extension runs in nodejs environment, so it can't directly access winapi. I prefer to use the command line to complete this operation. If not, I can only start the ahk process to achieve it.

**Comment by kovesp** [comment]
Got it. An easy solution then would be to ignore not being able to delete the file and do the compile anyway. The dialogue would then come up. Not perfect, but still more convenient than having to run the compiler from File Explorer.

P.S. I never dabbled with node.js or VS Code extensions before, so don't know what's possible. Perhaps now that I've retired I'll try that too :-).

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
