### ISSUE TITLE
[Bug:] `#SingleInstance` 没有提示和补全

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#635]
`#SingleInstance` 没显示对应的提示和补全：
![image](https://github.com/user-attachments/assets/ebfcf02f-f39f-41b4-9c44-2ef63d2c7402)

**Comment by thqby** [comment]
指令只有代码片段的提示和补全

**Comment by PythonYunfei** [comment]
![image](https://github.com/user-attachments/assets/f7afc174-58fa-4c68-b9bb-d097eee95f2e)
感谢黑神更新👍， 已修复。
