### ISSUE TITLE
[Bug:] 当鼠标悬停在`__Init()`上时，插件连同VSCode都炸了

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#637]
Critical 级别的Bug。
在以下代码中，如果鼠标悬停在`__Init`或`__New`上，插件连同VSCode都会炸：
```AHK
class CCC{
	static proto[mod]{
		get{
			na:='proto__' mod
			if ObjHasOwnProp(this,na){
				return this.%na%
			}else{
				proto:=this.%'Cls__' mod%.Prototype.Clone()
				return proto
			}
		}
	}
	static H__C(id){
		inst:={base:this.proto[this._mod]}
		,inst.__Init()
		.__New(this,id)
		return inst
	}
}
```
![image](https://github.com/user-attachments/assets/8f2fd902-5f13-4687-b9d9-bfc289647b35)

怀疑这个是最新版`2.5.5`的Bug。在更早的版本中未出现此问题。怀疑这个Bug是最近的更新（比如#632）造成的。当我把图中的 属性代码块`static proto[mod]{...}`去掉，这个Bug就不会出现。

鼠标不悬停。包含上面代码的文件，打开时间久了，也早晚会炸。

**Comment by thqby** [comment]
问题在`proto:=this.%'Cls__' mod%.Prototype.Clone()`

**Comment by PythonYunfei** [comment]
![image](https://github.com/user-attachments/assets/b5c1746e-86f5-4144-9087-bd9948f1a52b)
即便改成这样也一样炸..
