### ISSUE TITLE
`NumPut()`不能正确高亮`OffSet`

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#638]
![image](https://github.com/user-attachments/assets/2455143a-767c-456b-af95-f45f9d591cb2)

**Comment by thqby** [comment]
![image](https://github.com/user-attachments/assets/a3a795a2-f58c-4eaa-a528-10139c58feed)

**Comment by PythonYunfei** [comment]
![image](https://github.com/user-attachments/assets/a9b8986d-2c20-4380-b47b-eed642855ef0)
如果可以的话，希望最好能 先区分奇数位上传入的参数是`Type`还是`Target`，从而再区分紧随其后的偶数位上的参数是`Number`还是`Offset`。确定参数名后，再根据光标所在位置的参数名，进行加粗高亮。
目前当且仅当传入的参数是字符串时，奇数位对应的参数名才是`Type`；不是字符串，奇数位对应的参数名便是`Target`。

**Comment by PythonYunfei** [comment]
> ![image](https://private-user-images.githubusercontent.com/47076058/386960531-a9b8986d-2c20-4380-b47b-eed642855ef0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NDk5MDcsIm5iZiI6MTczMTg0OTYwNywicGF0aCI6Ii80NzA3NjA1OC8zODY5NjA1MzEtYTliODk4NmQtMmMyMC00MzgwLWI0N2ItZWVkNjQyODU1ZWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDEzMjAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZDA2MjYyMjc5ZGUyNzc0NTYxNTk3ZTRmMTYwYzdiNzNiMjlhZGEyOTRlMjcwNGQ5YjMxZjk1Mjk4MzFlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9SM-1FO_FgB_lrS82bzI1UqSU8nLh6V3I-G7wPDv2Gs) 如果可以的话，希望最好能 先区分奇数位上传入的参数是`Type`还是`Target`，从而再区分紧随其后的偶数位上的参数是`Number`还是`Offset`。确定参数名后，再根据光标所在位置的参数名，进行加粗高亮。 目前当且仅当传入的参数是字符串时，奇数位对应的参数名才是`Type`；不是字符串，奇数位对应的参数名便是`Target`。

还有一个更可行的区分方法：
当且仅当是最后一个奇数位时，参数名才是`Target`；否则，参数名是`Type`。

**Comment by thqby** [comment]
![1](https://github.com/user-attachments/assets/3bfafbfe-1216-4ce7-b5c2-2f35c61f6ce3)

**Comment by PythonYunfei** [comment]
![image](https://github.com/user-attachments/assets/97125a8c-ca53-4088-a45e-ce5118fc7a65)
您是更新了吗，目前我这没显示高亮。
如果更新了，希望：
(1)位于最前面的两个参数的参数名，始终识别为`Type1`、`Number1`。
(2)如果参数的位置n>=3，位于最后的参数的参数名，从最末一个奇数位参数开始，始终识别为`Target`、`[Offset]`。而不是在中间那两个`*,*`中高亮。

另外希望：
在实现上面(1)、(2)的基础上，如果参数的参数名被识别为`Type1`或`Number1`或`OffSet`，则将对  该位置传入实参的类型进行适度地诊断。如果类型不符合，则报错。

**Comment by PythonYunfei** [comment]
恭喜黑哥插件迎来重磅更新！
不过这个Issue还是未修复：
![image](https://github.com/user-attachments/assets/94d18460-8346-441f-a481-be926f0b17c3)
和预期之间还是有出入。
静待黑神佳音..
