### ISSUE TITLE
[Bug:] 实例方法的提示和补全失效

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#642]
在#633 中，将示例代码换成下面的[Code2]，仍然会变回失效：
[Code2:]
```AHK
class CCC {
	static Call(){
		;return {base: CCC.Prototype}
		return (Object.Call)(this)
	}
	ff3(){
		OutputDebug(789)
	}
}
x:=CCC()
x.ff3
```
![image](https://github.com/user-attachments/assets/8624fc18-e16f-460d-9191-9456978368db)

**Comment by PythonYunfei** [comment]
`Object`的子类调用方式，如：`return (Object.Call)(this)`，自然也不行。变回提示和补全失效。

**Comment by thqby** [comment]
1. 改成super()
2. 加类型标注

**Comment by PythonYunfei** [comment]
希望能假设：`(任意类型.Call)(this,args*)`一定能返回 `this`的实例。即 返回`CCC`的实例。就像`Super()`的返回一样。

这应该也是面向对象构造方法（静态Call）的惯例。
