### ISSUE TITLE
Many Issues while loading included files

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#643]
This has happened before:
The extension **sometimes** has troubles loading the included classes and functions.

For example, if you open a folder and open a file that is not the main file (say a file in the lib folder) and then you close vs code and re open it with that being the first file open, none of the classes load correctly.
![image](https://github.com/user-attachments/assets/6cca914f-4d2c-4071-a27f-f7fbbb2a4786)

Usually you can go to the main script file in the root folder and `set script dir` to "fix" the problem.

But that isnt working at the moment... at least not consistently. Some times that doesnt help.

Opening the main script file (in the root folder) and then reopening vs code also has issues some times and then you are forced to modify the file before the parser even tries to load the classes or included files.

Some times even after modifying the file and seting the script dir and reloading you still have issues with many classes being marked as not found.

This was not as common before. Not sure what changed.

**Comment by RaptorX** [comment]
This is one of those issues that are present on the new version of the extension:
>[Error - 10:54:12 AM] Request workspace/executeCommand failed.
   Message: Request workspace/executeCommand failed with message: Maximum call stack size exceeded
   Code: -32603 

here is an example of when it happens
https://github.com/user-attachments/assets/8a2dd074-7274-4d07-9c45-3e05b236a120

**Comment by RaptorX** [comment]
This issue isnt solved in the new version (`2.5.6`) yet:

https://github.com/user-attachments/assets/89ae6ce7-0434-4f37-b48a-87b42da3506c

Version `2.5.5` introduced the bug.
Version `2.5.6` works mostly as expected as far as I can tell.

**Comment by thqby** [comment]
how to reproduce?

**Comment by thqby** [comment]
Does your path contain symbolic links?

**Comment by RaptorX** [comment]
> Does your path contain symbolic links?

No but I think i found out what might be the reason: The folder is in a virtual location so to speak:

I created virtual drives using the registry and `substr` to basically point a drive letter to a folder:


https://github.com/user-attachments/assets/025e2c14-1a80-4f17-9ad0-2b81ef0bd6aa

when opening the folder with VSCode using the Virtual Drive (G:/) I get a lot of errors. When opening **the exact same folder** via the real location, i get no errors.

So, while I do not use symbolic links, im using virtual locations. So apparently since 2.5.5 whatever method you are using to list the files can no longer follow these special paths correctly.

If you need info on how i created the drives so you can test I can provide it.

**Comment by thqby** [comment]
I figured out the source of the bug yesterday.

```
dir := A_WorkingDir '\test'
DirCreate(dir), SetWorkingDir(dir)
FileAppend('', dir '\test.txt')
drive := SubStr(A_ScriptDir, 1, 2)
; Lack of slash has different behavior
; drive := SubStr(A_ScriptDir, 1, 3)
loop files drive '*'
    MsgBox A_LoopFileName
DirDelete(dir, true)
```

**Comment by RaptorX** [comment]
Thats a very interesting find but im not sure that might be related to the one I'm reporting.
Your findings might be causing similar issues in other parts of the code i guess.

My problem is that:

this path: `G:\Jeff_B\Prospect Finder\`
and this path:  `D:\Cloud\RaptorX\Dropbox\Guests\Jeff_B\Prospect Finder\`

Are exactly the same. But either VSCode or the Extension are not properly parsing `G:\` because that is a virtual drive.

This was not a problem on `v2.5.4` tough. Something changed after `v2.5.5` where this problem started happening with that type of drives.

**Comment by thqby** [comment]
It's the same question. In previous versions, I used a built-in method to restore the case of paths. But this method restores symbolic links and so on to the real path. In this case, I do this by enumerating files.
