### ISSUE TITLE
Addon is reporting wrong parameters for __New()

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#647]
The addon doesn't update the expected class parameters when `__New()` is overridden.  
In the provided example, it should expect 3 parameters for `a, b, c` but instead expects 0-2 for Buffer's `ByteCount, FillByte`.

```
; test extends the buffer class, so the addon expects 0-2 parameters.
class test extends buffer {
    ; This overrides the original __New() method
    ; Calling test should now require 3 params
    __New(a, b, c) {
        MsgBox(a '`n' b '`n' c, 'Test')
    }
}

; The addon shows this as an error because it expects 0-2 parameters
; It's expecting this new: Buffer.__New(ByteCount, FillByte)
; Instead of this new: test.__New(a, b, c)
x := test(1, 2, 3)
```

![Example](https://i.imgur.com/l8b5F95.png)

**Comment by thqby** [comment]
The issue cannot be reproduced. Please check whether ahk2.d.ahk is correct.

**Comment by GroggyOtter** [comment]
That explains it all.
Thanks again. 👍

**Comment by GroggyOtter** [comment]
@thqby - So I'm trying to understand the reasoning for this.  
What does the static all method of Buffer have to do with the __New() method of an instance that extends buffer?  
I don't think I'm quite understanding this.

__New() should be its own thing when creating an instance.  
A static call method should not affect this.

Please help me understand the logic of this b/c it's evading me.

**Comment by thqby** [comment]
```
class Buffer2 extends Buffer {
    static Call(size := 0, val?) => super(size, val?)
}
class test extends Buffer2 {
    __New(a,b,c) => 0
}
test(1,2,3) ; throw
```
