### ISSUE TITLE
[Bug:] 从符号链接的`Lib`路径导入的类,将显示警告

### ISSUE THREAD

**Issue by PythonYunfei** [thqby/vscode-autohotkey2-lsp#650]
如果`A_MyDocuments "\AutoHotkey\LibName1"` 是个符号链接，那么将显示以下警告：
![image](https://github.com/user-attachments/assets/03ad85a3-47d5-4430-87fc-2517f486e766)

如果不是符号链接，则为正常情况：
![image](https://github.com/user-attachments/assets/a3d7f73f-4e86-4c0c-96e3-c7328dfaabc7)

并且，`#include <LibName1>` 也将显示警告： #648

上一个版本无此情况。

**Comment by thqby** [comment]
不能重现

**Comment by PythonYunfei** [comment]
打开符号链接的文件夹，将符号链接中的脚本A拖到VSCode窗口中就能重现。脚本A中所有`#include`进来的变量名将全部显示不存在。
前提是脚本A的源文件夹是从符号链接双击打开的。
