### ISSUE TITLE
switch snippet follows the `switch_case_aligment` settings

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#653]
When typing `switch` we get an snippet and an autosuggestion.

![image](https://github.com/user-attachments/assets/c57aeeb5-c02e-4496-8238-72375255cb1e)

### Result
The autosuggestion follows the aligment settings but the snippet obviously doesnt.

### Expected
We should only get the statement that follows the alignment settings

**Comment by thqby** [comment]
> The autosuggestion follows the aligment settings

What do you mean?

**Comment by RaptorX** [comment]
> > The autosuggestion follows the aligment settings
> 
> What do you mean?

On the extension settings, under "formatting" you can set the switch/case alignment option. 

When using the statement (highlighted in purple above) that setting is in effect. 

If you choose the snippet (the white one, and always the first one on the list) your case statements won't be added and your formatting settings ignored. 

If the snippet wasn't the first and default option on that list, that problem wouldn't be as annoying hehe.

**Comment by PythonYunfei** [comment]
I think the snippet should be removed, remaining the effective one only.

**Comment by RaptorX** [comment]
This problem is not solved.

I see you edited the title of the issue. I would re-word it as:
'switch snippet DOES NOT follow the `switch_case_aligment` settings'

Is there a reason to keep the snippet when you have the keyword as well?

![image](https://github.com/user-attachments/assets/7acec7c6-5edd-4387-8835-251fef695a9e)

**Comment by thqby** [comment]
Remove the first one?

**Comment by thqby** [comment]
The first is the keyword, the second is the code snippet.

**Comment by RaptorX** [comment]
ah then the bug is that the keyword is not following the `switch_case_alignment` setting.
