### ISSUE TITLE
Writable variables acting as read/write on function scope but not on global scope

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#654]
When assigning a value to `A_Clipboard` or `A_TrayTip` ouside of a function they retain their `built-in` variable highlighting.
When doing the same inside a function its color changes.

### Expected 
I think it should either stay as a built-in var or change color in the global scope too.

I think having it change color after the assignment is somewhat useful to know that it was set by the script at some point but it seems inconsistent to only do it in function scope but not outside.

https://github.com/user-attachments/assets/14f827db-3297-431d-a5f9-8951cb3e9513

**Comment by thqby** [comment]
This was broken when module syntax parsing was added, will be fixed later.
