### ISSUE TITLE
since 2.5.9 update, in built-in functions using VarRefs, the first VarRef is flagged as never being assigned a value

### ISSUE THREAD

**Issue by mross** [thqby/vscode-autohotkey2-lsp#660]
For me, since the December update to version 2.5.9, ahk2 functions that use VarRefs have been generating warnings: Variable 'x' appears to never be assigned a value. This happens only for the first VarRef in the comma separated list of arguments.

![image](https://github.com/user-attachments/assets/8612c9e2-5d08-4530-bea0-484a15b601a8)

Oddly, not every instance of this syntax in every file open in my workspace is found -- but it always lights up some of them.
It seems to me that this is a flaw of some kind, but maybe not?

For the moment I'd like to disable this check in vs code settings, but I do not know how to find the names of diagnostic settings.

**Comment by thqby** [comment]
duplicate #658

**Comment by thqby** [comment]
disable Warn.VarUnset
