### ISSUE TITLE
Error if "contains" is used as a method after a fat arrow function

### ISSUE THREAD

**Issue by GroggyOtter** [thqby/vscode-autohotkey2-lsp#661]
The word "contains" triggers an error when it's used after a fat arrow function.  

This is valid code but generates a false error.  
![](https://github.com/user-attachments/assets/6cf3c63a-44c3-43bf-ba94-ececd93aa3d3):  
```
x := test()
MsgBox(x.method() '`n' x.contains())

class test {
    method() => 1
    contains() {
        return 2
    }
}
```

Does not show an error when 2 fat arrow methods are used.  
![](https://github.com/user-attachments/assets/fc7c860b-9ede-4d46-8f86-5d8eb7aee87f) 
```
x := test()
MsgBox(x.method() '`n' x.contains())

class test {
    method() => 1
    contains() => 2
}
```

Does not show an error if two normal methods are used.  
![](https://github.com/user-attachments/assets/3c703800-dc08-4254-9424-47fc6f27b534)
```
x := test()
MsgBox(x.method() '`n' x.contains())

class test {
    method() {
        return 1
    }
    
    contains() {
        return 2
    }
}
```

Edit: Updated images to use github storage.  
IDK why you can't access imgur. it's one of the largest photo repos in the world.

**Comment by thqby** [comment]
Unable to access imgur.com, the issue did not reproduce.

![{9D0228E1-769C-4A1B-8BEA-385FF99C5CB8}](https://github.com/user-attachments/assets/c78d0582-f90d-4758-afd9-abc216119fb1)

**Comment by RaptorX** [comment]
### Image 1
![image](https://github.com/user-attachments/assets/5ed948d5-de22-469e-8723-fb1846c600a7)

### Image 2
![image](https://github.com/user-attachments/assets/28203b8b-6691-434f-9ff6-6a5f088a6263)

### Image 3
![image](https://github.com/user-attachments/assets/c6386be6-15b2-42d9-bc69-d28c106042b1)


In the same order as the comment.

**Comment by GroggyOtter** [comment]
> Unable to access imgur.com.

I updated the images to use github.
