### ISSUE TITLE
Is there a way to set it to automatically open for AHK V2?

### ISSUE THREAD

**Issue by H5820121** [thqby/vscode-autohotkey2-lsp#662]
Is there a way to set it to automatically open for AHK V2 language, and I won't have to select AHK V2 in the languages ​​every time?
Thanks!

**Comment by thqby** [comment]
Have you installed the v1 extension? The file you opened uses v1 syntax?

**Comment by H5820121** [comment]
@thqby
Thanks for the reply!
It opens as a V1 file (it says so on the bottom right next to the bell
icon) and without any colors.



‫בתאריך יום ב׳, 30 בדצמ׳ 2024 ב-1:23 מאת ‪thqby‬‏ ***@***.***
‬‏>:‬

**Comment by H5820121** [comment]
It opens as a V1 file (it says so on the bottom right next to the bell
icon) and without any colors, and without any syntax.

‫בתאריך יום ב׳, 30 בדצמ׳ 2024 ב-1:30 מאת אברהם ברוך ***@***.***
‬‏>:‬

**Comment by thqby** [comment]
set `ActionWhenV1IsDetected` to `continue`

**Comment by thqby** [comment]
set `ActionWhenV1IsDetected` to `continue`

**Comment by H5820121** [comment]
@thqby
I made this setting, and unfortunately it still doesn't help, still at the
bottom right next to the bell icon the inscription AutoHotkey appears, and
as mentioned the script code appears without any colors and syntax.
And I have to manually select AutoHotkey2 in the languages.
But I noticed that this is only when the script file is xxx.ahk, but when
it xxx.ahk2, it is automatically recognized correctly.
Is it possible to define that even when the  file is xxx.ahk it will
automatically be recognized as AHK V2?
On this occasion, I would like to personally thank you for your very useful
extension, Its helps me a lot!

‫בתאריך יום ב׳, 30 בדצמ׳ 2024 ב-3:55 מאת ‪thqby‬‏ ***@***.***
‬‏>:‬

**Comment by thqby** [comment]
Check the settings in `files.associations`.
set `*.ahk`: `ahk2`

**Comment by H5820121** [comment]
It works!
Many thanks!

‫בתאריך יום ב׳, 30 בדצמ׳ 2024 ב-9:46 מאת ‪thqby‬‏ ***@***.***
‬‏>:‬
