### ISSUE TITLE
Parameter hints for functions with default value parameters does not display the @param tagged lines

### ISSUE THREAD

**Issue by Nich-Cebolla** [thqby/vscode-autohotkey2-lsp#663]
When writing the documentation comments for a function that has parameters with default values, the "Parameter hints" widget does not display the parameters.

Example:

```ahk
/**
 * Some other information.
 * @param {number} param - description
 */
Delete(param := 1) {

}
```
If I toggle the "Parameter hints" widget, what I expect to be displayed is a top section with the "@param {number} param - description" text, and underneath "Some other information".
What is actually displayed is only "Some other information."

The same is not true for class methods. This works as expected.
```ahk
class Delete {
    /**
     * @param {number} param - description
     */
    static Call(param := 1) {

    }
}
```

Functions without default value parameters also work as expected.
```ahk
/**
 * Some other information.
 * @param {number} param - description
 */
Delete(param) {

}
```

The order that the content is written impacts whether or not any extra text is displayed. For example, if I move the extra text beneath the "@param" part and then toggle the widget, I do not see any of the content.
```ahk
/**
 * @param {number} param - description
 * Some other information.
 */
Delete(param := 1) {

}
```

Extension is up-to-date as of 12/29

Version: 1.97.0-insider
Commit: 89f808979a5151bd91324e65d4f7ab1b62896983
Date: 2024-12-20T05:04:19.167Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by RaptorX** [comment]
Can confirm on static class methods.
I was going to make a report about that but forgot :P
