### ISSUE TITLE
[1.2.5] Grammar errors for some parameterless function calls

### ISSUE THREAD

**Issue by vmech** [thqby/vscode-autohotkey2-lsp#72]
![](https://i.imgur.com/JbwawEE.png)

**Comment by thqby** [comment]
There is an error in the header file. You can jump to `ahk2.d.ahk` through `goto-define` and modify the function definition to correct this error.

**Comment by aseiot** [comment]
And HotIf, Should be:
`HotIf([FuncOrExpr])`
