### ISSUE TITLE
Wrong comment shown in hover prompt

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#8]
The comment shown when hovering over a variable seems to be limited to one line, and not entirely predictable.  With the following script, the extension (0.7.0) is showing me "It has two lines." for every variable: `startup`, `var1`, `var2`, `var3` and `var4`.

	somefunc startup ; This comment is irrelevant.

	; This is a comment about the assignment below.
	; It has two lines.
	var1 := 1

	; Another comment
	; with two lines.
	var2 := 1

	somefunc(a) {
		
	}

	var3 := 2
	var4 := 4

This was an attempt to demonstrate the issue, but in the original script, it was showing the equivalent of "with two lines." for var2, var3 and var4.

I found that without the top line, none of the variables showed any hover prompt. Going back a couple of steps and removing some irrelevant parts, the file was like this:

	SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
	SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

	; This is a comment about the assignment below.
	; It has two lines.
	var1 := 1

In this case the hover prompt for `Input` and `var1` was "Recommended for new scripts" (etc.). The top lines came from creating the example file from the v1 template, but both lines are valid syntax for v2.

`Input` is the first and only reference, but is not a definition; as of v2.0-a128, it can't possibly be an assignment (ByRef requires `&`).

Obviously, the comment at the top has no relevance to `var1`.  If the SetWorkingDir line is removed or changed to use a naked variable, `var1` shows "It has two lines" instead.

The most minor part of the issue is that the hover prompt only shows the last line of the comment. I would tend to write multi-line comments with semicolon, delimiting with an empty line. I use `/* */` more rarely, such as to disable blocks of code that include multi-line semicolon comments.

**Comment by thqby** [comment]
Support comments on classes, methods and functions (`; ...` and `/*...*/`).
There are many errors in the comments of variables that have not been dealt with.

**Comment by Lexikos** [comment]
0.7.1 seems to work much better, but there doesn't seem to be a way for a comment to apply to multiple variables. Even if they are on the same line, the comment on the line above only applies to the first variable. For example, `v2_name_chars` and `v1_name_char`:

	; For use inside a character class.
	v2_name_chars := '\w\x80-\x{10ffff}', v1_name_chars := v2_name_chars '#@$'
	; Character class matching a single character.
	v1_name_char := '[' v1_name_chars ']', v2_name_char := '[' v2_name_chars ']'

**Comment by Lexikos** [comment]
Looks like 0.7.2 fixed the issue in my previous comment.

In 0.7.2, this does not associate the comment with var, and that's good:

    ; some comment unrelated to var

    var := 1

However, this associates both comments with var, despite the blank line:

    ; some comment unrelated to var

    ; comment about var
    var := 1

In my actual script, the first comment is `;#endregion`, which is used for folding.
