### ISSUE TITLE
Paste errors - version not usable

### ISSUE THREAD

**Issue by dmtr99** [thqby/vscode-autohotkey2-lsp#81]
Version v1.2.9 is not usable for be because it changes code when pasting.
example:

>    } else if (oCommand.text = "Gdip_DrawLines"){
>         Gdip_DrawLines(G, pPen, GUI1.Points)
>     }

becomes:

>     } else if if Command.text = "Gdip_DrawLines") {
>        Gdip_DrawLines(G, G, en, GUI1.Points)
>    }

**Comment by thqby** [comment]
after pasting.
![image](https://user-images.githubusercontent.com/28240311/158000883-7fb7fff4-21fe-46d5-a90a-099a502dee33.png)
No errors found, restart vscode and try again.

**Comment by FuPeiJiang** [comment]
doesn't happen on my vscode

try extension bisect ? <https://code.visualstudio.com/blogs/2021/02/16/extension-bisect>
![](https://code.visualstudio.com/assets/blogs/2021/02/16/bisect.gif)

**Comment by dmtr99** [comment]
Thanks for the replies, I reinstalled it again and It did not happened anymore.
