### ISSUE TITLE
Incorrect folding point

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#82]
Issue Type: <b>Bug</b>

declare a function using curly braces in a line separated from the declaration and fold.

**example:**
````
function() {  ; this works as expected
; some code
}

function() ; when folding this type of declaration the open brace disappears but the closing brace stays displayed
{
; some code
}
````
**Notice the closing braces being displayed when folded:**

![image](https://user-images.githubusercontent.com/328761/158088479-5cd49e00-d481-45ea-a844-ae3654a25110.png)

Extension version: 1.2.9
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.44GB (16.67GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\OneDrive\\Documents\\AutoHotkey\\v1\\250Watch --crash-reporter-id 9034311a-b43a-4975-a160-f9c1e84d1474|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
vscgsvid1:30447480
cppdebug:30451566
pynewfile477cf:30450039

```

</details>

**Comment by thqby** [comment]
This is the same as vscode block folding in other languages. Folding begins at function definitions, including multiple line parameter definitions rather than starting with braces.

**Comment by fade2gray** [comment]
I might be over simplifying this, but doesn't folding only occur where there is indentation, regardless of how you use the braces?

**Comment by RaptorX** [comment]
Yes but here is what other languages do (example with AHK++ extension for VSCode):

![image](https://user-images.githubusercontent.com/328761/158177685-876d1e7c-7912-446b-a178-c1e4e6527cf9.png)

The folding point seems to move to where the open brace is, be it on the line where the open brace is.

**Comment by fade2gray** [comment]
The fold point occurs at the line before the first indentation.
![FoldingIndentation](https://user-images.githubusercontent.com/1332009/158183337-dde16749-85ad-4963-9189-b11107a058ba.PNG)

**Comment by RaptorX** [comment]
I just found where the actual "bug" might be:

It is related to function definitions.

If you define a function and place the brace on the next line you get the folding point at the functions name:
![image](https://user-images.githubusercontent.com/328761/158183495-c880b53f-83b2-41e8-9284-051d763a9328.png)

If you put a space between the function name and the parenthesis (no longer a function definition) the folding point works as expected:
![image](https://user-images.githubusercontent.com/328761/158183981-293b717a-c2fa-4cac-a94e-31224f8f2de9.png)

**Comment by fade2gray** [comment]
Ah, I'm using AutoHokey Plus Plus by Mark Weimer, I assume you are using AutoHotkey++ by Vinny James?
![FoldingIndentation2](https://user-images.githubusercontent.com/1332009/158191595-a30475d9-182c-4d3d-b274-2648f1140bd0.PNG)

To be honest, I've only just realized I'm replying to comments in a repo for AutoHotkey v2. 🤣

**Comment by RaptorX** [comment]
> Ah, I'm using AutoHokey Plus Plus by Mark Weim

I use that one for ahk v1... 
I am using AutoHotkey2 Language Support by **thqby** which is where all this comments are falling to as I sent a bug report to that specific extension (I think)

**Comment by RaptorX** [comment]
> For functions, classes, and class methods, collapse from the beginning of the definition. And the rest of this is curly brace folding, comment folding, continuation string folding.

I would like it to behave as all the other folding logic or at least make it optional, as the current way is not to my liking.
