### ISSUE TITLE
Error while trying to change interpreter

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#83]
We have written the needed data into your 
Issue Type: <b>Bug</b>

# Steps to reproduce
* Install AHK in a different drive.
* Select AutoHotkey2 language
* Click on the interpreter button on the status bar
![path](https://user-images.githubusercontent.com/328761/158920502-ea332f22-a291-44ee-97bd-b65b42e66b90.png)

# Result
![error](https://user-images.githubusercontent.com/328761/158920528-1c7a0ccc-ffc0-414d-92cb-8e4c8fc8a3ac.png)

Extension version: 1.2.9
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.44GB (22.46GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\OneDrive\\Documents\\AutoHotkey\\v2\\lib\\Sqlite --crash-reporter-id 9034311a-b43a-4975-a160-f9c1e84d1474|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
vscgsvid1:30447480
cppdebug:30451566
pynewfile477cf:30450039

```

</details>

clipboard because it was too large to send. Please paste.

**Comment by thqby** [comment]
This will be fixed in the next version.
It is best to specify an AHK directory in your Settings. This is used to switch between different versions of the AHK interpreter in the directory.

**Comment by RaptorX** [comment]
> This will be fixed in the next version. It is best to specify an AHK directory in your Settings. This is used to switch between different versions of the AHK interpreter in the directory.

Yes, I have the directory listed there.

![image](https://user-images.githubusercontent.com/328761/159107258-cc7e2bc3-dc9b-4c31-99a0-0ac1d570fce7.png)

The problem is that the extension is trying C:\  by default even though I set the correct path in the settings.
