### ISSUE TITLE
Request: Extension options

### ISSUE THREAD

**Issue by Anutim** [thqby/vscode-autohotkey2-lsp#86]
Not really sure if this is where this should go, but it'd be very nice to have some option available for disabling association with the .ahk-extension.

(As I'm still mostly using v1, but trying to get into v2 as well.)

**Comment by thqby** [comment]
- You can manually switch the active language plug-in.
- or disable a plug-in in a specified folder.
- or remove this line.
https://github.com/thqby/vscode-autohotkey2-lsp/blob/803a4bf8a6547f1fecfd9e0e9b3e273b7da1911f/package.json#L48

**Comment by Anutim** [comment]
Oh, the third option is what I had been doing so far. But it kept being reset with updates, so that's why I went here to ask.

I didn't know about the other two solutions and I'll try them out, but can I do the "inverse" of option 2 somehow?

**Comment by Anutim** [comment]
Nevermind, found out the answer to my question.

(I'd still like an additional option within the plugin that allows you to disable support for the .ahk extension, but I very much understand if you don't want to add it.)

Thanks for your response and the awesome extension!

**Comment by thqby** [comment]
I don't know whether there is a way to specify the extension association through setting options.

**Comment by fade2gray** [comment]
@Anutim 

I think you'll need to create separate Workspaces for your v1 and v2 scripts, then set the v2 extension as disabled in the v2 Workspace and set the v1 extension as disabled in the v2 workspace.
