### ISSUE TITLE
1.3.1 introduced bug when highliting Error objects

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#87]
Issue Type: <b>Bug</b>

## Issue:

For some reason the Lexer is no longer reporting Error Classes with the correct definition for them. 
It is basically reporting and expecting the Object Class definition.

## Steps:
* create .ahk file
* type the following code:
```
throw TypeError("this is a test")
TypeError()
```

## Expected:
No problems expected:

![image](https://user-images.githubusercontent.com/328761/163095650-5a2c2fe0-0b61-4a87-8003-bb7067cfc038.png)

## Result:
Lexer reports an error:

![image](https://user-images.githubusercontent.com/328761/163095699-254a80ad-5efd-45c0-babe-696eb4f67724.png)

-----

Extension version: 1.3.1
VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (24.91GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\OneDrive\\Documents\\AutoHotkey\\lib\\APICall --crash-reporter-id 9034311a-b43a-4975-a160-f9c1e84d1474|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by thqby** [comment]
I haven't reproduced this bug yet.

**Comment by RaptorX** [comment]
oh thats interesting... let me clean the extension folder and then reinstall.

I did modify the config file to remove the automatic indentation but I dont think that would mess with the lexing in that way.

I will post again if I have issues still.

**Comment by RaptorX** [comment]
Deleting the extension folder and reinstalling seems to fix the problem. This issue can be closed.

![image](https://user-images.githubusercontent.com/328761/163659788-1fa09648-31b7-4d96-a6d7-1d643f4d6da9.png)
