### ISSUE TITLE
Ignored folding point closing comments with spaces

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#89]
Issue Type: <b>Bug</b>

* create a multiline comment
* align the closing tag (with spaces or tabs) 

## Resultt:
Folding will continue/restart on the next folding point.

![image](https://user-images.githubusercontent.com/328761/163727319-51e8cb03-5198-426f-b27f-d5255bf9335d.png)

## Expected:
Folding should end at closing comment tag.

## Notes:
Seems like all other languages have the same issue... maybe a vscode problem instead of the lexer itself?

-----
Extension version: 1.3.1
VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by fade2gray** [comment]
Remove the leading space - the one at the with the red arrow.

**Comment by RaptorX** [comment]
> Remove the leading space - the one with the red arrow.

Im aware that removing the space fixes folding, but shouldn't the spaces be ignored for folding?

**Comment by fade2gray** [comment]
Yeah, that's the way VS Code does it, it folds anywhere there's indentation, so you need an unindented line to close folding.

**Comment by thqby** [comment]
`editor. foldingStrategy` is set to `auto`, otherwise, an indentation-based folding strategy is used.

**Comment by RaptorX** [comment]
Seems like there is a way for a language to have full control of folding with the use of [folding range providers](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding).

Maybe this might be an idea for a future feature. ^^

**Comment by thqby** [comment]
This feature has been implemented.
