### ISSUE TITLE
Auto-indent after if/else/loop/etc.

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#9]
It would be helpful if the line after an if/else/loop/etc. (without braces) was auto-indented. The language configuration file has an [indentation rule](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#indentation-rules) for this:

> `indentNextLinePattern` - If a line matches this pattern, then **only the next line** after it should be indented once.

It seems to be ignored if the `increaseIndentPattern` and `decreaseIndentPattern` rules are not also defined.

I got a test pattern working by modifying ahk2.configuration.json, though in my case it stops working when I relaunch VS Code, until after I switch from an .ahk file to a non-.ahk file and back.

**Comment by thqby** [comment]
I have modified the indentation rule in language configuration file, but the configuration did not take effect, so I deleted it.
How did you modify?

**Comment by Lexikos** [comment]
I added this before the final `}`:

	,
	"indentationRules": {
		"increaseIndentPattern": "^((?!\\/\\/).)*(\\{[^}\"'`]*|\\([^)\"'`]*|\\[[^\\]\"'`]*)$",
		"decreaseIndentPattern": "^((?!.*?\\/\\*).*\\*/)?\\s*[\\)\\}\\]].*$",
		"indentNextLinePattern": "^\\s*loop"
	}

Obviously these patterns are not correct, just enough to test with `loop` (case-sensitive). I copy-pasted the first two rules from the [guide](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#indentation-rules) while trying to get it to work.

None of my changes to the language configuration seemed to take effect immediately, so I assume VS Code has to be reloaded. And as I said, after I reload VS Code, I have to switch from an .ahk file to a non-.ahk file and back before it works. Seems like a VS Code bug, but I thought you might get different results.

Using `onEnterRules` might work, but I suppose you would need a rule for indent (using `beforeText`) and another rule for outdent (using `previousLineText`).

**Comment by thqby** [comment]
I add the following code to do a good job of automatic indentation.
```
"indentationRules": {
		"increaseIndentPattern": "^\\s*(((\\}\\s*)?([Ee]lse|[Ff]inally)\\b|[Tt]ry\\b)(?=\\s*([;{].*)?$)|(((\\}\\s*)?([Ee]lse|[Ff]inally)|[Tt]ry)\\s+)?([Ii]f|[Ff]or|[Ww]hile|[Ll]oop)\\b|(\\}\\s*)?[Cc]atch\\b)",
		"decreaseIndentPattern": "^\\s*([Uu]ntil|[Ee]lse|[Cc]atch|[Ff]inally)\\b"
	}
```
But on my other computer, I can't indent it automatically. I need to run the `Reindent Selected Lines` or `Reindent Lines` command to indent it.

**Comment by thqby** [comment]
On my other computer, it can automatically indent after I switch from an .ahk file to a non-.ahk file and back.

**Comment by thqby** [comment]
> I got a test pattern working by modifying ahk2.configuration.json, though in my case it stops working when I relaunch VS Code, until after I switch from an .ahk file to a non-.ahk file and back.

Because I changed the default value of `editor.autoIndent` from `full` to `brackets`.

**Comment by Lexikos** [comment]
Actually, this interferes with the Allman style, i.e. typing `if condition` `` `n `` `{` `` `n `` produces extra indentation:

	if condition
		{
			MsgBox()
		}

I did a lot of searching and found nothing useful. It seems that they "solved" the same problem for JavaScript by removing the `indentNextLinePattern` rule (so there's no auto-indent for if/else/etc. without braces) rather than fixing auto-indentation to adjust the braces, such as by unindenting when you type `{` like in Visual Studio.

Reindent lines produces something worse:

	if condition
		{
		MsgBox()
	}

The best workaround I could find was a hotstring:

    :*B0:`n{::+{tab}

**Comment by thqby** [comment]
add the rules when type `{` decrease indent, but `}` will be not auto closing. This is unsolvable.

I submit the issues about this, hope to re-indent the current line when typing `enter`.
