### ISSUE TITLE
#Include误报错

### ISSUE THREAD

**Issue by HiXiJu** [thqby/vscode-autohotkey2-lsp#90]
```
#Include "%A_ScriptDir%\Lib"
#Include "xxx.ah2"
```
按F5可以正常运行
但是代码提示会将第二行标红，鼠标指上去显示的路径不对

**Comment by thqby** [comment]
插件设置，设置正确的解释器路径，才能解析include

**Comment by HiXiJu** [comment]
> 插件设置，设置正确的解释器路径，才能解析include

解释器路径有设置的，我重新确认了一下

- 单独打开这个文件时，代码提示不会标红
- 用工作区打开时，代码提示标红

可能是插件把A_ScriptDir解释为工作区目录了，而我这个文件在工作区的子目录下

**Comment by RaptorX** [comment]
This is the same issue as #91... the plugin is not taking into consideration **subfolders** inside the working directory.
