### ISSUE TITLE
#include <name> invalid

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#91]
Issue Type: <b>Bug</b>

* Include a file that is on the local library
* do not set a full path, just the name to the ahk file

## Result: 
![image](https://user-images.githubusercontent.com/328761/164765384-482d8629-d700-4119-b839-76d972830e88.png)
---

Notice that adding libraries that are inside folders seem to work fine (even though those libraries are in my user folder, so not sure if that affects the result).

it works fine if I use `lib\command.ahk` instead.

Extension version: 1.3.1
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (22.56GB free)|
|Process Argv|--crash-reporter-id 9034311a-b43a-4975-a160-f9c1e84d1474|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by RaptorX** [comment]
as suspected, removing the libraries from my user library caused the lexer to mark the includes as invalid even though they are all present in the local lib folder:

![image](https://user-images.githubusercontent.com/328761/164769514-bafc0417-07bf-4b8c-bee7-07087222c1a6.png)

**Comment by thqby** [comment]
When a folder is opened, it is assumed that the script entry is in the root of the folder.

**Comment by RaptorX** [comment]
> When a folder is opened, it is assumed that the script entry is in the root of the folder.

How about making that relative to the current file path?

**Usually my folder structure looks like this:**
![image](https://user-images.githubusercontent.com/328761/164913349-557f3552-a216-488b-8d24-3d0e7b324263.png)

**and in the src folder you can find this:**
![image](https://user-images.githubusercontent.com/328761/164913354-b0403280-89fc-4146-a35f-b538870e6c2e.png)

As you cannot possibly predict every single folder structure out there I think it is safer to just use the relative path of the current file and if the `#include` uses `<file>` try to search for a `lib` folder relative to that specific file.

**Comment by Lexikos** [comment]
> When a folder is opened, it is assumed that the script entry is in the root of the folder.

That makes sense if you use one workspace/window per script. What if:
  - you have a folder full of unrelated scripts?
  - you prefer to work on multiple scripts within one window?
  - one project has multiple script entries (e.g. a main script and a separate setup script)?

If you scan everything in the workspace (I suspect you do, as I was getting false error popups about "invalid encoding" of unrelated v1 .ahk files), it may be possible to identify the main script file as the one (if there's only one) which \#includes the current file but isn't \#included itself.

**Comment by thqby** [comment]
> **Usually my folder structure looks like this:**
![image](https://user-images.githubusercontent.com/328761/164913349-557f3552-a216-488b-8d24-3d0e7b324263.png)
>
> **and in the src folder you can find this:**
![image](https://user-images.githubusercontent.com/328761/164913354-b0403280-89fc-4146-a35f-b538870e6c2e.png)

Such a directory structure (containing lib subfolders) will also be regarded as a script entry dir.

It doesn't work when `#include < local library >` is used, so it is characterized by the existence of `Lib` subfolders.

**Comment by RaptorX** [comment]
> It doesn't work when #include < local library > is used, so it is characterized by the existence of Lib subfolders.

So basically you are saying that it should work? because I don't understand why it marks it as an error then.

remember that in my example, `script.ahk` and `lib/library.ahk` are NOT in the main working directory but in a subdirectory named `src` and in that situation the Lexer is not taking them into cosideration.
