### ISSUE TITLE
EnvSet("var") incorrectly marked as error

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#93]
The following are incorrectly marked as errors:
```AutoHotkey
EnvSet "var"
EnvSet("var")
```
This is no doubt due to an oversight in the AutoHotkey v2 documentation which I have corrected (var is deleted if the value is omitted).

How can a user correct such errors, to avoid the annoying underline prior to the extension being updated?

**Comment by thqby** [comment]
Go to the definition and modify `.d.ahk` file.
