### ISSUE TITLE
Unwanted automatic modification of `/*@...Version 1.0`

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#94]
If I try to save the following code into a script file with the extension active, the version number is unexpectedly changed to `1.0.1`.
```AutoHotkey
/* @SomethingVersion 1.0
```
becomes
```AutoHotkey
/* @SomethingVersion 1.0.1
```
This seems like it would have to be a "feature", but I could not find any documentation for it and do not want it.

**Comment by Lexikos** [comment]
Actually, if I modify the file and save it with the third number still present, I see that it is incremented. I do not want to count the number of times I save a file privately before even releasing it or committing changes to version control.

`1.0.0-alpha.1` is changed to `1.0.1-alpha.1`, which doesn't make any sense. It would make more sense to use a pre-release version suffix to track such changes.

**Comment by RaptorX** [comment]
Yes, I noticed the same thing

I had this on my code:

```
;#version 1.0
#Requires Autohotkey v2.0-
```

And the lexer would automatically update the version when i hit Ctrl+S (if there were changes on the file).

Adding a hyphen next to "version" fixed the issue

```
;#version-1.0
```

I would suggest the lexer should not implement additional 'features' outside of lexing and if there are, they should be optional and displayed on the extension settings page. Or at least documented.
