### ISSUE TITLE
`HasMethod(Value, Name)` should be `HasMethod(Value [, Name, ParamCount])`

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#96]
Likewise for GetMethod.

The functions can be used this way since v2.0-a132 to verify that *Value* itself is callable with a given number of parameters.

**Comment by RaptorX** [comment]
I think I could try to update those kind of things, I know where they are located and how to update them in the lexer.

Will probably fork it and submit pull requests for him.
